## .gitlab-ci.yml
## Configuration for CI/CD for NSWConfiguration

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SSL_NO_VERIFY: "true"
  MAKE_OPTIONS: -j3
  CMAKE_JOB_OPTIONS: -DNSW_STANDALONE_CI_BUILD=ON

stages:
  - build
  - test
  - quality
  - reports

include:
  - project: 'atlas-muon-nsw-daq/nsw-build-scripts'
    ref: 'master'
    file: '.gitlab/ci/code-quality.yml'
  - .gitlab/ci/build-and-test.yml

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: $CI_JOB_ID
    - when: always
