## .gitlab-ci.yml
## Configuration for CI/CD for NSWConfiguration

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SSL_NO_VERIFY: "true"
  MAKE_OPTIONS: -j3
  CMAKE_JOB_OPTIONS: -DNSW_STANDALONE_CI_BUILD=ON

stages:
  - build
  - test
  - quality
  - docs
  - reports
  - deploy

include:
  - project: 'atlas-muon-nsw-daq/infrastructure/nsw-build-scripts'
    ref: 'master'
    file:
      - '.gitlab/ci/code-quality.yml'
      - '.gitlab/ci/build-and-test.yml'
      - '.gitlab/ci/docs.yml'
      - '.gitlab/ci/deploy.yml'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH