# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "")
set(CPACK_BINARY_IFW "")
set(CPACK_BINARY_NSIS "")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "")
set(CPACK_BINARY_STGZ "")
set(CPACK_BINARY_TBZ2 "")
set(CPACK_BINARY_TGZ "")
set(CPACK_BINARY_TXZ "")
set(CPACK_BINARY_TZ "")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines;/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "NSWConfiguration_noarch-NSWConfiguration-00-00-06-15-gc314d2d;NSWConfiguration_src-NSWConfiguration-00-00-06-15-gc314d2d;NSWConfiguration_x86_64-centos7-gcc8-opt-NSWConfiguration-00-00-06-15-gc314d2d;WithoutLCG_x86_64-centos7-gcc8-opt;noarch;src;stgc_baselines_src-;x86_64-centos7-gcc8-opt")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_GENERATOR "RPM")
set(CPACK_INSTALL_CMAKE_PROJECTS "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration;NSWDAQ;ALL;/")
set(CPACK_INSTALL_PREFIX "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/installed")
set(CPACK_MODULE_PATH "/cvmfs/atlas.cern.ch/repo/sw/tdaq/tdaq/tdaq-08-03-01/installed/share/cmake/modules;/cvmfs/atlas.cern.ch/repo/sw/tdaq/tdaq-common/tdaq-common-03-04-01/installed/share/cmake/modules;/cvmfs/atlas.cern.ch/repo/sw/tdaq/tdaq-common/tdaq-common-03-04-01/installed/share/cmake_tdaq/cmake/modules;/cvmfs/atlas.cern.ch/repo/sw/tdaq/tdaq-common/tdaq-common-03-04-01/installed/share/cmake/modules")
set(CPACK_NSIS_DISPLAY_NAME "NSWDAQ 1.0.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "NSWDAQ 1.0.0")
set(CPACK_OUTPUT_CONFIG_FILE "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.14.2/Linux-x86_64/share/cmake-3.14/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Atlas TDAQ Software")
set(CPACK_PACKAGE_FILE_NAME "NSWDAQ-01-00-00")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "NSWDAQ 1.0.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "NSWDAQ 1.0.0")
set(CPACK_PACKAGE_NAME "NSWDAQ")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Atlas TDAQ")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PACKAGING_INSTALL_PREFIX "/sw/atlas/NSWDAQ/NSWDAQ-01-00-00/installed")
set(CPACK_RESOURCE_FILE_LICENSE "/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.14.2/Linux-x86_64/share/cmake-3.14/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.14.2/Linux-x86_64/share/cmake-3.14/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.14.2/Linux-x86_64/share/cmake-3.14/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_COMPONENT_INSTALL "ON")
set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "/sw/atlas/NSWDAQ/NSWDAQ-01-00-00/installed/share/cmake")
set(CPACK_RPM_NO_INSTALL_PREFIX_RELOCATION "TRUE")
set(CPACK_RPM_NSWConfiguration_noarch-NSWConfiguration-00-00-06-15-gc314d2d_PACKAGE_ARCHITECTURE "noarch")
set(CPACK_RPM_NSWConfiguration_noarch-NSWConfiguration-00-00-06-15-gc314d2d_PACKAGE_PROVIDES "/bin/sh")
set(CPACK_RPM_NSWConfiguration_noarch-NSWConfiguration-00-00-06-15-gc314d2d_USER_BINARY_SPECFILE "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration/NSWConfiguration/template_noarch.spec")
set(CPACK_RPM_NSWConfiguration_src-NSWConfiguration-00-00-06-15-gc314d2d_PACKAGE_ARCHITECTURE "noarch")
set(CPACK_RPM_NSWConfiguration_src-NSWConfiguration-00-00-06-15-gc314d2d_PACKAGE_PREFIX "/sw/atlas/NSWDAQ/NSWDAQ-01-00-00")
set(CPACK_RPM_NSWConfiguration_src-NSWConfiguration-00-00-06-15-gc314d2d_PACKAGE_REQUIRES "NSWDAQ-01-00-00_NSWConfiguration_noarch = NSWConfiguration_00_00_06_15_gc314d2d")
set(CPACK_RPM_NSWConfiguration_src-NSWConfiguration-00-00-06-15-gc314d2d_USER_BINARY_SPECFILE "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration/NSWConfiguration/template_src.spec")
set(CPACK_RPM_NSWConfiguration_x86_64-centos7-gcc8-opt-NSWConfiguration-00-00-06-15-gc314d2d_PACKAGE_REQUIRES "NSWDAQ-01-00-00_NSWConfiguration_noarch = NSWConfiguration_00_00_06_15_gc314d2d")
set(CPACK_RPM_NSWConfiguration_x86_64-centos7-gcc8-opt-NSWConfiguration-00-00-06-15-gc314d2d_USER_BINARY_SPECFILE "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration/NSWConfiguration/template_binary.spec")
set(CPACK_RPM_PACKAGE_AUTOPROV "NO")
set(CPACK_RPM_PACKAGE_AUTOREQ "NO")
set(CPACK_RPM_PACKAGE_GROUP "Atlas/TDAQ")
set(CPACK_RPM_PACKAGE_RELOCATABLE "TRUE")
set(CPACK_RPM_RELOCATION_PATHS "/sw/atlas")
set(CPACK_RPM_WithoutLCG_x86_64-centos7-gcc8-opt_PACKAGE_PROVIDES "/bin/sh")
set(CPACK_RPM_WithoutLCG_x86_64-centos7-gcc8-opt_PACKAGE_REQUIRES "/bin/sh,tdaq-08-03-01_WithoutLCG_x86_64-centos7-gcc8-opt
Requires: NSWDAQ-01-00-00_NSWConfiguration_x86_64-centos7-gcc8-opt
Requires: NSWDAQ-01-00-00_stgc_baselines_x86_64-centos7-gcc8-opt
Requires: NSWDAQ-01-00-00_noarch")
set(CPACK_RPM_WithoutLCG_x86_64-centos7-gcc8-opt_USER_BINARY_SPECFILE "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration/template_lcg.spec")
set(CPACK_RPM_noarch_PACKAGE_ARCHITECTURE "noarch")
set(CPACK_RPM_noarch_PACKAGE_PROVIDES "NSWDAQ_NSWDAQ_01_00_00_noarch")
set(CPACK_RPM_noarch_PACKAGE_REQUIRES "/bin/sh")
set(CPACK_RPM_noarch_USER_BINARY_SPECFILE "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration/template_noarch.spec")
set(CPACK_RPM_src_PACKAGE_ARCHITECTURE "noarch")
set(CPACK_RPM_src_PACKAGE_PREFIX "/sw/atlas/NSWDAQ/NSWDAQ-01-00-00")
set(CPACK_RPM_src_PACKAGE_REQUIRES "/bin/sh
Requires: NSWDAQ-01-00-00_NSWConfiguration_src
Requires: NSWDAQ-01-00-00_stgc_baselines_src")
set(CPACK_RPM_src_USER_BINARY_SPECFILE "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration/template_src.spec")
set(CPACK_RPM_stgc_baselines_noarch-_PACKAGE_ARCHITECTURE "noarch")
set(CPACK_RPM_stgc_baselines_noarch-_PACKAGE_PROVIDES "/bin/sh")
set(CPACK_RPM_stgc_baselines_noarch-_USER_BINARY_SPECFILE "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration/stgc_baselines/template_noarch.spec")
set(CPACK_RPM_stgc_baselines_src-_PACKAGE_ARCHITECTURE "noarch")
set(CPACK_RPM_stgc_baselines_src-_PACKAGE_PREFIX "/sw/atlas/NSWDAQ/NSWDAQ-01-00-00")
set(CPACK_RPM_stgc_baselines_src-_PACKAGE_REQUIRES "NSWDAQ-01-00-00_stgc_baselines_noarch = NSWConfiguration_00_00_06_15_gc314d2d")
set(CPACK_RPM_stgc_baselines_src-_USER_BINARY_SPECFILE "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration/stgc_baselines/template_src.spec")
set(CPACK_RPM_stgc_baselines_x86_64-centos7-gcc8-opt-_PACKAGE_REQUIRES "NSWDAQ-01-00-00_stgc_baselines_noarch = NSWConfiguration_00_00_06_15_gc314d2d")
set(CPACK_RPM_stgc_baselines_x86_64-centos7-gcc8-opt-_USER_BINARY_SPECFILE "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration/stgc_baselines/template_binary.spec")
set(CPACK_RPM_x86_64-centos7-gcc8-opt_PACKAGE_PROVIDES "/bin/sh, NSWDAQ_NSWDAQ_01_00_00_x86_64_centos7_gcc8_opt, NSWDAQ_1.0.0_x86_64_centos7_gcc8_opt")
set(CPACK_RPM_x86_64-centos7-gcc8-opt_PACKAGE_REQUIRES ",tdaq_tdaq_08_03_01_x86_64_centos7_gcc8_opt
Requires: NSWDAQ-01-00-00_WithoutLCG_x86_64-centos7-gcc8-opt
Requires: NSWDAQ-01-00-00_noarch")
set(CPACK_RPM_x86_64-centos7-gcc8-opt_USER_BINARY_SPECFILE "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration/template_project.spec")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "RPM")
set(CPACK_SOURCE_IGNORE_FILES "/installed/;/.svn/;/.git/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_ZIP "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/afs/cern.ch/work/n/nswdaq/public/sTGC_quick_and_dirty_baselines/NSWConfiguration/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
