#include "NSWConfiguration/monitoring/StgctpInRunStatusRegisters.h"

nsw::mon::StgctpInRunStatusRegisters::StgctpInRunStatusRegisters(
  const nsw::hw::DeviceManager& deviceManager) :
  m_devices{deviceManager.getSTGCTps()}, m_helper{NUM_CONCURRENT}
{}

void nsw::mon::StgctpInRunStatusRegisters::monitor(ISInfoDictionary* isDict,
                                                 const std::string_view serverName)
{
  m_helper.monitorAndPublish(m_devices.get(),
                             isDict,
                             m_threadPool,
                             serverName,
                             NAME,
                             nsw::mon::StgctpInRunStatusRegisters::getData);
}

nsw::mon::is::StgctpInRunStatusRegisters nsw::mon::StgctpInRunStatusRegisters::getData(
  const nsw::hw::STGCTP& tp)
{
  auto is = nsw::mon::is::StgctpInRunStatusRegisters{};
//  is.RegName=tp.readRegister("i2cAddress.RegName");
//
is.horx_mgm_regs_env_mon_data_RO_0=tp.readRegister("horx_mgm_regs.env_mon_data_RO_0");
is.horx_mgm_regs_upod_tx_temp_RO_0=tp.readRegister("horx_mgm_regs.upod_tx_temp_RO_0");
is.horx_mgm_regs_upod_tx_temp_RO_1=tp.readRegister("horx_mgm_regs.upod_tx_temp_RO_1");
is.horx_mgm_regs_upod_tx_temp_RO_2=tp.readRegister("horx_mgm_regs.upod_tx_temp_RO_2");
is.horx_mgm_regs_upod_rx_temp_RO_0=tp.readRegister("horx_mgm_regs.upod_rx_temp_RO_0");
is.horx_mgm_regs_upod_rx_temp_RO_1=tp.readRegister("horx_mgm_regs.upod_rx_temp_RO_1");
is.horx_mgm_regs_upod_rx_temp_RO_2=tp.readRegister("horx_mgm_regs.upod_rx_temp_RO_2");
is.horx_mgm_regs_upod_tx_loss_RO_0=tp.readRegister("horx_mgm_regs.upod_tx_loss_RO_0");
is.horx_mgm_regs_upod_tx_loss_RO_1=tp.readRegister("horx_mgm_regs.upod_tx_loss_RO_1");
is.horx_mgm_regs_upod_tx_loss_RO_2=tp.readRegister("horx_mgm_regs.upod_tx_loss_RO_2");
is.horx_mgm_regs_upod_rx_loss_RO_0=tp.readRegister("horx_mgm_regs.upod_rx_loss_RO_0");
is.horx_mgm_regs_upod_rx_loss_RO_1=tp.readRegister("horx_mgm_regs.upod_rx_loss_RO_1");
is.horx_mgm_regs_upod_rx_loss_RO_2=tp.readRegister("horx_mgm_regs.upod_rx_loss_RO_2");
is.horx_mgm_regs_upod_tx1_opt_pwr_RO_0=tp.readRegister("horx_mgm_regs.upod_tx1_opt_pwr_RO_0");
is.horx_mgm_regs_upod_tx1_opt_pwr_RO_1=tp.readRegister("horx_mgm_regs.upod_tx1_opt_pwr_RO_1");
is.horx_mgm_regs_upod_tx1_opt_pwr_RO_2=tp.readRegister("horx_mgm_regs.upod_tx1_opt_pwr_RO_2");
is.horx_mgm_regs_upod_tx1_opt_pwr_RO_3=tp.readRegister("horx_mgm_regs.upod_tx1_opt_pwr_RO_3");
is.horx_mgm_regs_upod_tx1_opt_pwr_RO_4=tp.readRegister("horx_mgm_regs.upod_tx1_opt_pwr_RO_4");
is.horx_mgm_regs_upod_tx1_opt_pwr_RO_5=tp.readRegister("horx_mgm_regs.upod_tx1_opt_pwr_RO_5");
is.horx_mgm_regs_upod_tx1_opt_pwr_RO_6=tp.readRegister("horx_mgm_regs.upod_tx1_opt_pwr_RO_6");
is.horx_mgm_regs_upod_tx1_opt_pwr_RO_7=tp.readRegister("horx_mgm_regs.upod_tx1_opt_pwr_RO_7");
is.horx_mgm_regs_upod_tx1_opt_pwr_RO_8=tp.readRegister("horx_mgm_regs.upod_tx1_opt_pwr_RO_8");
is.horx_mgm_regs_upod_tx1_opt_pwr_RO_9=tp.readRegister("horx_mgm_regs.upod_tx1_opt_pwr_RO_9");
is.horx_mgm_regs_upod_tx1_opt_pwr_RO_10=tp.readRegister("horx_mgm_regs.upod_tx1_opt_pwr_RO_10");
is.horx_mgm_regs_upod_tx1_opt_pwr_RO_11=tp.readRegister("horx_mgm_regs.upod_tx1_opt_pwr_RO_11");
is.horx_mgm_regs_upod_tx2_opt_pwr_RO_0=tp.readRegister("horx_mgm_regs.upod_tx2_opt_pwr_RO_0");
is.horx_mgm_regs_upod_tx2_opt_pwr_RO_1=tp.readRegister("horx_mgm_regs.upod_tx2_opt_pwr_RO_1");
is.horx_mgm_regs_upod_tx2_opt_pwr_RO_2=tp.readRegister("horx_mgm_regs.upod_tx2_opt_pwr_RO_2");
is.horx_mgm_regs_upod_tx2_opt_pwr_RO_3=tp.readRegister("horx_mgm_regs.upod_tx2_opt_pwr_RO_3");
is.horx_mgm_regs_upod_tx2_opt_pwr_RO_4=tp.readRegister("horx_mgm_regs.upod_tx2_opt_pwr_RO_4");
is.horx_mgm_regs_upod_tx2_opt_pwr_RO_5=tp.readRegister("horx_mgm_regs.upod_tx2_opt_pwr_RO_5");
is.horx_mgm_regs_upod_tx2_opt_pwr_RO_6=tp.readRegister("horx_mgm_regs.upod_tx2_opt_pwr_RO_6");
is.horx_mgm_regs_upod_tx2_opt_pwr_RO_7=tp.readRegister("horx_mgm_regs.upod_tx2_opt_pwr_RO_7");
is.horx_mgm_regs_upod_tx2_opt_pwr_RO_8=tp.readRegister("horx_mgm_regs.upod_tx2_opt_pwr_RO_8");
is.horx_mgm_regs_upod_tx2_opt_pwr_RO_9=tp.readRegister("horx_mgm_regs.upod_tx2_opt_pwr_RO_9");
is.horx_mgm_regs_upod_tx2_opt_pwr_RO_10=tp.readRegister("horx_mgm_regs.upod_tx2_opt_pwr_RO_10");
is.horx_mgm_regs_upod_tx2_opt_pwr_RO_11=tp.readRegister("horx_mgm_regs.upod_tx2_opt_pwr_RO_11");
is.horx_mgm_regs_upod_tx3_opt_pwr_RO_0=tp.readRegister("horx_mgm_regs.upod_tx3_opt_pwr_RO_0");
is.horx_mgm_regs_upod_tx3_opt_pwr_RO_1=tp.readRegister("horx_mgm_regs.upod_tx3_opt_pwr_RO_1");
is.horx_mgm_regs_upod_tx3_opt_pwr_RO_2=tp.readRegister("horx_mgm_regs.upod_tx3_opt_pwr_RO_2");
is.horx_mgm_regs_upod_tx3_opt_pwr_RO_3=tp.readRegister("horx_mgm_regs.upod_tx3_opt_pwr_RO_3");
is.horx_mgm_regs_upod_tx3_opt_pwr_RO_4=tp.readRegister("horx_mgm_regs.upod_tx3_opt_pwr_RO_4");
is.horx_mgm_regs_upod_tx3_opt_pwr_RO_5=tp.readRegister("horx_mgm_regs.upod_tx3_opt_pwr_RO_5");
is.horx_mgm_regs_upod_tx3_opt_pwr_RO_6=tp.readRegister("horx_mgm_regs.upod_tx3_opt_pwr_RO_6");
is.horx_mgm_regs_upod_tx3_opt_pwr_RO_7=tp.readRegister("horx_mgm_regs.upod_tx3_opt_pwr_RO_7");
is.horx_mgm_regs_upod_tx3_opt_pwr_RO_8=tp.readRegister("horx_mgm_regs.upod_tx3_opt_pwr_RO_8");
is.horx_mgm_regs_upod_tx3_opt_pwr_RO_9=tp.readRegister("horx_mgm_regs.upod_tx3_opt_pwr_RO_9");
is.horx_mgm_regs_upod_tx3_opt_pwr_RO_10=tp.readRegister("horx_mgm_regs.upod_tx3_opt_pwr_RO_10");
is.horx_mgm_regs_upod_tx3_opt_pwr_RO_11=tp.readRegister("horx_mgm_regs.upod_tx3_opt_pwr_RO_11");
is.horx_mgm_regs_upod_rx1_opt_pwr_RO_0=tp.readRegister("horx_mgm_regs.upod_rx1_opt_pwr_RO_0");
is.horx_mgm_regs_upod_rx1_opt_pwr_RO_1=tp.readRegister("horx_mgm_regs.upod_rx1_opt_pwr_RO_1");
is.horx_mgm_regs_upod_rx1_opt_pwr_RO_2=tp.readRegister("horx_mgm_regs.upod_rx1_opt_pwr_RO_2");
is.horx_mgm_regs_upod_rx1_opt_pwr_RO_3=tp.readRegister("horx_mgm_regs.upod_rx1_opt_pwr_RO_3");
is.horx_mgm_regs_upod_rx1_opt_pwr_RO_4=tp.readRegister("horx_mgm_regs.upod_rx1_opt_pwr_RO_4");
is.horx_mgm_regs_upod_rx1_opt_pwr_RO_5=tp.readRegister("horx_mgm_regs.upod_rx1_opt_pwr_RO_5");
is.horx_mgm_regs_upod_rx1_opt_pwr_RO_6=tp.readRegister("horx_mgm_regs.upod_rx1_opt_pwr_RO_6");
is.horx_mgm_regs_upod_rx1_opt_pwr_RO_7=tp.readRegister("horx_mgm_regs.upod_rx1_opt_pwr_RO_7");
is.horx_mgm_regs_upod_rx1_opt_pwr_RO_8=tp.readRegister("horx_mgm_regs.upod_rx1_opt_pwr_RO_8");
is.horx_mgm_regs_upod_rx1_opt_pwr_RO_9=tp.readRegister("horx_mgm_regs.upod_rx1_opt_pwr_RO_9");
is.horx_mgm_regs_upod_rx1_opt_pwr_RO_10=tp.readRegister("horx_mgm_regs.upod_rx1_opt_pwr_RO_10");
is.horx_mgm_regs_upod_rx1_opt_pwr_RO_11=tp.readRegister("horx_mgm_regs.upod_rx1_opt_pwr_RO_11");
is.horx_mgm_regs_upod_rx2_opt_pwr_RO_0=tp.readRegister("horx_mgm_regs.upod_rx2_opt_pwr_RO_0");
is.horx_mgm_regs_upod_rx2_opt_pwr_RO_1=tp.readRegister("horx_mgm_regs.upod_rx2_opt_pwr_RO_1");
is.horx_mgm_regs_upod_rx2_opt_pwr_RO_2=tp.readRegister("horx_mgm_regs.upod_rx2_opt_pwr_RO_2");
is.horx_mgm_regs_upod_rx2_opt_pwr_RO_3=tp.readRegister("horx_mgm_regs.upod_rx2_opt_pwr_RO_3");
is.horx_mgm_regs_upod_rx2_opt_pwr_RO_4=tp.readRegister("horx_mgm_regs.upod_rx2_opt_pwr_RO_4");
is.horx_mgm_regs_upod_rx2_opt_pwr_RO_5=tp.readRegister("horx_mgm_regs.upod_rx2_opt_pwr_RO_5");
is.horx_mgm_regs_upod_rx2_opt_pwr_RO_6=tp.readRegister("horx_mgm_regs.upod_rx2_opt_pwr_RO_6");
is.horx_mgm_regs_upod_rx2_opt_pwr_RO_7=tp.readRegister("horx_mgm_regs.upod_rx2_opt_pwr_RO_7");
is.horx_mgm_regs_upod_rx2_opt_pwr_RO_8=tp.readRegister("horx_mgm_regs.upod_rx2_opt_pwr_RO_8");
is.horx_mgm_regs_upod_rx2_opt_pwr_RO_9=tp.readRegister("horx_mgm_regs.upod_rx2_opt_pwr_RO_9");
is.horx_mgm_regs_upod_rx2_opt_pwr_RO_10=tp.readRegister("horx_mgm_regs.upod_rx2_opt_pwr_RO_10");
is.horx_mgm_regs_upod_rx2_opt_pwr_RO_11=tp.readRegister("horx_mgm_regs.upod_rx2_opt_pwr_RO_11");
is.horx_mgm_regs_upod_rx3_opt_pwr_RO_0=tp.readRegister("horx_mgm_regs.upod_rx3_opt_pwr_RO_0");
is.horx_mgm_regs_upod_rx3_opt_pwr_RO_1=tp.readRegister("horx_mgm_regs.upod_rx3_opt_pwr_RO_1");
is.horx_mgm_regs_upod_rx3_opt_pwr_RO_2=tp.readRegister("horx_mgm_regs.upod_rx3_opt_pwr_RO_2");
is.horx_mgm_regs_upod_rx3_opt_pwr_RO_3=tp.readRegister("horx_mgm_regs.upod_rx3_opt_pwr_RO_3");
is.horx_mgm_regs_upod_rx3_opt_pwr_RO_4=tp.readRegister("horx_mgm_regs.upod_rx3_opt_pwr_RO_4");
is.horx_mgm_regs_upod_rx3_opt_pwr_RO_5=tp.readRegister("horx_mgm_regs.upod_rx3_opt_pwr_RO_5");
is.horx_mgm_regs_upod_rx3_opt_pwr_RO_6=tp.readRegister("horx_mgm_regs.upod_rx3_opt_pwr_RO_6");
is.horx_mgm_regs_upod_rx3_opt_pwr_RO_7=tp.readRegister("horx_mgm_regs.upod_rx3_opt_pwr_RO_7");
is.horx_mgm_regs_upod_rx3_opt_pwr_RO_8=tp.readRegister("horx_mgm_regs.upod_rx3_opt_pwr_RO_8");
is.horx_mgm_regs_upod_rx3_opt_pwr_RO_9=tp.readRegister("horx_mgm_regs.upod_rx3_opt_pwr_RO_9");
is.horx_mgm_regs_upod_rx3_opt_pwr_RO_10=tp.readRegister("horx_mgm_regs.upod_rx3_opt_pwr_RO_10");
is.horx_mgm_regs_upod_rx3_opt_pwr_RO_11=tp.readRegister("horx_mgm_regs.upod_rx3_opt_pwr_RO_11");
is.stgc_tp_regs_sector_id_0=tp.readRegister("stgc_tp_regs.sector_id_0");
is.stgc_tp_regs_small_sector_0=tp.readRegister("stgc_tp_regs.small_sector_0");
is.stgc_tp_regs_mm_disable_0=tp.readRegister("stgc_tp_regs.mm_disable_0");
is.stgc_tp_regs_ignore_pads_0=tp.readRegister("stgc_tp_regs.ignore_pads_0");
is.stgc_tp_regs_ignore_mm_0=tp.readRegister("stgc_tp_regs.ignore_mm_0");
is.stgc_tp_regs_err_bcid_match_RO_0=tp.readRegister("stgc_tp_regs.err_bcid_match_RO_0");
is.stgc_tp_regs_sticky_err_bcid_match_RO_0=tp.readRegister("stgc_tp_regs.sticky_err_bcid_match_RO_0");
is.stgc_tp_regs_pad_hit_rate_RO_0=tp.readRegister("stgc_tp_regs.pad_hit_rate_RO_0");
is.stgc_tp_regs_bcr_rate_RO_0=tp.readRegister("stgc_tp_regs.bcr_rate_RO_0");
is.stgc_tp_regs_bcid_sync_ok_RO_0=tp.readRegister("stgc_tp_regs.bcid_sync_ok_RO_0");
is.stgc_tp_regs_mm_sync_ok_RO_0=tp.readRegister("stgc_tp_regs.mm_sync_ok_RO_0");
is.stgc_tp_regs_pt_fifo_enpty_RO_0=tp.readRegister("stgc_tp_regs.pt_fifo_enpty_RO_0");
is.stgc_tp_regs_pad_idle_status_RO_0=tp.readRegister("stgc_tp_regs.pad_idle_status_RO_0");
is.stgc_tp_regs_mm_idle_status_RO_0=tp.readRegister("stgc_tp_regs.mm_idle_status_RO_0");
is.stgc_tp_regs_to_sl_hit_rate_RO_0=tp.readRegister("stgc_tp_regs.to_sl_hit_rate_RO_0");
is.stgc_tp_regs_pad_arrival_bc_RO_0=tp.readRegister("stgc_tp_regs.pad_arrival_bc_RO_0");
is.stgc_tp_regs_mm_arrival_bc_RO_0=tp.readRegister("stgc_tp_regs.mm_arrival_bc_RO_0");
is.stgc_tp_regs_mon_limit_0=tp.readRegister("stgc_tp_regs.mon_limit_0");
is.stgc_tp_regs_sl_latency_comp_0=tp.readRegister("stgc_tp_regs.sl_latency_comp_0");
is.stgc_tp_regs_disable_nsw_mon_0=tp.readRegister("stgc_tp_regs.disable_nsw_mon_0");
is.stgc_tp_regs_nsw_mon_limit_0=tp.readRegister("stgc_tp_regs.nsw_mon_limit_0");
is.stgc_tp_regs_mm_nsw_mon_en_0=tp.readRegister("stgc_tp_regs.mm_nsw_mon_en_0");
is.stgc_tp_regs_l1a_busy_i_0=tp.readRegister("stgc_tp_regs.l1a_busy_i_0");
is.stgc_tp_regs_l1a_opening_ofst_0=tp.readRegister("stgc_tp_regs.l1a_opening_ofst_0");
is.stgc_tp_regs_l1a_request_ofst_0=tp.readRegister("stgc_tp_regs.l1a_request_ofst_0");
is.stgc_tp_regs_l1a_closing_ofst_0=tp.readRegister("stgc_tp_regs.l1a_closing_ofst_0");
is.stgc_tp_regs_l1a_window_timeout_0=tp.readRegister("stgc_tp_regs.l1a_window_timeout_0");
is.stgc_tp_regs_l1a_busy_threshold_0=tp.readRegister("stgc_tp_regs.l1a_busy_threshold_0");
is.stgc_tp_regs_l1a_busy_o_RO_0=tp.readRegister("stgc_tp_regs.l1a_busy_o_RO_0");
is.stgc_tp_regs_l1a_pad_en_0=tp.readRegister("stgc_tp_regs.l1a_pad_en_0");
is.stgc_tp_regs_l1a_merge_en_0=tp.readRegister("stgc_tp_regs.l1a_merge_en_0");
is.stgc_tp_regs_mon_disable_0=tp.readRegister("stgc_tp_regs.mon_disable_0");
is.stgc_tp_regs_no_strech_0=tp.readRegister("stgc_tp_regs.no_strech_0");
is.stgc_tp_regs_last_pt_data_bcid_RO_0=tp.readRegister("stgc_tp_regs.last_pt_data_bcid_RO_0");
is.stgc_tp_regs_last_pt_data_l1a_bcid_RO_0=tp.readRegister("stgc_tp_regs.last_pt_data_l1a_bcid_RO_0");
is.stgc_tp_regs_l1a_bcid_latency_diff_0=tp.readRegister("stgc_tp_regs.l1a_bcid_latency_diff_0");
is.stgc_tp_regs_last_merge_vseg_bcid_RO_0=tp.readRegister("stgc_tp_regs.last_merge_vseg_bcid_RO_0");
  return is;
}
