variables:
  GIT_STRATEGY: fetch

stages:
- setup
- build

setup:
  stage: setup
  script:
    - export PATH=/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.11.1/Linux-x86_64/bin:$PATH
    - virtualenv python
    - source python/bin/activate
    - pip install six
    
build:
  stage: build
  script:
    - export PATH=/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.11.1/Linux-x86_64/bin:$PATH
    - virtualenv python
    - source python/bin/activate
    - pip install six
    - cd demo
    - sh build.sh
