#ifndef NSWCONFIGURATION_GBTXREGISTERMAP_H
#define NSWCONFIGURATION_GBTXREGISTERMAP_H

#include "NSWConfiguration/Types.h"

static const std::unordered_map<std::string, gbtx::regMap> GBTX_REGISTER_MAP = {
  // clang-format off
  {"paTrainEC",                           {"paTrainEC", "Train EC channel", 1, {0,1,2}, {245,245,245}}},
  {"paTrainGroup6",                       {"paTrainGroup6", "Train channels (0-7)", 8, {0,0,0}, {222,223,224}}},
  {"paTrainGroup5",                       {"paTrainGroup5", "Train channels (0-7)", 8, {0,0,0}, {198,199,200}}},
  {"paTrainGroup4",                       {"paTrainGroup4", "Train channels (0-7)", 8, {0,0,0}, {174,175,176}}},
  {"paTrainGroup3",                       {"paTrainGroup3", "Train channels (0-7)", 8, {0,0,0}, {150,151,152}}},
  {"paTrainGroup2",                       {"paTrainGroup2", "Train channels (0-7)", 8, {0,0,0}, {126,127,128}}},
  {"paTrainGroup1",                       {"paTrainGroup1", "Train channels (0-7)", 8, {0,0,0}, {102,103,104}}},
  {"paTrainGroup0",                       {"paTrainGroup0", "Train channels (0-7)", 8, {0,0,0}, {78,79,80}}},
  {"paResetEC",                           {"paResetEC", "Reset EC channel", 1, {0,1,2}, {251,251,251}}},
  {"paResetGroup0",                       {"paResetGroup0", "Reset channels (0-7)", 8, {0,0,0}, {84,85,86}}},
  {"paResetGroup1",                       {"paResetGroup1", "Reset channels (0-7)", 8, {0,0,0}, {108,109,110}}},
  {"paResetGroup2",                       {"paResetGroup2", "Reset channels (0-7)", 8, {0,0,0}, {132,133,134}}},
  {"paResetGroup3",                       {"paResetGroup3", "Reset channels (0-7)", 8, {0,0,0}, {156,157,158}}},
  {"paResetGroup4",                       {"paResetGroup4", "Reset channels (0-7)", 8, {0,0,0}, {180,181,182}}},
  {"paResetGroup5",                       {"paResetGroup5", "Reset channels (0-7)", 8, {0,0,0}, {204,205,206}}},
  {"paResetGroup6",                       {"paResetGroup6", "Reset channels (0-7)", 8, {0,0,0}, {228,229,230}}},
  {"paPhaseSelectGroup0Channel4",         {"paPhaseSelectGroup0Channel4", "Select sample phase channel 4", 4, {0,0,0}, {67,71,75}}},
  {"paPhaseSelectGroup5Channel4",         {"paPhaseSelectGroup5Channel4", "Select sample phase channel 4", 4, {0,0,0}, {187,191,195}}},
  {"paPhaseSelectGroup5Channel6",         {"paPhaseSelectGroup5Channel6", "Select sample phase channel 6", 4, {0,0,0}, {186,190,194}}},
  {"paPhaseSelectGroup5Channel7",         {"paPhaseSelectGroup5Channel7", "Select sample phase channel 7", 4, {4,4,4}, {186,190,194}}},
  {"paPhaseSelectGroup5Channel0",         {"paPhaseSelectGroup5Channel0", "Select sample phase channel 0", 4, {0,0,0}, {189,193,197}}},
  {"paPhaseSelectGroup5Channel5",         {"paPhaseSelectGroup5Channel5", "Select sample phase channel 5", 4, {4,4,4}, {187,191,195}}},
  {"paPhaseSelectGroup5Channel3",         {"paPhaseSelectGroup5Channel3", "Select sample phase channel 3", 4, {4,4,4}, {188,192,196}}},
  {"paPhaseSelectGroup2Channel3",         {"paPhaseSelectGroup2Channel3", "Select sample phase channel 3", 4, {4,4,4}, {116,120,124}}},
  {"paPhaseSelectGroup2Channel2",         {"paPhaseSelectGroup2Channel2", "Select sample phase channel 2", 4, {0,0,0}, {116,120,124}}},
  {"paPhaseSelectGroup2Channel1",         {"paPhaseSelectGroup2Channel1", "Select sample phase channel 1", 4, {4,4,4}, {117,121,125}}},
  {"paPhaseSelectGroup2Channel0",         {"paPhaseSelectGroup2Channel0", "Select sample phase channel 0", 4, {0,0,0}, {117,121,125}}},
  {"paPhaseSelectGroup2Channel7",         {"paPhaseSelectGroup2Channel7", "Select sample phase channel 7", 4, {4,4,4}, {114,118,122}}},
  {"paPhaseSelectGroup2Channel6",         {"paPhaseSelectGroup2Channel6", "Select sample phase channel 6", 4, {0,0,0}, {114,118,122}}},
  {"paPhaseSelectGroup2Channel5",         {"paPhaseSelectGroup2Channel5", "Select sample phase channel 5", 4, {4,4,4}, {115,119,123}}},
  {"paPhaseSelectGroup2Channel4",         {"paPhaseSelectGroup2Channel4", "Select sample phase channel 4", 4, {0,0,0}, {115,119,123}}},
  {"paPhaseSelectEC",                     {"paPhaseSelectEC", "Select sample phase EC channel", 4, {0,0,0}, {233,237,241}}},
  {"paPhaseSelectGroup4Channel5",         {"paPhaseSelectGroup4Channel5", "Select sample phase channel 5", 4, {4,4,4}, {163,167,171}}},
  {"paPhaseSelectGroup4Channel4",         {"paPhaseSelectGroup4Channel4", "Select sample phase channel 4", 4, {0,0,0}, {163,167,171}}},
  {"paPhaseSelectGroup4Channel7",         {"paPhaseSelectGroup4Channel7", "Select sample phase channel 7", 4, {4,4,4}, {162,166,170}}},
  {"paPhaseSelectGroup4Channel6",         {"paPhaseSelectGroup4Channel6", "Select sample phase channel 6", 4, {0,0,0}, {162,166,170}}},
  {"paPhaseSelectGroup4Channel1",         {"paPhaseSelectGroup4Channel1", "Select sample phase channel 1", 4, {4,4,4}, {165,169,173}}},
  {"paPhaseSelectGroup4Channel0",         {"paPhaseSelectGroup4Channel0", "Select sample phase channel 0", 4, {0,0,0}, {165,169,173}}},
  {"paPhaseSelectGroup4Channel3",         {"paPhaseSelectGroup4Channel3", "Select sample phase channel 3", 4, {4,4,4}, {164,168,172}}},
  {"paPhaseSelectGroup4Channel2",         {"paPhaseSelectGroup4Channel2", "Select sample phase channel 2", 4, {0,0,0}, {164,168,172}}},
  {"paPhaseSelectGroup6Channel7",         {"paPhaseSelectGroup6Channel7", "Select sample phase channel 7", 4, {4,4,4}, {210,214,218}}},
  {"paPhaseSelectGroup6Channel6",         {"paPhaseSelectGroup6Channel6", "Select sample phase channel 6", 4, {0,0,0}, {210,214,218}}},
  {"paPhaseSelectGroup6Channel5",         {"paPhaseSelectGroup6Channel5", "Select sample phase channel 5", 4, {4,4,4}, {211,215,219}}},
  {"paPhaseSelectGroup6Channel3",         {"paPhaseSelectGroup6Channel3", "Select sample phase channel 3", 4, {4,4,4}, {212,216,220}}},
  {"paPhaseSelectGroup6Channel2",         {"paPhaseSelectGroup6Channel2", "Select sample phase channel 2", 4, {0,0,0}, {212,216,220}}},
  {"paPhaseSelectGroup6Channel1",         {"paPhaseSelectGroup6Channel1", "Select sample phase channel 1", 4, {4,4,4}, {213,217,221}}},
  {"paPhaseSelectGroup6Channel0",         {"paPhaseSelectGroup6Channel0", "Select sample phase channel 0", 4, {0,0,0}, {213,217,221}}},
  {"paPhaseSelectGroup5Channel1",         {"paPhaseSelectGroup5Channel1", "Select sample phase channel 1", 4, {4,4,4}, {189,193,197}}},
  {"paPhaseSelectGroup1Channel0",         {"paPhaseSelectGroup1Channel0", "Select sample phase channel 0", 4, {0,0,0}, {93,97,101}}},
  {"paPhaseSelectGroup1Channel1",         {"paPhaseSelectGroup1Channel1", "Select sample phase channel 1", 4, {4,4,4}, {93,97,101}}},
  {"paPhaseSelectGroup1Channel2",         {"paPhaseSelectGroup1Channel2", "Select sample phase channel 2", 4, {0,0,0}, {92,96,100}}},
  {"paPhaseSelectGroup1Channel3",         {"paPhaseSelectGroup1Channel3", "Select sample phase channel 3", 4, {4,4,4}, {92,96,100}}},
  {"paPhaseSelectGroup1Channel4",         {"paPhaseSelectGroup1Channel4", "Select sample phase channel 4", 4, {0,0,0}, {91,95,99}}},
  {"paPhaseSelectGroup1Channel5",         {"paPhaseSelectGroup1Channel5", "Select sample phase channel 5", 4, {4,4,4}, {91,95,99}}},
  {"paPhaseSelectGroup1Channel6",         {"paPhaseSelectGroup1Channel6", "Select sample phase channel 6", 4, {0,0,0}, {90,94,98}}},
  {"paPhaseSelectGroup1Channel7",         {"paPhaseSelectGroup1Channel7", "Select sample phase channel 7", 4, {4,4,4}, {90,94,98}}},
  {"paPhaseSelectGroup6Channel4",         {"paPhaseSelectGroup6Channel4", "Select sample phase channel 4", 4, {0,0,0}, {211,215,219}}},
  {"paPhaseSelectGroup3Channel0",         {"paPhaseSelectGroup3Channel0", "Select sample phase channel 0", 4, {0,0,0}, {141,145,149}}},
  {"paPhaseSelectGroup5Channel2",         {"paPhaseSelectGroup5Channel2", "Select sample phase channel 2", 4, {0,0,0}, {188,192,196}}},
  {"paPhaseSelectGroup3Channel2",         {"paPhaseSelectGroup3Channel2", "Select sample phase channel 2", 4, {0,0,0}, {140,144,148}}},
  {"paPhaseSelectGroup3Channel3",         {"paPhaseSelectGroup3Channel3", "Select sample phase channel 3", 4, {4,4,4}, {140,144,148}}},
  {"paPhaseSelectGroup3Channel1",         {"paPhaseSelectGroup3Channel1", "Select sample phase channel 1", 4, {4,4,4}, {141,145,149}}},
  {"paPhaseSelectGroup3Channel6",         {"paPhaseSelectGroup3Channel6", "Select sample phase channel 6", 4, {0,0,0}, {138,142,146}}},
  {"paPhaseSelectGroup3Channel7",         {"paPhaseSelectGroup3Channel7", "Select sample phase channel 7", 4, {4,4,4}, {138,142,146}}},
  {"paPhaseSelectGroup3Channel4",         {"paPhaseSelectGroup3Channel4", "Select sample phase channel 4", 4, {0,0,0}, {139,143,147}}},
  {"paPhaseSelectGroup3Channel5",         {"paPhaseSelectGroup3Channel5", "Select sample phase channel 5", 4, {4,4,4}, {139,143,147}}},
  {"paPhaseSelectGroup0Channel1",         {"paPhaseSelectGroup0Channel1", "Select sample phase channel 1", 4, {4,4,4}, {69,73,77}}},
  {"paPhaseSelectGroup0Channel0",         {"paPhaseSelectGroup0Channel0", "Select sample phase channel 0", 4, {0,0,0}, {69,73,77}}},
  {"paPhaseSelectGroup0Channel3",         {"paPhaseSelectGroup0Channel3", "Select sample phase channel 3", 4, {4,4,4}, {68,72,76}}},
  {"paPhaseSelectGroup0Channel2",         {"paPhaseSelectGroup0Channel2", "Select sample phase channel 2", 4, {0,0,0}, {68,72,76}}},
  {"paPhaseSelectGroup0Channel5",         {"paPhaseSelectGroup0Channel5", "Select sample phase channel 5", 4, {4,4,4}, {67,71,75}}},
  {"paPhaseSelectGroup0Channel7",         {"paPhaseSelectGroup0Channel7", "Select sample phase channel 7", 4, {4,4,4}, {66,70,74}}},
  {"paPhaseSelectGroup0Channel6",         {"paPhaseSelectGroup0Channel6", "Select sample phase channel 6", 4, {0,0,0}, {66,70,74}}},
  {"i2cResetTx",                          {"i2cResetTx", "reset TX logic", 1, {0,1,2}, {54,54,54}}},
  {"cmReferenceClockSelect",              {"cmReferenceClockSelect", "Selects global reference clock", 2, {0,2,4}, {281,281,281}}},
  {"cmXpllReferenceSelect",               {"cmXpllReferenceSelect", "Selects Xpll reference clock", 2, {0,2,4}, {290,290,290}}},
  {"ePllRxReferenceFreq",                 {"ePllRxReferenceFreq", "Select EPLL-RX reference frequency", 2, {0,2,4}, {242,242,242}}},
  {"enableTermination3",                  {"enableTermination3", "enable Termination group3 channel 7", 8, {0}, {323}}},
  {"cmTxTestMuxSelect40",                 {"cmTxTestMuxSelect40", "Selects TX 40MHz clock C in Test mode", 2, {0,0,0}, {287,288,289}}},
  {"extLate7",                            {"extLate7", " ", 1, {6}, {23}}},
  {"extLate6",                            {"extLate6", " ", 1, {6}, {22}}},
  {"extLate5",                            {"extLate5", " ", 1, {6}, {21}}},
  {"extLate4",                            {"extLate4", " ", 1, {6}, {20}}},
  {"extLate3",                            {"extLate3", " ", 1, {6}, {19}}},
  {"extLate2",                            {"extLate2", " ", 1, {6}, {18}}},
  {"extLate1",                            {"extLate1", " ", 1, {6}, {17}}},
  {"extLate0",                            {"extLate0", " ", 1, {6}, {16}}},
  {"i2cRxFilterEnable",                   {"i2cRxFilterEnable", "i2cRxFilterEnable", 1, {0,1,2}, {45,45,45}}},
  {"modeEc",                              {"modeEc", "mode EC channel", 1, {4,5,6}, {254,254,254}}},
  {"xPllControlOverride",                 {"xPllControlOverride", "Override XPLL control", 1, {0,1,2}, {318,318,318}}},
  {"paDllConfigGroup5",                   {"paDllConfigGroup5", "Set Phase-aligner dll", 4, {0,4,0}, {184,184,185}}},
  {"cmRxTestMuxSelect80",                 {"cmRxTestMuxSelect80", "Selects RX 80MHz clock C in Test mode", 2, {2,2,2}, {277,278,279}}},
  {"paDllConfigGroup4",                   {"paDllConfigGroup4", "Set Phase-aligner dll", 4, {0,4,0}, {160,160,161}}},
  {"ePllRxCap",                           {"ePllRxCap", "Sets EPLL-RX Cap C in filter", 2, {5,5,5}, {307,308,309}}},
  {"ePllTxReset",                         {"ePllTxReset", "Reset of EPLL-TX filter", 1, {0,1,2}, {303,303,303}}},
  {"i2cResetRx",                          {"i2cResetRx", "reset RX logic", 1, {3,4,5}, {50,50,50}}},
  {"i2cRxSkipCycle",                      {"i2cRxSkipCycle", "i2cRxSkipCycle", 1, {0,1,2}, {40,40,40}}},
  {"TXselectPosEdge",                     {"TXselectPosEdge", "select +ve clock edge in TX synchroniser", 1, {3,4,5}, {244,244,244}}},
  {"xPllEnablePhaseDetector",             {"xPllEnablePhaseDetector", "Enable XPLL Phase Detector", 1, {4,5,6}, {317,317,317}}},
  {"ePllRxEnablePhase",                   {"ePllRxEnablePhase", "Enable EPLL-RX phase", 8, {0,0,0}, {304,305,306}}},
  {"paDllConfigGroup1",                   {"paDllConfigGroup1", "Set Phase-aligner dll", 4, {0,4,0}, {88,88,89}}},
  {"ePllTxPhase160MHz",                   {"ePllTxPhase160MHz", "Sets EPLL-TX 160MHz phase", 5, {0,0,0}, {296,297,298}}},
  {"enableTermination5",                  {"enableTermination5", "enable Termination group5 channel 7", 8, {0}, {325}}},
  {"enableTermination4",                  {"enableTermination4", "enable Termination group4 channel 7", 8, {0}, {324}}},
  {"i2cTxReset",                          {"i2cTxReset", "Reset TX control and serialiser", 1, {0,1,2}, {33,33,33}}},
  {"enableTermination1",                  {"enableTermination1", "enable Termination group1 channel 7", 8, {0}, {321}}},
  {"enableTermination0",                  {"enableTermination0", "enable Termination group0 channel 7", 8, {0}, {320}}},
  {"i2cRxSwap",                           {"i2cRxSwap", "", 1, {3,4,5}, {40,40,40}}},
  {"enableTermination2",                  {"enableTermination2", "enable Termination group2 channel 7", 8, {0}, {322}}},
  {"cmRxTestMuxSelect160",                {"cmRxTestMuxSelect160", "Selects RX 160MHz clock C in Test mode", 2, {4,4,4}, {277,278,279}}},
  {"cmRxTestMuxSelect40",                 {"cmRxTestMuxSelect40", "Selects RX 40MHz clock C in Test mode", 2, {0,0,0}, {277,278,279}}},
  {"xPllGmSelect",                        {"xPllGmSelect", "Select XPLL Gm", 4, {0,4,0}, {316,316,317}}},
  {"paEnableEC",                          {"paEnableEC", "Enable EC channel", 1, {0,1,2}, {248,248,248}}},
  {"cset1",                               {"cset1", " ", 4, {4}, {269}}},
  {"rxMaxInvalidHeaders",                 {"rxMaxInvalidHeaders", " ", 8, {0}, {38}}},
  {"paDllConfigGroup3",                   {"paDllConfigGroup3", "Set Phase-aligner dll", 4, {0,4,0}, {136,136,137}}},
  {"paDllConfigGroup2",                   {"paDllConfigGroup2", "Set Phase-aligner dll", 4, {0,4,0}, {112,112,113}}},
  {"i2cRxSelectDataInPhase",              {"i2cRxSelectDataInPhase", "", 1, {3,4,5}, {36,36,36}}},
  {"paDllConfigGroup0",                   {"paDllConfigGroup0", "Set Phase-aligner dll", 4, {0,4,0}, {64,64,65}}},
  {"clockBusFrequency4",                  {"clockBusFrequency4", "clock frequency group4", 2, {2,2,2}, {266,344,359}}},
  {"ePllTxReferenceFreq",                 {"ePllTxReferenceFreq", "Select EPLL-TX reference frequency", 2, {0,2,4}, {243,243,243}}},
  {"clockBusFrequency1",                  {"clockBusFrequency1", "clock frequency group1", 2, {2,2,2}, {257,335,350}}},
  {"clockBusFrequency2",                  {"clockBusFrequency2", "clock frequency group2", 2, {2,2,2}, {260,338,353}}},
  {"PSpllEnable",                         {"PSpllEnable", "enable phase-shifter PLL", 1, {0,1,2}, {52,52,52}}},
  {"paDataRateGroup0",                    {"paDataRateGroup0", "Set Phase-aligner speed", 2, {0,2,4}, {63,63,63}}},
  {"paDataRateGroup1",                    {"paDataRateGroup1", "Set Phase-aligner speed", 2, {0,2,4}, {87,87,87}}},
  {"paDataRateGroup2",                    {"paDataRateGroup2", "Set Phase-aligner speed", 2, {0,2,4}, {111,111,111}}},
  {"paDataRateGroup3",                    {"paDataRateGroup3", "Set Phase-aligner speed", 2, {0,2,4}, {135,135,135}}},
  {"paDataRateGroup4",                    {"paDataRateGroup4", "Set Phase-aligner speed", 2, {0,2,4}, {159,159,159}}},
  {"paDataRateGroup5",                    {"paDataRateGroup5", "Set Phase-aligner speed", 2, {0,2,4}, {183,183,183}}},
  {"paDataRateGroup6",                    {"paDataRateGroup6", "Set Phase-aligner speed", 2, {0,2,4}, {207,207,207}}},
  {"cset5",                               {"cset5", " ", 4, {4}, {271}}},
  {"cset2",                               {"cset2", " ", 4, {0}, {270}}},
  {"cset3",                               {"cset3", " ", 4, {4}, {270}}},
  {"paEnableGroup1",                      {"paEnableGroup1", "Enable channel 7", 8, {0,0,0}, {105,106,107}}},
  {"paEnableGroup0",                      {"paEnableGroup0", "Enable channel 7", 8, {0,0,0}, {81,82,83}}},
  {"paEnableGroup3",                      {"paEnableGroup3", "Enable channel 7", 8, {0,0,0}, {153,154,155}}},
  {"paEnableGroup2",                      {"paEnableGroup2", "Enable channel 7", 8, {0,0,0}, {129,130,131}}},
  {"paEnableGroup5",                      {"paEnableGroup5", "Enable channel 7", 8, {0,0,0}, {201,202,203}}},
  {"paEnableGroup4",                      {"paEnableGroup4", "Enable channel 7", 8, {0,0,0}, {177,178,179}}},
  {"i2cStartRace",                        {"i2cStartRace", "", 1, {0,1,2}, {42,42,42}}},
  {"cset6",                               {"cset6", " ", 4, {0}, {272}}},
  {"paDllConfigGroup6",                   {"paDllConfigGroup6", "Set Phase-aligner dll", 4, {0,4,0}, {208,208,209}}},
  {"cset7",                               {"cset7", " ", 4, {4}, {272}}},
  {"enableWatchdogFSM",                   {"enableWatchdogFSM", "enable watchdog", 1, {0,1,2}, {50,50,50}}},
  {"modeGroup2",                          {"modeGroup2", "mode group2", 2, {0,0,0}, {260,338,353}}},
  {"cmRxPhase40MHz",                      {"cmRxPhase40MHz", "Fine phase delay of RX 40MHz clock", 4, {0,4,0}, {274,274,275}}},
  {"PLLcp",                               {"PLLcp", " ", 4, {0}, {26}}},
  {"cset4",                               {"cset4", " ", 4, {0}, {271}}},
  {"i2cRxSelectI2Freq",                   {"i2cRxSelectI2Freq", " freq detector", 4, {0}, {35}}},
  {"ePllTxEnablePhase",                   {"ePllTxEnablePhase", "Enable EPLL-TX phase", 8, {0,0,0}, {293,294,295}}},
  {"cmTxTestMuxSelect80",                 {"cmTxTestMuxSelect80", "Selects TX 80MHz clock C in Test mode", 2, {2,2,2}, {287,288,289}}},
  {"clkDriveStrength1",                   {"clkDriveStrength1", "set clock drive strength group 1", 4, {0}, {330}}},
  {"cmTxPhase40MHz",                      {"cmTxPhase40MHz", "Fine phase delay of TX 40MHz clock", 4, {0,4,0}, {284,284,285}}},
  {"fuseBlowData",                        {"fuseBlowData", "data to blow fuse", 8, {0}, {240}}},
  {"ePllTxIcp",                           {"ePllTxIcp", "Sets EPLL-TX charge pump current", 4, {0,0,0}, {299,300,301}}},
  {"xPllChargePumpCurrent",               {"xPllChargePumpCurrent", "xPll Charge Pump Current", 4, {0,4,0}, {235,235,236}}},
  {"dataPortEnableGroup2",                {"dataPortEnableGroup2", "enable data group2 channel 7", 8, {0,0,0}, {262,340,355}}},
  {"PLLres",                              {"PLLres", " ", 3, {4}, {26}}},
  {"i2cRxFilterBypass",                   {"i2cRxFilterBypass", "", 1, {1,2,3}, {44,44,44}}},
  {"i2cRxControlOverride",                {"i2cRxControlOverride", "", 1, {0,1,2}, {36,36,36}}},
  {"clockBusFrequencyEc",                 {"clockBusFrequencyEc", "clock frequency EC channel", 1, {4,5,6}, {257,257,257}}},
  {"ePllRxIcp",                           {"ePllRxIcp", "Sets EPLL-RX charge pump current", 4, {0,0,0}, {310,311,312}}},
  {"paEnableGroup6",                      {"paEnableGroup6", "Enable channel 7", 8, {0,0,0}, {225,226,227}}},
  {"paDllResetGroup3",                    {"paDllResetGroup3", "Reset Phase-aligner dll", 1, {4,5,6}, {137,137,137}}},
  {"paDllResetGroup2",                    {"paDllResetGroup2", "Reset Phase-aligner dll", 1, {4,5,6}, {113,113,113}}},
  {"paDllResetGroup1",                    {"paDllResetGroup1", "Reset Phase-aligner dll", 1, {4,5,6}, {89,89,89}}},
  {"paDllResetGroup0",                    {"paDllResetGroup0", "Reset Phase-aligner dll", 1, {4,5,6}, {65,65,65}}},
  {"paDllResetGroup6",                    {"paDllResetGroup6", "Reset Phase-aligner dll", 1, {4,5,6}, {209,209,209}}},
  {"paDllResetGroup5",                    {"paDllResetGroup5", "Reset Phase-aligner dll", 1, {4,5,6}, {185,185,185}}},
  {"paDllResetGroup4",                    {"paDllResetGroup4", "Reset Phase-aligner dll", 1, {4,5,6}, {161,161,161}}},
  {"paDllConfigEC",                       {"paDllConfigEC", "Set EC Phase-aligner dll", 4, {0,4,0}, {231,231,232}}},
  {"rxSelectR",                           {"rxSelectR", " ", 4, {0}, {34}}},
  {"gbld_w1",                             {"gbld_w1", "Value to write to GBLD", 8, {0}, {56}}},
  {"cmEpllRxReferenceSelect",             {"cmEpllRxReferenceSelect", "Selects reference clock C for EPLL-RX", 2, {0,2,4}, {0,0,0}}},
  {"xPllEnableAutoRestart",               {"xPllEnableAutoRestart", "Enable XPLL Auto restart", 1, {3,4,5}, {318,318,318}}},
  {"modeGroup0",                          {"modeGroup0", "mode group0", 2, {0,0,0}, {254,332,347}}},
  {"ePllRxPhase320MHz",                   {"ePllRxPhase320MHz", "Sets EPLL-RX 320MHz phase", 4, {0,4,4}, {302,302,292}}},
  {"gbld_w4",                             {"gbld_w4", "Value to write to GBLD", 8, {0}, {59}}},
  {"rxTestMode",                          {"rxTestMode", "Select RX data source", 1, {5,6,7}, {49,49,49}}},
  {"gbld_w6",                             {"gbld_w6", "Value to write to GBLD", 8, {0}, {61}}},
  {"modeGroup3",                          {"modeGroup3", "mode group3", 2, {0,0,0}, {263,341,356}}},
  {"gbld_w0",                             {"gbld_w0", "Value to write to GBLD", 8, {0}, {55}}},
  {"cmTxReferenceTestMuxSelect",          {"cmTxReferenceTestMuxSelect", "Selects reference clock C for TX in Test mode", 2, {0,2,4}, {3,3,3}}},
  {"gbld_w2",                             {"gbld_w2", "Value to write to GBLD", 8, {0}, {57}}},
  {"gbld_w3",                             {"gbld_w3", "Value to write to GBLD", 8, {0}, {58}}},
  {"clockPortEnableGroup0",               {"clockPortEnableGroup0", "enable clock group0 channel 7", 8, {0,0,0}, {255,333,348}}},
  {"i2cRxSelectI2Phase",                  {"i2cRxSelectI2Phase", " phase detector", 4, {4}, {35}}},
  {"clockPortEnableGroup2",               {"clockPortEnableGroup2", "enable clock group2 channel 7", 8, {0,0,0}, {261,339,354}}},
  {"stateForced",                         {"stateForced", "select state of power-up sequence", 5, {0}, {51}}},
  {"clockPortEnableGroup4",               {"clockPortEnableGroup4", "enable clock group4 channel 7", 8, {0,0,0}, {267,345,360}}},
  {"dataPortEnableGroup3",                {"dataPortEnableGroup3", "enable data group3 channel 7", 8, {0,0,0}, {265,343,358}}},
  {"extS5",                               {"extS5", " ", 2, {5}, {13}}},
  {"extS4",                               {"extS4", " ", 2, {5}, {12}}},
  {"extS7",                               {"extS7", " ", 2, {5}, {15}}},
  {"txTestMode",                          {"txTestMode", "Select TX data source", 2, {0}, {28}}},
  {"txEnableSoftLossOfLock",              {"txEnableSoftLossOfLock", "Enable soft loss of lock", 1, {6}, {33}}},
  {"extS0",                               {"extS0", " ", 2, {5}, {8}}},
  {"extS3",                               {"extS3", " ", 2, {5}, {11}}},
  {"extS2",                               {"extS2", " ", 2, {5}, {10}}},
  {"bypssEportTX2",                       {"bypssEportTX2", "bypass Eport TX group2", 1, {6,7,0}, {246,246,247}}},
  {"dllCoarseLockDetection",              {"dllCoarseLockDetection", "dll coarse lock detection", 1, {4,5,6}, {233,233,233}}},
  {"bypssEportTX1",                       {"bypssEportTX1", "bypass Eport TX group1", 1, {3,4,5}, {246,246,246}}},
  {"dataPortEnableGroup1",                {"dataPortEnableGroup1", "enable data group1 channel 7", 8, {0,0,0}, {259,337,352}}},
  {"bypssEportTX4",                       {"bypssEportTX4", "bypass Eport TX group4", 1, {4,5,6}, {247,247,247}}},
  {"iSel4",                               {"iSel4", " ", 4, {0}, {20}}},
  {"iSel5",                               {"iSel5", " ", 4, {0}, {21}}},
  {"iSel6",                               {"iSel6", " ", 4, {0}, {22}}},
  {"iSel7",                               {"iSel7", " ", 4, {0}, {23}}},
  {"iSel0",                               {"iSel0", " ", 4, {0}, {16}}},
  {"iSel1",                               {"iSel1", " ", 4, {0}, {17}}},
  {"iSel2",                               {"iSel2", " ", 4, {0}, {18}}},
  {"iSel3",                               {"iSel3", " ", 4, {0}, {19}}},
  {"cmRxPhase80MHz",                      {"cmRxPhase80MHz", "Fine phase delay of RX 80MHz clock", 4, {4,0,4}, {275,276,276}}},
  {"loopbackF",                           {"loopbackF", "enable loopbackF", 1, {3,4,5}, {234,234,234}}},
  {"clkDriveStrength4",                   {"clkDriveStrength4", "set clock drive strength group 4", 4, {4}, {331}}},
  {"i2cRxDac2",                           {"i2cRxDac2", " ", 1, {0}, {44}}},
  {"i2cRxDac1",                           {"i2cRxDac1", " ", 8, {0}, {43}}},
  {"scCset",                              {"scCset", "Drive current control for SC-EC Eport", 4, {0}, {273}}},
  {"FDL6",                                {"FDL6", " ", 4, {0}, {7}}},
  {"FDL7",                                {"FDL7", " ", 4, {4}, {7}}},
  {"FDL4",                                {"FDL4", " ", 4, {0}, {6}}},
  {"FDL5",                                {"FDL5", " ", 4, {4}, {6}}},
  {"FDL2",                                {"FDL2", " ", 4, {0}, {5}}},
  {"FDL3",                                {"FDL3", " ", 4, {4}, {5}}},
  {"FDL0",                                {"FDL0", " ", 4, {0}, {4}}},
  {"FDL1",                                {"FDL1", " ", 4, {4}, {4}}},
  {"i2cRxForceVfEqVc",                    {"i2cRxForceVfEqVc", "", 1, {3,4,5}, {45,45,45}}},
  {"enableTestBar",                       {"enableTestBar", " ", 1, {1}, {25}}},
  {"CDL5",                                {"CDL5", " ", 5, {0}, {13}}},
  {"CDL4",                                {"CDL4", " ", 5, {0}, {12}}},
  {"CDL7",                                {"CDL7", " ", 5, {0}, {15}}},
  {"CDL6",                                {"CDL6", " ", 5, {0}, {14}}},
  {"CDL1",                                {"CDL1", " ", 5, {0}, {9}}},
  {"CDL0",                                {"CDL0", " ", 5, {0}, {8}}},
  {"CDL3",                                {"CDL3", " ", 5, {0}, {11}}},
  {"CDL2",                                {"CDL2", " ", 5, {0}, {10}}},
  {"resetBar1",                           {"resetBar1", "Channel 1 reset", 1, {1}, {24}}},
  {"resetBar0",                           {"resetBar0", "Channel 0 reset", 1, {0}, {24}}},
  {"resetBar3",                           {"resetBar3", "Channel 3 reset", 1, {3}, {24}}},
  {"resetBar2",                           {"resetBar2", "Channel 2 reset", 1, {2}, {24}}},
  {"resetBar5",                           {"resetBar5", "Channel 5 reset", 1, {5}, {24}}},
  {"resetBar4",                           {"resetBar4", "Channel 4 reset", 1, {4}, {24}}},
  {"resetBar7",                           {"resetBar7", "Channel 7 reset", 1, {7}, {24}}},
  {"resetBar6",                           {"resetBar6", "Channel 6 reset", 1, {6}, {24}}},
  {"gbld_w5",                             {"gbld_w5", "Value to write to GBLD", 8, {0}, {60}}},
  {"dataPortEnableGroup0",                {"dataPortEnableGroup0", "enable data group0 channel 7", 8, {0,0,0}, {256,334,349}}},
  {"rxSwitchesControl",                   {"rxSwitchesControl", "Select data path through RX logic", 6, {0,0,0}, {46,47,48}}},
  {"fuseBlowAddress2",                    {"fuseBlowAddress2", "address of fuse to blow", 8, {0}, {239}}},
  {"fuseBlowAddress1",                    {"fuseBlowAddress1", "address of fuse to blow", 8, {0}, {238}}},
  {"configDone",                          {"configDone", "re-starts power-up sequence if set to AA hex", 8, {0}, {365}}},
  {"i2cRxControlReset",                   {"i2cRxControlReset", "FASM and LCSM reset", 1, {0,1,2}, {41,41,41}}},
  {"modeGroup4",                          {"modeGroup4", "mode group4", 2, {0,0,0}, {266,344,359}}},
  {"ePllTxPhase320MHz",                   {"ePllTxPhase320MHz", "Sets EPLL-TX 320MHz phase", 4, {0,4,0}, {291,291,292}}},
  {"xPllFrequencyTrim",                   {"xPllFrequencyTrim", "Sets XPLL frequency trim", 7, {0,0,0}, {313,314,315}}},
  {"clockBusFrequency3",                  {"clockBusFrequency3", "clock frequency group3", 2, {2,2,2}, {263,341,356}}},
  {"xPllEnable",                          {"xPllEnable", "Enables XPLL", 1, {7,7,7}, {313,314,315}}},
  {"i2cRxSelectI1",                       {"i2cRxSelectI1", " ", 4, {4}, {41}}},
  {"paDllResetEC",                        {"paDllResetEC", "Reset EC Phase-aligner dll", 1, {4,5,6}, {232,232,232}}},
  {"enableTermination6",                  {"enableTermination6", "enable Termination group6 channel 7", 8, {0}, {326}}},
  {"cmTestOutSelect",                     {"cmTestOutSelect", "Selects which signal to send to testClockOut from first subset", 7, {0}, {283}}},
  {"rxMinValidHeaders",                   {"rxMinValidHeaders", " ", 8, {0}, {39}}},
  {"timeOutEnable",                       {"timeOutEnable", "enable timeOuts", 1, {3,4,5}, {52,52,52}}},
  {"bypssEportTX3",                       {"bypssEportTX3", "bypass Eport TX group3", 1, {1,2,3}, {247,247,247}}},
  {"cmTestMuxSelect",                     {"cmTestMuxSelect", "Selects which signal to send to testClockOut from second subset", 5, {0}, {319}}},
  {"cmEpllTxReferenceSelect",             {"cmEpllTxReferenceSelect", "Selects reference clock C for EPLL-TX", 2, {0,2,4}, {1,1,1}}},
  {"txPLLLockTime",                       {"txPLLLockTime", "Set wait time for serialiser PLL to lock", 4, {0}, {32}}},
  {"modeGroup1",                          {"modeGroup1", "mode group1", 2, {0,0,0}, {257,335,350}}},
  {"cmTxPhase80MHz",                      {"cmTxPhase80MHz", "Fine phase delay of TX 80MHz clock", 4, {4,0,4}, {285,286,286}}},
  {"clockPortEnableGroup1",               {"clockPortEnableGroup1", "enable clock group1 channel 7", 8, {0,0,0}, {258,336,351}}},
  {"selHiByteTX1",                        {"selHiByteTX1", "select HiByte in bypassed Eport TX group1", 1, {3,4,5}, {249,249,249}}},
  {"loopbackE",                           {"loopbackE", "enable loopbackE", 1, {0,1,2}, {234,234,234}}},
  {"enableBERT",                          {"enableBERT", "Enable BERT in RX logic", 1, {2,3,4}, {49,49,49}}},
  {"clockPortEnableGroup3",               {"clockPortEnableGroup3", "enable clock group3 channel 7", 8, {0,0,0}, {264,342,357}}},
  {"i2cRxDacEnable",                      {"i2cRxDacEnable", "", 1, {3,4,5}, {42,42,42}}},
  {"cset0",                               {"cset0", " ", 4, {0}, {269}}},
  {"clkDriveStrength0",                   {"clkDriveStrength0", "set clock drive strength group 0", 4, {4}, {329}}},
  {"rxDisableDecoderTMR",                 {"rxDisableDecoderTMR", "Disable TMR in FEC decoder", 1, {1}, {49}}},
  {"driveStrength3",                      {"driveStrength3", "set drive strength group 3", 4, {4}, {328}}},
  {"paMode",                              {"paMode", "Phase-aligner track mode", 2, {0,2,4}, {62,62,62}}},
  {"cmPsReferenceSelect",                 {"cmPsReferenceSelect", "Selects Phase-Shifter reference clock", 2, {0,2,4}, {282,282,282}}},
  {"selHiByteTX0",                        {"selHiByteTX0", "select HiByte in bypassed Eport TX group0", 1, {0,1,2}, {249,249,249}}},
  {"clkDriveStrength2",                   {"clkDriveStrength2", "set clock drive strength group 2", 4, {4}, {330}}},
  {"clkDriveStrength3",                   {"clkDriveStrength3", "set clock drive strength group 3", 4, {0}, {331}}},
  {"cmRxReferenceTestMuxSelect",          {"cmRxReferenceTestMuxSelect", "Selects reference clock C for RX in Test mode", 2, {0,2,4}, {2,2,2}}},
  {"cmTxTestMuxSelect160",                {"cmTxTestMuxSelect160", "Selects TX 160MHz clock C in Test mode", 2, {4,4,4}, {287,288,289}}},
  {"ePllRxReset",                         {"ePllRxReset", "Reset of EPLL-RX filter", 1, {4,5,6}, {303,303,303}}},
  {"FREQ7",                               {"FREQ7", " ", 2, {4}, {23}}},
  {"FREQ6",                               {"FREQ6", " ", 2, {4}, {22}}},
  {"FREQ5",                               {"FREQ5", " ", 2, {4}, {21}}},
  {"FREQ4",                               {"FREQ4", " ", 2, {4}, {20}}},
  {"FREQ3",                               {"FREQ3", " ", 2, {4}, {19}}},
  {"FREQ2",                               {"FREQ2", " ", 2, {4}, {18}}},
  {"FREQ1",                               {"FREQ1", " ", 2, {4}, {17}}},
  {"FREQ0",                               {"FREQ0", " ", 2, {4}, {16}}},
  {"RXselectPosEdge",                     {"RXselectPosEdge", "select +ve clock edge in RX synchroniser", 1, {0,1,2}, {244,244,244}}},
  {"extS6",                               {"extS6", " ", 2, {5}, {14}}},
  {"ePllTxCap",                           {"ePllTxCap", "Sets EPLL-TX Cap C in filter", 2, {5,5,5}, {296,297,298}}},
  {"i2cldReset",                          {"i2cldReset", "Controls state of ldReset pin", 1, {3,4,5}, {54,54,54}}},
  {"extS1",                               {"extS1", " ", 2, {5}, {9}}},
  {"selHiByteTX3",                        {"selHiByteTX3", "select HiByte in bypassed Eport TX group3", 1, {1,2,3}, {250,250,250}}},
  {"ePllTxRes",                           {"ePllTxRes", "Sets EPLL-TX Res C in filter", 4, {4,4,4}, {299,300,301}}},
  {"ePllRxRes",                           {"ePllRxRes", "Sets EPLL-RX Res C in filter", 4, {4,4,4}, {310,311,312}}},
  {"dataPortEnableGroup4",                {"dataPortEnableGroup4", "enable data group4 channel 7", 8, {0,0,0}, {268,346,361}}},
  {"cmTxTestMuxSelect320",                {"cmTxTestMuxSelect320", "Selects TX 320MHz clock C in Test mode", 2, {6,6,6}, {287,288,289}}},
  {"ePllRxPhase160MHz",                   {"ePllRxPhase160MHz", "Sets EPLL-RX 160MHz phase", 5, {0,0,0}, {307,308,309}}},
  {"cmRxTestMuxSelect320",                {"cmRxTestMuxSelect320", "Selects RX 320MHz clock C in Test mode", 2, {6,6,6}, {277,278,279}}},
  {"rxDacGain",                           {"rxDacGain", "", 1, {4,5,6}, {34,34,34}}},
  {"resetPLLBar",                         {"resetPLLBar", "PLL reset", 1, {0}, {25}}},
  {"SLVSoutTestSel",                      {"SLVSoutTestSel", "Selects signal to drive SLVS output test (dOut32)", 2, {6}, {0}}},
  {"txSelectI",                           {"txSelectI", " ", 4, {0}, {27}}},
  {"txSelectR",                           {"txSelectR", " ", 2, {4}, {27}}},
  {"txEnableTest",                        {"txEnableTest", " ", 1, {6}, {27}}},
  {"extEarly3",                           {"extEarly3", " ", 1, {7}, {11}}},
  {"extEarly2",                           {"extEarly2", " ", 1, {7}, {10}}},
  {"extEarly1",                           {"extEarly1", " ", 1, {7}, {9}}},
  {"extEarly0",                           {"extEarly0", " ", 1, {7}, {8}}},
  {"extEarly7",                           {"extEarly7", " ", 1, {7}, {15}}},
  {"extEarly6",                           {"extEarly6", " ", 1, {7}, {14}}},
  {"extEarly5",                           {"extEarly5", " ", 1, {7}, {13}}},
  {"extEarly4",                           {"extEarly4", " ", 1, {7}, {12}}},
  {"selHiByteTX2",                        {"selHiByteTX2", "select HiByte in bypassed Eport TX group2", 1, {6,7,0}, {249,249,250}}},
  {"bypssEportTX0",                       {"bypssEportTX0", "bypass Eport TX group0", 1, {0,1,2}, {246,246,246}}},
  {"clockBusFrequency0",                  {"clockBusFrequency0", "clock frequency group0", 2, {2,2,2}, {254,332,347}}},
  {"selHiByteTX4",                        {"selHiByteTX4", "select HiByte in bypassed Eport TX group4", 1, {4,5,6}, {250,250,250}}},
  {"driveStrength4",                      {"driveStrength4", "set drive strength group 4", 4, {0}, {329}}},
  {"rxValidHeaders",                      {"rxValidHeaders", " ", 8, {0}, {37}}},
  {"driveStrength2",                      {"driveStrength2", "set drive strength group 2", 4, {0}, {328}}},
  {"driveStrength1",                      {"driveStrength1", "set drive strength group 1", 4, {4}, {327}}},
  {"driveStrength0",                      {"driveStrength0", "set drive strength group 0", 4, {0}, {327}}},
  {"txSwitchesControl",                   {"txSwitchesControl", "Select data path through TX logic", 6, {0,0,0}, {29,30,31}}},
  {"testOutputSelect",                    {"testOutputSelect", "Selects the signal to drive testOutput", 8, {0}, {280}}},
  {"txForceLockState",                    {"txForceLockState", "Force serialiser control to locked state", 1, {4}, {32}}},
  {"txLossOfLockTime",                    {"txLossOfLockTime", "Set time limit on unlock", 3, {5}, {32}}},
  {"scEnableTermination",                 {"scEnableTermination", "Enable termination for SC-EC Eport", 1, {5}, {273}}},
  {"txDisableEncoderTMR",                 {"txDisableEncoderTMR", "Disable TMR in FEC encoder", 1, {6}, {28}}},
  {"bypassEportRX",                       {"bypassEportRX", "bypass EportRX", 1, {0,1,2}, {252,252,252}}},
  {"gbld_ID",                             {"gbld_ID", "i2c address of GBLD", 7, {0}, {253}}},
  {"i2cRxReset",                          {"i2cRxReset", "(Conditional) reset of the CDR PLL", 2, {0,2,4}, {53,53,53}}},
  {"configFuseData",                      {"configFuseData", "config fuse value", 8, {0}, {366}}},
  {"testFuseData1",                       {"testFuseData1", "test fuse 1 value", 8, {0}, {367}}},
  {"testFuseData2",                       {"testFuseData2", "test fuse 2 value", 8, {0}, {368}}},
  {"BERTCounter",                         {"BERTCounter", "BERT counter value in RC logic", 16, {0}, {369}}},
  {"scStatusAParity",                     {"scStatusAParity", "result of parity check of previous SC-IC write", 1, {0}, {371}}},
  {"scStatusAState",                      {"scStatusAState", "State of SC-IC state machine A", 6, {1}, {371}}},
  {"scStatusAGbldAccess",                 {"scStatusAGbldAccess", "high if GBLD access is not running", 1, {7}, {371}}},
  {"scStatusBParity",                     {"scStatusBParity", "result of parity check of previous SC-IC write", 1, {0}, {372}}},
  {"scStatusBState",                      {"scStatusBState", "State of SC-IC state machine A", 6, {1}, {372}}},
  {"scStatusBGbldAccess",                 {"scStatusBGbldAccess", "high if GBLD access is not running", 1, {7}, {372}}},
  {"scStatusCParity",                     {"scStatusCParity", "result of parity check of previous SC-IC write", 1, {0}, {373}}},
  {"scStatusCState",                      {"scStatusCState", "State of SC-IC state machine A", 6, {1}, {373}}},
  {"scStatusCGbldAccess",                 {"scStatusCGbldAccess", "high if GBLD access is not running", 1, {7}, {373}}},
  {"configRegErrorCount",                 {"configRegErrorCount", "count of SEU corrections in registers", 8, {0}, {375}}},
  {"txStatusClockLoss",                   {"txStatusClockLoss", "TX status: Loss of clock count", 8, {0}, {376}}},
  {"txStatusReady",                       {"txStatusReady", "TX status: txRdy", 1, {0}, {377}}},
  {"rxStatusVco",                         {"rxStatusVco", "RX status: vcoFast status", 1, {1}, {377}}},
  {"txStatusControlA",                    {"txStatusControlA", "TX status: txControl state A", 2, {2}, {377}}},
  {"txStatusControlB",                    {"txStatusControlB", "TX status: txControl state B", 2, {4}, {377}}},
  {"txStatusControlC",                    {"txStatusControlC", "TX status: txControl state C", 2, {6}, {377}}},
  {"rxStatusControlA",                    {"rxStatusControlA", "RX status: txControl state A", 4, {0}, {378}}},
  {"rxStatusControlRxSkipCycleA",         {"rxStatusControlRxSkipCycleA", "RX status: rxSkipCycle A", 1, {4}, {378}}},
  {"rxStatusControlRxSelectDataInPhaseA", {"rxStatusControlRxSelectDataInPhaseA", "RX status: rxSelectDataInPhase A", 1, {5}, {378}}},
  {"rxStatusControlRxSwapA",              {"rxStatusControlRxSwapA", "RX status: rxSwap A", 1, {6}, {378}}},
  {"rxStatusControlRxReadyA",             {"rxStatusControlRxReadyA", "RX status: rxReady A", 5, {7}, {378}}},
  {"rxStatusControlB",                    {"rxStatusControlB", "RX status: txControl state B", 0, {4}, {379}}},
  {"rxStatusControlRxSkipCycleB",         {"rxStatusControlRxSkipCycleB", "RX status: rxSkipCycle B", 1, {4}, {379}}},
  {"rxStatusControlRxSelectDataInPhaseB", {"rxStatusControlRxSelectDataInPhaseB", "RX status: rxSelectDataInPhase B", 1, {5}, {379}}},
  {"rxStatusControlRxSwapB",              {"rxStatusControlRxSwapB", "RX status: rxSwap B", 1, {6}, {379}}},
  {"rxStatusControlRxReadyB",             {"rxStatusControlRxReadyB", "RX status: rxReady B", 5, {7}, {379}}},
  {"rxStatusControlC",                    {"rxStatusControlC", "RX status: txControl state C", 0, {6}, {377}}},
  {"rxStatusControlRxSkipCycleC",         {"rxStatusControlRxSkipCycleC", "RX status: rxSkipCycle C", 1, {4}, {380}}},
  {"rxStatusControlRxSelectDataInPhaseC", {"rxStatusControlRxSelectDataInPhaseC", "RX status: rxSelectDataInPhase C", 1, {5}, {380}}},
  {"rxStatusControlRxSwapC",              {"rxStatusControlRxSwapC", "RX status: rxSwap C", 1, {6}, {380}}},
  {"rxStatusControlRxReadyC",             {"rxStatusControlRxReadyC", "RX status: rxReady C", 1, {7}, {380}}},
  {"gbldReadData0",                       {"gbldReadData0", "GBLD read data register 0", 8, {0}, {381}}},
  {"gbldReadData1",                       {"gbldReadData1", "GBLD read data register 1", 8, {0}, {382}}},
  {"gbldReadData2",                       {"gbldReadData2", "GBLD read data register 2", 8, {0}, {383}}},
  {"gbldReadData3",                       {"gbldReadData3", "GBLD read data register 3", 8, {0}, {384}}},
  {"gbldReadData4",                       {"gbldReadData4", "GBLD read data register 4", 8, {0}, {385}}},
  {"gbldReadData5",                       {"gbldReadData5", "GBLD read data register 5", 8, {0}, {386}}},
  {"gbldReadData6",                       {"gbldReadData6", "GBLD read data register 6", 8, {0}, {387}}},
  {"gbldWrite",                           {"gbldWrite", "address this register to launch GBLD write", 8, {0}, {388}}},
  {"gbldRead",                            {"gbldRead", "address this register to launch GBLD read", 8, {0}, {389}}},
  {"dllLockedGroup0",                     {"dllLockedGroup0", "EportRX dll locked status, group 0", 1, {0}, {390}}},
  {"dllLockedGroup1",                     {"dllLockedGroup1", "EportRX dll locked status, group 1", 1, {1}, {390}}},
  {"dllLockedGroup2",                     {"dllLockedGroup2", "EportRX dll locked status, group 2", 1, {2}, {390}}},
  {"dllLockedGroup3",                     {"dllLockedGroup3", "EportRX dll locked status, group 3", 1, {3}, {390}}},
  {"dllLockedGroup4",                     {"dllLockedGroup4", "EportRX dll locked status, group 4", 1, {4}, {390}}},
  {"dllLockedGroup5",                     {"dllLockedGroup5", "EportRX dll locked status, group 5", 1, {5}, {390}}},
  {"dllLockedGroup6",                     {"dllLockedGroup6", "EportRX dll locked status, group 6", 1, {6}, {390}}},
  {"dllLockedEc",                         {"dllLockedEc", "EportRX dll locked status, EC channel", 1, {7}, {390}}},
  {"channelLockedGroup0",                 {"channelLockedGroup0", "EportRX phase aligner locked status, group 0", 9, {0}, {391}}},
  {"channelLockedGroup1",                 {"channelLockedGroup1", "EportRX phase aligner locked status, group 1", 9, {1}, {392}}},
  {"channelLockedGroup2",                 {"channelLockedGroup2", "EportRX phase aligner locked status, group 2", 9, {2}, {393}}},
  {"channelLockedGroup3",                 {"channelLockedGroup3", "EportRX phase aligner locked status, group 3", 9, {3}, {394}}},
  {"channelLockedGroup4",                 {"channelLockedGroup4", "EportRX phase aligner locked status, group 4", 9, {4}, {395}}},
  {"channelLockedGroup5",                 {"channelLockedGroup5", "EportRX phase aligner locked status, group 5", 9, {5}, {396}}},
  {"channelLockedGroup6",                 {"channelLockedGroup6", "EportRX phase aligner locked status, group 6", 2, {6}, {397}}},
  {"phaseSelectOutEc",                    {"phaseSelectOutEc", "EportRX selected phase EC channel", 4, {0}, {398}}},
  {"channelLockedGroupEc",                {"channelLockedGroupEc", "EportRX phase aligner locked status, EC channel", 1, {4}, {398}}},
  {"phaseSelectOutGroup0Channel0",        {"phaseSelectOutGroup0Channel0", "EportRX selected phase, group 0, channel 0", 4, {0}, {399}}},
  {"phaseSelectOutGroup0Channel1",        {"phaseSelectOutGroup0Channel1", "EportRX selected phase, group 0, channel 1", 4, {4}, {399}}},
  {"phaseSelectOutGroup0Channel2",        {"phaseSelectOutGroup0Channel2", "EportRX selected phase, group 0, channel 2", 4, {0}, {400}}},
  {"phaseSelectOutGroup0Channel3",        {"phaseSelectOutGroup0Channel3", "EportRX selected phase, group 0, channel 3", 4, {4}, {400}}},
  {"phaseSelectOutGroup0Channel4",        {"phaseSelectOutGroup0Channel4", "EportRX selected phase, group 0, channel 4", 4, {0}, {401}}},
  {"phaseSelectOutGroup0Channel5",        {"phaseSelectOutGroup0Channel5", "EportRX selected phase, group 0, channel 5", 4, {4}, {401}}},
  {"phaseSelectOutGroup0Channel6",        {"phaseSelectOutGroup0Channel6", "EportRX selected phase, group 0, channel 6", 4, {0}, {402}}},
  {"phaseSelectOutGroup0Channel7",        {"phaseSelectOutGroup0Channel7", "EportRX selected phase, group 0, channel 7", 4, {4}, {402}}},
  {"phaseSelectOutGroup1Channel0",        {"phaseSelectOutGroup1Channel0", "EportRX selected phase, group 1, channel 0", 4, {0}, {403}}},
  {"phaseSelectOutGroup1Channel1",        {"phaseSelectOutGroup1Channel1", "EportRX selected phase, group 1, channel 1", 4, {4}, {403}}},
  {"phaseSelectOutGroup1Channel2",        {"phaseSelectOutGroup1Channel2", "EportRX selected phase, group 1, channel 2", 4, {0}, {404}}},
  {"phaseSelectOutGroup1Channel3",        {"phaseSelectOutGroup1Channel3", "EportRX selected phase, group 1, channel 3", 4, {4}, {404}}},
  {"phaseSelectOutGroup1Channel4",        {"phaseSelectOutGroup1Channel4", "EportRX selected phase, group 1, channel 4", 4, {0}, {405}}},
  {"phaseSelectOutGroup1Channel5",        {"phaseSelectOutGroup1Channel5", "EportRX selected phase, group 1, channel 5", 4, {4}, {405}}},
  {"phaseSelectOutGroup1Channel6",        {"phaseSelectOutGroup1Channel6", "EportRX selected phase, group 1, channel 6", 4, {0}, {406}}},
  {"phaseSelectOutGroup1Channel7",        {"phaseSelectOutGroup1Channel7", "EportRX selected phase, group 1, channel 7", 4, {4}, {406}}},
  {"phaseSelectOutGroup2Channel0",        {"phaseSelectOutGroup2Channel0", "EportRX selected phase, group 2, channel 0", 4, {0}, {407}}},
  {"phaseSelectOutGroup2Channel1",        {"phaseSelectOutGroup2Channel1", "EportRX selected phase, group 2, channel 1", 4, {4}, {407}}},
  {"phaseSelectOutGroup2Channel2",        {"phaseSelectOutGroup2Channel2", "EportRX selected phase, group 2, channel 2", 4, {0}, {408}}},
  {"phaseSelectOutGroup2Channel3",        {"phaseSelectOutGroup2Channel3", "EportRX selected phase, group 2, channel 3", 4, {4}, {408}}},
  {"phaseSelectOutGroup2Channel4",        {"phaseSelectOutGroup2Channel4", "EportRX selected phase, group 2, channel 4", 4, {0}, {409}}},
  {"phaseSelectOutGroup2Channel5",        {"phaseSelectOutGroup2Channel5", "EportRX selected phase, group 2, channel 5", 4, {4}, {409}}},
  {"phaseSelectOutGroup2Channel6",        {"phaseSelectOutGroup2Channel6", "EportRX selected phase, group 2, channel 6", 4, {0}, {410}}},
  {"phaseSelectOutGroup2Channel7",        {"phaseSelectOutGroup2Channel7", "EportRX selected phase, group 2, channel 7", 4, {4}, {410}}},
  {"phaseSelectOutGroup3Channel0",        {"phaseSelectOutGroup3Channel0", "EportRX selected phase, group 3, channel 0", 4, {0}, {411}}},
  {"phaseSelectOutGroup3Channel1",        {"phaseSelectOutGroup3Channel1", "EportRX selected phase, group 3, channel 1", 4, {4}, {411}}},
  {"phaseSelectOutGroup3Channel2",        {"phaseSelectOutGroup3Channel2", "EportRX selected phase, group 3, channel 2", 4, {0}, {412}}},
  {"phaseSelectOutGroup3Channel3",        {"phaseSelectOutGroup3Channel3", "EportRX selected phase, group 3, channel 3", 4, {4}, {412}}},
  {"phaseSelectOutGroup3Channel4",        {"phaseSelectOutGroup3Channel4", "EportRX selected phase, group 3, channel 4", 4, {0}, {413}}},
  {"phaseSelectOutGroup3Channel5",        {"phaseSelectOutGroup3Channel5", "EportRX selected phase, group 3, channel 5", 4, {4}, {413}}},
  {"phaseSelectOutGroup3Channel6",        {"phaseSelectOutGroup3Channel6", "EportRX selected phase, group 3, channel 6", 4, {0}, {414}}},
  {"phaseSelectOutGroup3Channel7",        {"phaseSelectOutGroup3Channel7", "EportRX selected phase, group 3, channel 7", 4, {4}, {414}}},
  {"phaseSelectOutGroup4Channel0",        {"phaseSelectOutGroup4Channel0", "EportRX selected phase, group 4, channel 0", 4, {0}, {415}}},
  {"phaseSelectOutGroup4Channel1",        {"phaseSelectOutGroup4Channel1", "EportRX selected phase, group 4, channel 1", 4, {4}, {415}}},
  {"phaseSelectOutGroup4Channel2",        {"phaseSelectOutGroup4Channel2", "EportRX selected phase, group 4, channel 2", 4, {0}, {416}}},
  {"phaseSelectOutGroup4Channel3",        {"phaseSelectOutGroup4Channel3", "EportRX selected phase, group 4, channel 3", 4, {4}, {416}}},
  {"phaseSelectOutGroup4Channel4",        {"phaseSelectOutGroup4Channel4", "EportRX selected phase, group 4, channel 4", 4, {0}, {417}}},
  {"phaseSelectOutGroup4Channel5",        {"phaseSelectOutGroup4Channel5", "EportRX selected phase, group 4, channel 5", 4, {4}, {417}}},
  {"phaseSelectOutGroup4Channel6",        {"phaseSelectOutGroup4Channel6", "EportRX selected phase, group 4, channel 6", 4, {0}, {418}}},
  {"phaseSelectOutGroup4Channel7",        {"phaseSelectOutGroup4Channel7", "EportRX selected phase, group 4, channel 7", 4, {4}, {418}}},
  {"phaseSelectOutGroup5Channel0",        {"phaseSelectOutGroup5Channel0", "EportRX selected phase, group 5, channel 0", 4, {0}, {419}}},
  {"phaseSelectOutGroup5Channel1",        {"phaseSelectOutGroup5Channel1", "EportRX selected phase, group 5, channel 1", 4, {4}, {419}}},
  {"phaseSelectOutGroup5Channel2",        {"phaseSelectOutGroup5Channel2", "EportRX selected phase, group 5, channel 2", 4, {0}, {420}}},
  {"phaseSelectOutGroup5Channel3",        {"phaseSelectOutGroup5Channel3", "EportRX selected phase, group 5, channel 3", 4, {4}, {420}}},
  {"phaseSelectOutGroup5Channel4",        {"phaseSelectOutGroup5Channel4", "EportRX selected phase, group 5, channel 4", 4, {0}, {421}}},
  {"phaseSelectOutGroup5Channel5",        {"phaseSelectOutGroup5Channel5", "EportRX selected phase, group 5, channel 5", 4, {4}, {421}}},
  {"phaseSelectOutGroup5Channel6",        {"phaseSelectOutGroup5Channel6", "EportRX selected phase, group 5, channel 6", 4, {0}, {422}}},
  {"phaseSelectOutGroup5Channel7",        {"phaseSelectOutGroup5Channel7", "EportRX selected phase, group 5, channel 7", 4, {4}, {422}}},
  {"phaseSelectOutGroup6Channel0",        {"phaseSelectOutGroup6Channel0", "EportRX selected phase, group 6, channel 0", 4, {0}, {423}}},
  {"phaseSelectOutGroup6Channel1",        {"phaseSelectOutGroup6Channel1", "EportRX selected phase, group 6, channel 1", 4, {4}, {423}}},
  {"phaseSelectOutGroup6Channel2",        {"phaseSelectOutGroup6Channel2", "EportRX selected phase, group 6, channel 2", 4, {0}, {424}}},
  {"phaseSelectOutGroup6Channel3",        {"phaseSelectOutGroup6Channel3", "EportRX selected phase, group 6, channel 3", 4, {4}, {424}}},
  {"phaseSelectOutGroup6Channel4",        {"phaseSelectOutGroup6Channel4", "EportRX selected phase, group 6, channel 4", 4, {0}, {425}}},
  {"phaseSelectOutGroup6Channel5",        {"phaseSelectOutGroup6Channel5", "EportRX selected phase, group 6, channel 5", 4, {4}, {425}}},
  {"phaseSelectOutGroup6Channel6",        {"phaseSelectOutGroup6Channel6", "EportRX selected phase, group 6, channel 6", 4, {0}, {426}}},
  {"phaseSelectOutGroup6Channel7",        {"phaseSelectOutGroup6Channel7", "EportRX selected phase, group 6, channel 7", 4, {4}, {426}}},
  {"TXEPLLLocked",                        {"TXEPLLLocked", "EPLL-TX locked status", 1, {0}, {427}}},
  {"txRdy_control",                       {"txRdy_control", "txControl txRdy", 1, {1}, {427}}},
  {"RXEPLLLocked",                        {"RXEPLLLocked", "EPLL-RX locked status", 1, {2}, {427}}},
  {"rxRdy_control",                       {"rxRdy_control", "rxControl rxRdy", 1, {3}, {427}}},
  {"XPLLLocked",                          {"XPLLLocked", "XPLL locked status", 1, {4}, {427}}},
  {"ttcDivideOut",                        {"ttcDivideOut", "phase shifter DivideOut", 1, {0}, {428}}},
  {"ttcTestDown",                         {"ttcTestDown", "phase shifter TestDown", 1, {1}, {428}}},
  {"ttcTestUp",                           {"ttcTestUp", "phase shifter TestUp", 1, {2}, {428}}},
  {"txTestUp",                            {"txTestUp", "Serialiser TestUp", 1, {3}, {428}}},
  {"txTestDown",                          {"txTestDown", "Serialiser TestDown", 1, {4}, {428}}},
  {"ePLLRXInstantLock",                   {"ePLLRXInstantLock", "EPLL-RX instant lock status", 1, {5}, {428}}},
  {"ePLLTXInstantLock",                   {"ePLLTXInstantLock", "EPLL-TX instant lock status", 1, {6}, {428}}},
  {"xPllInstantLock",                     {"xPllInstantLock", "XPLL instant lock status", 1, {7}, {428}}},
  {"ttcEarly",                            {"ttcEarly", "phase shifter Early", 8, {0}, {429}}},
  {"ttcLate",                             {"ttcLate", "phase shifter Late", 8, {0}, {430}}},
  {"txInstantLockgated",                  {"txInstantLockgated", "Serialiser instant lock status", 1, {0}, {431}}},
  {"rxInstantLockRefGated",               {"rxInstantLockRefGated", "Deserialiser instant lock status", 1, {1}, {431}}},
  {"powerUpFSMState",                     {"powerUpFSMState", "state of powerUp FSM", 5, {2}, {431}}},
  {"rxRefPllLossOfLockCount",             {"rxRefPllLossOfLockCount", "RF PLL loss of lock count", 8, {0}, {432}}},
  {"EPLLTXlossOfLockCount",               {"EPLLTXlossOfLockCount", "EPLL-TX loss of lock count", 8, {0}, {433}}},
  {"EPLLRXlossOfLockCount",               {"EPLLRXlossOfLockCount", "EPLL-RX loss of lock count", 8, {0}, {434}}},
  {"FECcorrectionCount",                  {"FECcorrectionCount", "Count of FEC corrections in RX", 8, {0}, {435}}},
  // clang-format on
};

#endif  // NSWCONFIGURATION_GBTXREGISTERMAP_H
