// NSW SCAx Registers
// this file should be generated by NSWRegisters by Ifat

#ifndef NSWCONFIGURATION_SCAXREGISTERS_H_
#define NSWCONFIGURATION_SCAXREGISTERS_H_

#include <cstddef>
#include <cstdint>
#include <vector>
#include <string>
#include <array>
#include <utility> // for std::pair
#include <chrono>
#include <map>
#include <cmath>

// FIXME OBSOLETE! NEED TO DELETEE

namespace nsw {

  namespace mmtp {
    // json name; bus; addr; default; R/W status
    constexpr auto REGS = std::to_array({
      std::make_tuple("ADDC_EMU_DISABLE", 0, 0x01, 0x01, "RW"),
      std::make_tuple("FIBER_ALIGNMENT",  0, 0x02, 0x00, "R"),
      std::make_tuple("REG_L1A_CONTROL",  0, 0x10, 0x00, "RW"),
      std::make_tuple("L1AOpeningOffset", 0, 0x11, 0x01, "RW"),
      std::make_tuple("L1ARequestOffset", 0, 0x12, 0x01, "RW"),
      std::make_tuple("L1AClosingOffset", 0, 0x13, 0x01, "RW"),
      std::make_tuple("L1ATimeoutWindow", 0, 0x14, 0x01, "RW"),
      std::make_tuple("FiberBCOffset", 0, 0x08, 0x01, "RW"),
      std::make_tuple("GlobalInputPhase",   0, 0x0b, 0x01, "RW"),
      std::make_tuple("GlobalInputOffset",  0, 0x0c, 0x01, "RW"),
      std::make_tuple("gbtL1ddPhaseOffset", 0, 0x32, 0x01, "RW"),
      std::make_tuple("SelfTriggerDelay", 0, 0x21, 0x00, "RW"),
      std::make_tuple("VmmMaskHotThresh", 0, 0x22, 0x0A, "RW"),
      std::make_tuple("VmmMaskHotThreshHyst", 0, 0x23, 0x03, "RW"),
      std::make_tuple("VmmMaskDrainPeriod", 0, 0x24, 0x9c40, "RW"),
      std::make_tuple("gloSyncIdleState", 0, 0x28, 0x0, "RW"),
      std::make_tuple("gloSyncBcidOffset", 0, 0x29, 0x0, "RW"),
      std::make_tuple("fiberRemapSel", 0, 0x2a, 0x0, "RW"),

    });
  }
}  // namespace nsw
#endif  // NSWCONFIGURATION_SCAXREGISTERS_H_
