#ifndef NSWCONFIGURATION_TP_I2CREGISTERMAPPINGS_H_
#define NSWCONFIGURATION_TP_I2CREGISTERMAPPINGS_H_

/*
 * ----------------------------------------------------------------------------------
 * -- Source auto-generated via jinja2 templates for use with wuppercodegen
 * --
 * -- Company:  The Weizmann Institute of Science
 * -- Engineer: Noam Inbari (noam.inbari@weizmann.ac.il)
 * --
 * -- Edits and review: Lawrence Lee (lawrence.lee.jr@cern.ch)
 * --
 * ----------------------------------------------------------------------------------
 */

#include <map>
#include <vector>
#include <string>
#include <utility>

#include "NSWConfiguration/Types.h"


// -------------	NSW	-------------
static const char TP_NAME_NSW[] ="NSW";
static const i2c::AddressRegisterMap TP_REGISTERS_NSW = {
		{ "NSW_Firmware_version_time_stamp_READONLY", { {"register", 32 } } },
		{ "NSW_EndcapSector_ID", { {"register", 5 } } },
		{ "NSW_XL1ID", { {"register", 8 } } },
		{ "NSW_Run_number", { {"register", 32 } } },
		{ "NSW_orbit_count_READONLY", { {"register", 32 } } },
		{ "NSW_delta_theta_cut", { {"register", 5 } } },
		{ "NSW_mezz_PLL_reset", { {"register", 1 } } },
		{ "NSW_XVC_IP_low_byte", { {"register", 8 } } },
		{ "NSW_BC_offset", { {"register", 12 } } },
		{ "NSW_BC_L1A_window", { {"register", 3 } } },
		{ "NSW_BC_monitoring_window", { {"register", 3 } } },
		{ "NSW_send_RODBUSY_on", { {"register", 1 } } },
		{ "NSW_send_RODBUSY_off", { {"register", 1 } } },
		{ "NSW_enable_LIA_data_output", { {"register", 1 } } },
		{ "NSW_FELIX_RX_link_OK_READONLY", { {"register", 1 } } },
		{ "NSW_Jitter_cleaner_status_0_READONLY", { {"register", 1 } } },
		{ "NSW_Jitter_cleaner_status_1_READONLY", { {"register", 1 } } },
		{ "NSW_Jitter_cleaner_status_2_READONLY", { {"register", 1 } } },
		{ "NSW_Jitter_cleaner_status_3_READONLY", { {"register", 1 } } },
	};

static const std::vector<std::string> TP_REGISTERORDER_NSW = {
		{ "NSW_Firmware_version_time_stamp_READONLY" },
		{ "NSW_EndcapSector_ID" },
		{ "NSW_XL1ID" },
		{ "NSW_Run_number" },
		{ "NSW_orbit_count_READONLY" },
		{ "NSW_delta_theta_cut" },
		{ "NSW_mezz_PLL_reset" },
		{ "NSW_XVC_IP_low_byte" },
		{ "NSW_BC_offset" },
		{ "NSW_BC_L1A_window" },
		{ "NSW_BC_monitoring_window" },
		{ "NSW_send_RODBUSY_on" },
		{ "NSW_send_RODBUSY_off" },
		{ "NSW_enable_LIA_data_output" },
		{ "NSW_FELIX_RX_link_OK_READONLY" },
		{ "NSW_Jitter_cleaner_status_0_READONLY" },
		{ "NSW_Jitter_cleaner_status_1_READONLY" },
		{ "NSW_Jitter_cleaner_status_2_READONLY" },
		{ "NSW_Jitter_cleaner_status_3_READONLY" },
	};

// -------------	MM_lnk	-------------
static const char TP_NAME_MM_lnk[] ="MM_lnk";
static const i2c::AddressRegisterMap TP_REGISTERS_MM_lnk = {
		{ "MM_lnk_gbt_link_alligned_READONLY", { {"register", 32 } } },
		{ "MM_lnk_gbt_pll_locked_READONLY", { {"register", 9 } } },
		{ "MM_lnk_gbt_pll_reset", { {"register", 9 } } },
		{ "MM_lnk_gbt_hw_reset", { {"register", 1 } } },
		{ "MM_lnk_gbt_link_error_READONLY", { {"register", 32 } } },
		{ "MM_lnk_gbt_channel_mask", { {"register", 32 } } },
	};

static const std::vector<std::string> TP_REGISTERORDER_MM_lnk = {
		{ "MM_lnk_gbt_link_alligned_READONLY" },
		{ "MM_lnk_gbt_pll_locked_READONLY" },
		{ "MM_lnk_gbt_pll_reset" },
		{ "MM_lnk_gbt_hw_reset" },
		{ "MM_lnk_gbt_link_error_READONLY" },
		{ "MM_lnk_gbt_channel_mask" },
	};

// -------------	MM_addc	-------------
static const char TP_NAME_MM_addc[] ="MM_addc";
static const i2c::AddressRegisterMap TP_REGISTERS_MM_addc = {
		{ "MM_addc_addc_packet_parity_error_READONLY", { {"register", 32 } } },
		{ "MM_addc_addc_packet_bc_error_READONLY", { {"register", 32 } } },
		{ "MM_addc_addc_packet_format_error_READONLY", { {"register", 32 } } },
		{ "MM_addc_addc_packet_BC_offset_0", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_1", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_2", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_3", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_4", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_5", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_6", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_7", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_8", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_9", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_10", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_11", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_12", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_13", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_14", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_15", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_16", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_17", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_18", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_19", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_20", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_21", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_22", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_23", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_24", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_25", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_26", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_27", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_28", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_29", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_30", { {"register", 8 } } },
		{ "MM_addc_addc_packet_BC_offset_31", { {"register", 8 } } },
	};

static const std::vector<std::string> TP_REGISTERORDER_MM_addc = {
		{ "MM_addc_addc_packet_parity_error_READONLY" },
		{ "MM_addc_addc_packet_bc_error_READONLY" },
		{ "MM_addc_addc_packet_format_error_READONLY" },
		{ "MM_addc_addc_packet_BC_offset_0" },
		{ "MM_addc_addc_packet_BC_offset_1" },
		{ "MM_addc_addc_packet_BC_offset_2" },
		{ "MM_addc_addc_packet_BC_offset_3" },
		{ "MM_addc_addc_packet_BC_offset_4" },
		{ "MM_addc_addc_packet_BC_offset_5" },
		{ "MM_addc_addc_packet_BC_offset_6" },
		{ "MM_addc_addc_packet_BC_offset_7" },
		{ "MM_addc_addc_packet_BC_offset_8" },
		{ "MM_addc_addc_packet_BC_offset_9" },
		{ "MM_addc_addc_packet_BC_offset_10" },
		{ "MM_addc_addc_packet_BC_offset_11" },
		{ "MM_addc_addc_packet_BC_offset_12" },
		{ "MM_addc_addc_packet_BC_offset_13" },
		{ "MM_addc_addc_packet_BC_offset_14" },
		{ "MM_addc_addc_packet_BC_offset_15" },
		{ "MM_addc_addc_packet_BC_offset_16" },
		{ "MM_addc_addc_packet_BC_offset_17" },
		{ "MM_addc_addc_packet_BC_offset_18" },
		{ "MM_addc_addc_packet_BC_offset_19" },
		{ "MM_addc_addc_packet_BC_offset_20" },
		{ "MM_addc_addc_packet_BC_offset_21" },
		{ "MM_addc_addc_packet_BC_offset_22" },
		{ "MM_addc_addc_packet_BC_offset_23" },
		{ "MM_addc_addc_packet_BC_offset_24" },
		{ "MM_addc_addc_packet_BC_offset_25" },
		{ "MM_addc_addc_packet_BC_offset_26" },
		{ "MM_addc_addc_packet_BC_offset_27" },
		{ "MM_addc_addc_packet_BC_offset_28" },
		{ "MM_addc_addc_packet_BC_offset_29" },
		{ "MM_addc_addc_packet_BC_offset_30" },
		{ "MM_addc_addc_packet_BC_offset_31" },
	};

// -------------	MM	-------------
static const char TP_NAME_MM[] ="MM";
static const i2c::AddressRegisterMap TP_REGISTERS_MM = {
		{ "MM_tp_status_READONLY", { {"register", 32 } } },
		{ "MM_tp_local_bc_disable", { {"register", 1 } } },
		{ "MM_tp_local_bc_reset", { {"register", 1 } } },
	};

static const std::vector<std::string> TP_REGISTERORDER_MM = {
		{ "MM_tp_status_READONLY" },
		{ "MM_tp_local_bc_disable" },
		{ "MM_tp_local_bc_reset" },
	};

// -------------	MM_alg	-------------
static const char TP_NAME_MM_alg[] ="MM_alg";
static const i2c::AddressRegisterMap TP_REGISTERS_MM_alg = {
		{ "MM_alg_algor_strip0_offset_0", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_1", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_2", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_3", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_4", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_5", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_6", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_7", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_8", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_9", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_10", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_11", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_12", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_13", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_14", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_15", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_16", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_17", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_18", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_19", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_20", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_21", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_22", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_23", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_24", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_25", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_26", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_27", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_28", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_29", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_30", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_31", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_32", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_33", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_34", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_35", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_36", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_37", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_38", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_39", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_40", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_41", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_42", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_43", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_44", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_45", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_46", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_47", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_48", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_49", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_50", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_51", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_52", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_53", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_54", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_55", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_56", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_57", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_58", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_59", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_60", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_61", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_62", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_63", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_64", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_65", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_66", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_67", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_68", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_69", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_70", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_71", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_72", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_73", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_74", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_75", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_76", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_77", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_78", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_79", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_80", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_81", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_82", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_83", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_84", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_85", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_86", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_87", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_88", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_89", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_90", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_91", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_92", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_93", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_94", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_95", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_96", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_97", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_98", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_99", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_100", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_101", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_102", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_103", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_104", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_105", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_106", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_107", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_108", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_109", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_110", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_111", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_112", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_113", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_114", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_115", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_116", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_117", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_118", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_119", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_120", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_121", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_122", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_123", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_124", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_125", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_126", { {"register", 16 } } },
		{ "MM_alg_algor_strip0_offset_127", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_0", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_1", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_2", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_3", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_4", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_5", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_6", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_7", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_8", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_9", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_10", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_11", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_12", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_13", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_14", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_15", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_16", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_17", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_18", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_19", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_20", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_21", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_22", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_23", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_24", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_25", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_26", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_27", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_28", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_29", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_30", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_31", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_32", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_33", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_34", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_35", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_36", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_37", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_38", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_39", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_40", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_41", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_42", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_43", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_44", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_45", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_46", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_47", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_48", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_49", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_50", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_51", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_52", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_53", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_54", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_55", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_56", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_57", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_58", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_59", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_60", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_61", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_62", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_63", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_64", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_65", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_66", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_67", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_68", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_69", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_70", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_71", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_72", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_73", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_74", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_75", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_76", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_77", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_78", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_79", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_80", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_81", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_82", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_83", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_84", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_85", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_86", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_87", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_88", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_89", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_90", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_91", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_92", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_93", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_94", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_95", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_96", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_97", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_98", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_99", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_100", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_101", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_102", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_103", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_104", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_105", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_106", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_107", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_108", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_109", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_110", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_111", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_112", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_113", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_114", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_115", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_116", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_117", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_118", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_119", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_120", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_121", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_122", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_123", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_124", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_125", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_126", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_127", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_0", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_1", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_2", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_3", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_4", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_5", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_6", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_7", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_8", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_9", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_10", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_11", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_12", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_13", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_14", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_15", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_16", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_17", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_18", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_19", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_20", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_21", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_22", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_23", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_24", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_25", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_26", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_27", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_28", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_29", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_30", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_31", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_32", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_33", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_34", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_35", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_36", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_37", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_38", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_39", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_40", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_41", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_42", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_43", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_44", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_45", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_46", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_47", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_48", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_49", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_50", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_51", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_52", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_53", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_54", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_55", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_56", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_57", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_58", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_59", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_60", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_61", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_62", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_63", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_64", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_65", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_66", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_67", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_68", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_69", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_70", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_71", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_72", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_73", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_74", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_75", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_76", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_77", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_78", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_79", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_80", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_81", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_82", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_83", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_84", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_85", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_86", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_87", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_88", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_89", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_90", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_91", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_92", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_93", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_94", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_95", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_96", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_97", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_98", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_99", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_100", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_101", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_102", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_103", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_104", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_105", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_106", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_107", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_108", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_109", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_110", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_111", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_112", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_113", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_114", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_115", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_116", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_117", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_118", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_119", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_120", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_121", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_122", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_123", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_124", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_125", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_126", { {"register", 16 } } },
		{ "MM_alg_algor_plane_offset_recip_127", { {"register", 16 } } },
		{ "MM_alg_algor_mmfe8_invert", { {"register", 32 } } },
		{ "MM_alg_algor_roi_map_wrAddr", { {"register", 16 } } },
		{ "MM_alg_algor_roi_map_wrData", { {"register", 16 } } },
		{ "MM_alg_algor_roi_map_wrEn", { {"register", 1 } } },
		{ "MM_alg_algor_mxlocal_parameters_wrAddr", { {"register", 16 } } },
		{ "MM_alg_algor_mxlocal_parameters_wrData", { {"register", 16 } } },
		{ "MM_alg_algor_mxlocal_parameters_wrEn", { {"register", 1 } } },
		{ "MM_alg_algor_dtheta_parameters_wrAddr", { {"register", 16 } } },
		{ "MM_alg_algor_dtheta_parameters_wrData", { {"register", 16 } } },
		{ "MM_alg_algor_dtheta_parameters_wrEn", { {"register", 1 } } },
		{ "MM_alg_algor_region_mask", { {"register", 16 } } },
	};

static const std::vector<std::string> TP_REGISTERORDER_MM_alg = {
		{ "MM_alg_algor_strip0_offset_0" },
		{ "MM_alg_algor_strip0_offset_1" },
		{ "MM_alg_algor_strip0_offset_2" },
		{ "MM_alg_algor_strip0_offset_3" },
		{ "MM_alg_algor_strip0_offset_4" },
		{ "MM_alg_algor_strip0_offset_5" },
		{ "MM_alg_algor_strip0_offset_6" },
		{ "MM_alg_algor_strip0_offset_7" },
		{ "MM_alg_algor_strip0_offset_8" },
		{ "MM_alg_algor_strip0_offset_9" },
		{ "MM_alg_algor_strip0_offset_10" },
		{ "MM_alg_algor_strip0_offset_11" },
		{ "MM_alg_algor_strip0_offset_12" },
		{ "MM_alg_algor_strip0_offset_13" },
		{ "MM_alg_algor_strip0_offset_14" },
		{ "MM_alg_algor_strip0_offset_15" },
		{ "MM_alg_algor_strip0_offset_16" },
		{ "MM_alg_algor_strip0_offset_17" },
		{ "MM_alg_algor_strip0_offset_18" },
		{ "MM_alg_algor_strip0_offset_19" },
		{ "MM_alg_algor_strip0_offset_20" },
		{ "MM_alg_algor_strip0_offset_21" },
		{ "MM_alg_algor_strip0_offset_22" },
		{ "MM_alg_algor_strip0_offset_23" },
		{ "MM_alg_algor_strip0_offset_24" },
		{ "MM_alg_algor_strip0_offset_25" },
		{ "MM_alg_algor_strip0_offset_26" },
		{ "MM_alg_algor_strip0_offset_27" },
		{ "MM_alg_algor_strip0_offset_28" },
		{ "MM_alg_algor_strip0_offset_29" },
		{ "MM_alg_algor_strip0_offset_30" },
		{ "MM_alg_algor_strip0_offset_31" },
		{ "MM_alg_algor_strip0_offset_32" },
		{ "MM_alg_algor_strip0_offset_33" },
		{ "MM_alg_algor_strip0_offset_34" },
		{ "MM_alg_algor_strip0_offset_35" },
		{ "MM_alg_algor_strip0_offset_36" },
		{ "MM_alg_algor_strip0_offset_37" },
		{ "MM_alg_algor_strip0_offset_38" },
		{ "MM_alg_algor_strip0_offset_39" },
		{ "MM_alg_algor_strip0_offset_40" },
		{ "MM_alg_algor_strip0_offset_41" },
		{ "MM_alg_algor_strip0_offset_42" },
		{ "MM_alg_algor_strip0_offset_43" },
		{ "MM_alg_algor_strip0_offset_44" },
		{ "MM_alg_algor_strip0_offset_45" },
		{ "MM_alg_algor_strip0_offset_46" },
		{ "MM_alg_algor_strip0_offset_47" },
		{ "MM_alg_algor_strip0_offset_48" },
		{ "MM_alg_algor_strip0_offset_49" },
		{ "MM_alg_algor_strip0_offset_50" },
		{ "MM_alg_algor_strip0_offset_51" },
		{ "MM_alg_algor_strip0_offset_52" },
		{ "MM_alg_algor_strip0_offset_53" },
		{ "MM_alg_algor_strip0_offset_54" },
		{ "MM_alg_algor_strip0_offset_55" },
		{ "MM_alg_algor_strip0_offset_56" },
		{ "MM_alg_algor_strip0_offset_57" },
		{ "MM_alg_algor_strip0_offset_58" },
		{ "MM_alg_algor_strip0_offset_59" },
		{ "MM_alg_algor_strip0_offset_60" },
		{ "MM_alg_algor_strip0_offset_61" },
		{ "MM_alg_algor_strip0_offset_62" },
		{ "MM_alg_algor_strip0_offset_63" },
		{ "MM_alg_algor_strip0_offset_64" },
		{ "MM_alg_algor_strip0_offset_65" },
		{ "MM_alg_algor_strip0_offset_66" },
		{ "MM_alg_algor_strip0_offset_67" },
		{ "MM_alg_algor_strip0_offset_68" },
		{ "MM_alg_algor_strip0_offset_69" },
		{ "MM_alg_algor_strip0_offset_70" },
		{ "MM_alg_algor_strip0_offset_71" },
		{ "MM_alg_algor_strip0_offset_72" },
		{ "MM_alg_algor_strip0_offset_73" },
		{ "MM_alg_algor_strip0_offset_74" },
		{ "MM_alg_algor_strip0_offset_75" },
		{ "MM_alg_algor_strip0_offset_76" },
		{ "MM_alg_algor_strip0_offset_77" },
		{ "MM_alg_algor_strip0_offset_78" },
		{ "MM_alg_algor_strip0_offset_79" },
		{ "MM_alg_algor_strip0_offset_80" },
		{ "MM_alg_algor_strip0_offset_81" },
		{ "MM_alg_algor_strip0_offset_82" },
		{ "MM_alg_algor_strip0_offset_83" },
		{ "MM_alg_algor_strip0_offset_84" },
		{ "MM_alg_algor_strip0_offset_85" },
		{ "MM_alg_algor_strip0_offset_86" },
		{ "MM_alg_algor_strip0_offset_87" },
		{ "MM_alg_algor_strip0_offset_88" },
		{ "MM_alg_algor_strip0_offset_89" },
		{ "MM_alg_algor_strip0_offset_90" },
		{ "MM_alg_algor_strip0_offset_91" },
		{ "MM_alg_algor_strip0_offset_92" },
		{ "MM_alg_algor_strip0_offset_93" },
		{ "MM_alg_algor_strip0_offset_94" },
		{ "MM_alg_algor_strip0_offset_95" },
		{ "MM_alg_algor_strip0_offset_96" },
		{ "MM_alg_algor_strip0_offset_97" },
		{ "MM_alg_algor_strip0_offset_98" },
		{ "MM_alg_algor_strip0_offset_99" },
		{ "MM_alg_algor_strip0_offset_100" },
		{ "MM_alg_algor_strip0_offset_101" },
		{ "MM_alg_algor_strip0_offset_102" },
		{ "MM_alg_algor_strip0_offset_103" },
		{ "MM_alg_algor_strip0_offset_104" },
		{ "MM_alg_algor_strip0_offset_105" },
		{ "MM_alg_algor_strip0_offset_106" },
		{ "MM_alg_algor_strip0_offset_107" },
		{ "MM_alg_algor_strip0_offset_108" },
		{ "MM_alg_algor_strip0_offset_109" },
		{ "MM_alg_algor_strip0_offset_110" },
		{ "MM_alg_algor_strip0_offset_111" },
		{ "MM_alg_algor_strip0_offset_112" },
		{ "MM_alg_algor_strip0_offset_113" },
		{ "MM_alg_algor_strip0_offset_114" },
		{ "MM_alg_algor_strip0_offset_115" },
		{ "MM_alg_algor_strip0_offset_116" },
		{ "MM_alg_algor_strip0_offset_117" },
		{ "MM_alg_algor_strip0_offset_118" },
		{ "MM_alg_algor_strip0_offset_119" },
		{ "MM_alg_algor_strip0_offset_120" },
		{ "MM_alg_algor_strip0_offset_121" },
		{ "MM_alg_algor_strip0_offset_122" },
		{ "MM_alg_algor_strip0_offset_123" },
		{ "MM_alg_algor_strip0_offset_124" },
		{ "MM_alg_algor_strip0_offset_125" },
		{ "MM_alg_algor_strip0_offset_126" },
		{ "MM_alg_algor_strip0_offset_127" },
		{ "MM_alg_algor_plane_offset_0" },
		{ "MM_alg_algor_plane_offset_1" },
		{ "MM_alg_algor_plane_offset_2" },
		{ "MM_alg_algor_plane_offset_3" },
		{ "MM_alg_algor_plane_offset_4" },
		{ "MM_alg_algor_plane_offset_5" },
		{ "MM_alg_algor_plane_offset_6" },
		{ "MM_alg_algor_plane_offset_7" },
		{ "MM_alg_algor_plane_offset_8" },
		{ "MM_alg_algor_plane_offset_9" },
		{ "MM_alg_algor_plane_offset_10" },
		{ "MM_alg_algor_plane_offset_11" },
		{ "MM_alg_algor_plane_offset_12" },
		{ "MM_alg_algor_plane_offset_13" },
		{ "MM_alg_algor_plane_offset_14" },
		{ "MM_alg_algor_plane_offset_15" },
		{ "MM_alg_algor_plane_offset_16" },
		{ "MM_alg_algor_plane_offset_17" },
		{ "MM_alg_algor_plane_offset_18" },
		{ "MM_alg_algor_plane_offset_19" },
		{ "MM_alg_algor_plane_offset_20" },
		{ "MM_alg_algor_plane_offset_21" },
		{ "MM_alg_algor_plane_offset_22" },
		{ "MM_alg_algor_plane_offset_23" },
		{ "MM_alg_algor_plane_offset_24" },
		{ "MM_alg_algor_plane_offset_25" },
		{ "MM_alg_algor_plane_offset_26" },
		{ "MM_alg_algor_plane_offset_27" },
		{ "MM_alg_algor_plane_offset_28" },
		{ "MM_alg_algor_plane_offset_29" },
		{ "MM_alg_algor_plane_offset_30" },
		{ "MM_alg_algor_plane_offset_31" },
		{ "MM_alg_algor_plane_offset_32" },
		{ "MM_alg_algor_plane_offset_33" },
		{ "MM_alg_algor_plane_offset_34" },
		{ "MM_alg_algor_plane_offset_35" },
		{ "MM_alg_algor_plane_offset_36" },
		{ "MM_alg_algor_plane_offset_37" },
		{ "MM_alg_algor_plane_offset_38" },
		{ "MM_alg_algor_plane_offset_39" },
		{ "MM_alg_algor_plane_offset_40" },
		{ "MM_alg_algor_plane_offset_41" },
		{ "MM_alg_algor_plane_offset_42" },
		{ "MM_alg_algor_plane_offset_43" },
		{ "MM_alg_algor_plane_offset_44" },
		{ "MM_alg_algor_plane_offset_45" },
		{ "MM_alg_algor_plane_offset_46" },
		{ "MM_alg_algor_plane_offset_47" },
		{ "MM_alg_algor_plane_offset_48" },
		{ "MM_alg_algor_plane_offset_49" },
		{ "MM_alg_algor_plane_offset_50" },
		{ "MM_alg_algor_plane_offset_51" },
		{ "MM_alg_algor_plane_offset_52" },
		{ "MM_alg_algor_plane_offset_53" },
		{ "MM_alg_algor_plane_offset_54" },
		{ "MM_alg_algor_plane_offset_55" },
		{ "MM_alg_algor_plane_offset_56" },
		{ "MM_alg_algor_plane_offset_57" },
		{ "MM_alg_algor_plane_offset_58" },
		{ "MM_alg_algor_plane_offset_59" },
		{ "MM_alg_algor_plane_offset_60" },
		{ "MM_alg_algor_plane_offset_61" },
		{ "MM_alg_algor_plane_offset_62" },
		{ "MM_alg_algor_plane_offset_63" },
		{ "MM_alg_algor_plane_offset_64" },
		{ "MM_alg_algor_plane_offset_65" },
		{ "MM_alg_algor_plane_offset_66" },
		{ "MM_alg_algor_plane_offset_67" },
		{ "MM_alg_algor_plane_offset_68" },
		{ "MM_alg_algor_plane_offset_69" },
		{ "MM_alg_algor_plane_offset_70" },
		{ "MM_alg_algor_plane_offset_71" },
		{ "MM_alg_algor_plane_offset_72" },
		{ "MM_alg_algor_plane_offset_73" },
		{ "MM_alg_algor_plane_offset_74" },
		{ "MM_alg_algor_plane_offset_75" },
		{ "MM_alg_algor_plane_offset_76" },
		{ "MM_alg_algor_plane_offset_77" },
		{ "MM_alg_algor_plane_offset_78" },
		{ "MM_alg_algor_plane_offset_79" },
		{ "MM_alg_algor_plane_offset_80" },
		{ "MM_alg_algor_plane_offset_81" },
		{ "MM_alg_algor_plane_offset_82" },
		{ "MM_alg_algor_plane_offset_83" },
		{ "MM_alg_algor_plane_offset_84" },
		{ "MM_alg_algor_plane_offset_85" },
		{ "MM_alg_algor_plane_offset_86" },
		{ "MM_alg_algor_plane_offset_87" },
		{ "MM_alg_algor_plane_offset_88" },
		{ "MM_alg_algor_plane_offset_89" },
		{ "MM_alg_algor_plane_offset_90" },
		{ "MM_alg_algor_plane_offset_91" },
		{ "MM_alg_algor_plane_offset_92" },
		{ "MM_alg_algor_plane_offset_93" },
		{ "MM_alg_algor_plane_offset_94" },
		{ "MM_alg_algor_plane_offset_95" },
		{ "MM_alg_algor_plane_offset_96" },
		{ "MM_alg_algor_plane_offset_97" },
		{ "MM_alg_algor_plane_offset_98" },
		{ "MM_alg_algor_plane_offset_99" },
		{ "MM_alg_algor_plane_offset_100" },
		{ "MM_alg_algor_plane_offset_101" },
		{ "MM_alg_algor_plane_offset_102" },
		{ "MM_alg_algor_plane_offset_103" },
		{ "MM_alg_algor_plane_offset_104" },
		{ "MM_alg_algor_plane_offset_105" },
		{ "MM_alg_algor_plane_offset_106" },
		{ "MM_alg_algor_plane_offset_107" },
		{ "MM_alg_algor_plane_offset_108" },
		{ "MM_alg_algor_plane_offset_109" },
		{ "MM_alg_algor_plane_offset_110" },
		{ "MM_alg_algor_plane_offset_111" },
		{ "MM_alg_algor_plane_offset_112" },
		{ "MM_alg_algor_plane_offset_113" },
		{ "MM_alg_algor_plane_offset_114" },
		{ "MM_alg_algor_plane_offset_115" },
		{ "MM_alg_algor_plane_offset_116" },
		{ "MM_alg_algor_plane_offset_117" },
		{ "MM_alg_algor_plane_offset_118" },
		{ "MM_alg_algor_plane_offset_119" },
		{ "MM_alg_algor_plane_offset_120" },
		{ "MM_alg_algor_plane_offset_121" },
		{ "MM_alg_algor_plane_offset_122" },
		{ "MM_alg_algor_plane_offset_123" },
		{ "MM_alg_algor_plane_offset_124" },
		{ "MM_alg_algor_plane_offset_125" },
		{ "MM_alg_algor_plane_offset_126" },
		{ "MM_alg_algor_plane_offset_127" },
		{ "MM_alg_algor_plane_offset_recip_0" },
		{ "MM_alg_algor_plane_offset_recip_1" },
		{ "MM_alg_algor_plane_offset_recip_2" },
		{ "MM_alg_algor_plane_offset_recip_3" },
		{ "MM_alg_algor_plane_offset_recip_4" },
		{ "MM_alg_algor_plane_offset_recip_5" },
		{ "MM_alg_algor_plane_offset_recip_6" },
		{ "MM_alg_algor_plane_offset_recip_7" },
		{ "MM_alg_algor_plane_offset_recip_8" },
		{ "MM_alg_algor_plane_offset_recip_9" },
		{ "MM_alg_algor_plane_offset_recip_10" },
		{ "MM_alg_algor_plane_offset_recip_11" },
		{ "MM_alg_algor_plane_offset_recip_12" },
		{ "MM_alg_algor_plane_offset_recip_13" },
		{ "MM_alg_algor_plane_offset_recip_14" },
		{ "MM_alg_algor_plane_offset_recip_15" },
		{ "MM_alg_algor_plane_offset_recip_16" },
		{ "MM_alg_algor_plane_offset_recip_17" },
		{ "MM_alg_algor_plane_offset_recip_18" },
		{ "MM_alg_algor_plane_offset_recip_19" },
		{ "MM_alg_algor_plane_offset_recip_20" },
		{ "MM_alg_algor_plane_offset_recip_21" },
		{ "MM_alg_algor_plane_offset_recip_22" },
		{ "MM_alg_algor_plane_offset_recip_23" },
		{ "MM_alg_algor_plane_offset_recip_24" },
		{ "MM_alg_algor_plane_offset_recip_25" },
		{ "MM_alg_algor_plane_offset_recip_26" },
		{ "MM_alg_algor_plane_offset_recip_27" },
		{ "MM_alg_algor_plane_offset_recip_28" },
		{ "MM_alg_algor_plane_offset_recip_29" },
		{ "MM_alg_algor_plane_offset_recip_30" },
		{ "MM_alg_algor_plane_offset_recip_31" },
		{ "MM_alg_algor_plane_offset_recip_32" },
		{ "MM_alg_algor_plane_offset_recip_33" },
		{ "MM_alg_algor_plane_offset_recip_34" },
		{ "MM_alg_algor_plane_offset_recip_35" },
		{ "MM_alg_algor_plane_offset_recip_36" },
		{ "MM_alg_algor_plane_offset_recip_37" },
		{ "MM_alg_algor_plane_offset_recip_38" },
		{ "MM_alg_algor_plane_offset_recip_39" },
		{ "MM_alg_algor_plane_offset_recip_40" },
		{ "MM_alg_algor_plane_offset_recip_41" },
		{ "MM_alg_algor_plane_offset_recip_42" },
		{ "MM_alg_algor_plane_offset_recip_43" },
		{ "MM_alg_algor_plane_offset_recip_44" },
		{ "MM_alg_algor_plane_offset_recip_45" },
		{ "MM_alg_algor_plane_offset_recip_46" },
		{ "MM_alg_algor_plane_offset_recip_47" },
		{ "MM_alg_algor_plane_offset_recip_48" },
		{ "MM_alg_algor_plane_offset_recip_49" },
		{ "MM_alg_algor_plane_offset_recip_50" },
		{ "MM_alg_algor_plane_offset_recip_51" },
		{ "MM_alg_algor_plane_offset_recip_52" },
		{ "MM_alg_algor_plane_offset_recip_53" },
		{ "MM_alg_algor_plane_offset_recip_54" },
		{ "MM_alg_algor_plane_offset_recip_55" },
		{ "MM_alg_algor_plane_offset_recip_56" },
		{ "MM_alg_algor_plane_offset_recip_57" },
		{ "MM_alg_algor_plane_offset_recip_58" },
		{ "MM_alg_algor_plane_offset_recip_59" },
		{ "MM_alg_algor_plane_offset_recip_60" },
		{ "MM_alg_algor_plane_offset_recip_61" },
		{ "MM_alg_algor_plane_offset_recip_62" },
		{ "MM_alg_algor_plane_offset_recip_63" },
		{ "MM_alg_algor_plane_offset_recip_64" },
		{ "MM_alg_algor_plane_offset_recip_65" },
		{ "MM_alg_algor_plane_offset_recip_66" },
		{ "MM_alg_algor_plane_offset_recip_67" },
		{ "MM_alg_algor_plane_offset_recip_68" },
		{ "MM_alg_algor_plane_offset_recip_69" },
		{ "MM_alg_algor_plane_offset_recip_70" },
		{ "MM_alg_algor_plane_offset_recip_71" },
		{ "MM_alg_algor_plane_offset_recip_72" },
		{ "MM_alg_algor_plane_offset_recip_73" },
		{ "MM_alg_algor_plane_offset_recip_74" },
		{ "MM_alg_algor_plane_offset_recip_75" },
		{ "MM_alg_algor_plane_offset_recip_76" },
		{ "MM_alg_algor_plane_offset_recip_77" },
		{ "MM_alg_algor_plane_offset_recip_78" },
		{ "MM_alg_algor_plane_offset_recip_79" },
		{ "MM_alg_algor_plane_offset_recip_80" },
		{ "MM_alg_algor_plane_offset_recip_81" },
		{ "MM_alg_algor_plane_offset_recip_82" },
		{ "MM_alg_algor_plane_offset_recip_83" },
		{ "MM_alg_algor_plane_offset_recip_84" },
		{ "MM_alg_algor_plane_offset_recip_85" },
		{ "MM_alg_algor_plane_offset_recip_86" },
		{ "MM_alg_algor_plane_offset_recip_87" },
		{ "MM_alg_algor_plane_offset_recip_88" },
		{ "MM_alg_algor_plane_offset_recip_89" },
		{ "MM_alg_algor_plane_offset_recip_90" },
		{ "MM_alg_algor_plane_offset_recip_91" },
		{ "MM_alg_algor_plane_offset_recip_92" },
		{ "MM_alg_algor_plane_offset_recip_93" },
		{ "MM_alg_algor_plane_offset_recip_94" },
		{ "MM_alg_algor_plane_offset_recip_95" },
		{ "MM_alg_algor_plane_offset_recip_96" },
		{ "MM_alg_algor_plane_offset_recip_97" },
		{ "MM_alg_algor_plane_offset_recip_98" },
		{ "MM_alg_algor_plane_offset_recip_99" },
		{ "MM_alg_algor_plane_offset_recip_100" },
		{ "MM_alg_algor_plane_offset_recip_101" },
		{ "MM_alg_algor_plane_offset_recip_102" },
		{ "MM_alg_algor_plane_offset_recip_103" },
		{ "MM_alg_algor_plane_offset_recip_104" },
		{ "MM_alg_algor_plane_offset_recip_105" },
		{ "MM_alg_algor_plane_offset_recip_106" },
		{ "MM_alg_algor_plane_offset_recip_107" },
		{ "MM_alg_algor_plane_offset_recip_108" },
		{ "MM_alg_algor_plane_offset_recip_109" },
		{ "MM_alg_algor_plane_offset_recip_110" },
		{ "MM_alg_algor_plane_offset_recip_111" },
		{ "MM_alg_algor_plane_offset_recip_112" },
		{ "MM_alg_algor_plane_offset_recip_113" },
		{ "MM_alg_algor_plane_offset_recip_114" },
		{ "MM_alg_algor_plane_offset_recip_115" },
		{ "MM_alg_algor_plane_offset_recip_116" },
		{ "MM_alg_algor_plane_offset_recip_117" },
		{ "MM_alg_algor_plane_offset_recip_118" },
		{ "MM_alg_algor_plane_offset_recip_119" },
		{ "MM_alg_algor_plane_offset_recip_120" },
		{ "MM_alg_algor_plane_offset_recip_121" },
		{ "MM_alg_algor_plane_offset_recip_122" },
		{ "MM_alg_algor_plane_offset_recip_123" },
		{ "MM_alg_algor_plane_offset_recip_124" },
		{ "MM_alg_algor_plane_offset_recip_125" },
		{ "MM_alg_algor_plane_offset_recip_126" },
		{ "MM_alg_algor_plane_offset_recip_127" },
		{ "MM_alg_algor_mmfe8_invert" },
		{ "MM_alg_algor_roi_map_wrAddr" },
		{ "MM_alg_algor_roi_map_wrData" },
		{ "MM_alg_algor_roi_map_wrEn" },
		{ "MM_alg_algor_mxlocal_parameters_wrAddr" },
		{ "MM_alg_algor_mxlocal_parameters_wrData" },
		{ "MM_alg_algor_mxlocal_parameters_wrEn" },
		{ "MM_alg_algor_dtheta_parameters_wrAddr" },
		{ "MM_alg_algor_dtheta_parameters_wrData" },
		{ "MM_alg_algor_dtheta_parameters_wrEn" },
		{ "MM_alg_algor_region_mask" },
	};

// -------------	MM_diag	-------------
static const char TP_NAME_MM_diag[] ="MM_diag";
static const i2c::AddressRegisterMap TP_REGISTERS_MM_diag = {
		{ "MM_diag_diag_fifo_ef_READONLY", { {"register", 32 } } },
		{ "MM_diag_diag_fifo_of_READONLY", { {"register", 32 } } },
		{ "MM_diag_diag_gbt_loopback_data_wrAddr", { {"register", 32 } } },
		{ "MM_diag_diag_gbt_loopback_data_wrData", { {"register", 32 } } },
		{ "MM_diag_diag_gbt_loopback_data_wrEn", { {"register", 1 } } },
	};

static const std::vector<std::string> TP_REGISTERORDER_MM_diag = {
		{ "MM_diag_diag_fifo_ef_READONLY" },
		{ "MM_diag_diag_fifo_of_READONLY" },
		{ "MM_diag_diag_gbt_loopback_data_wrAddr" },
		{ "MM_diag_diag_gbt_loopback_data_wrData" },
		{ "MM_diag_diag_gbt_loopback_data_wrEn" },
	};

// -------------	sTGC_lnk	-------------
static const char TP_NAME_sTGC_lnk[] ="sTGC_lnk";
static const i2c::AddressRegisterMap TP_REGISTERS_sTGC_lnk = {
		{ "sTGC_lnk_GTH_MMC_RX_lock_READONLY", { {"register", 3 } } },
		{ "sTGC_lnk_GTH_TX_FSM_RESET_DONE_32_READONLY", { {"register", 32 } } },
		{ "sTGC_lnk_GTH_RX_FSM_RESET_DONE_32_READONLY", { {"register", 32 } } },
		{ "sTGC_lnk_GTH_cpllfbclklost_32_READONLY", { {"register", 32 } } },
		{ "sTGC_lnk_GTH_cplllock_32_READONLY", { {"register", 32 } } },
		{ "sTGC_lnk_GTH_rxresetdone_32_READONLY", { {"register", 32 } } },
		{ "sTGC_lnk_GTH_txresetdone_32_READONLY", { {"register", 32 } } },
		{ "sTGC_lnk_GTH_TX_FSM_RESET_DONE_4_READONLY", { {"register", 4 } } },
		{ "sTGC_lnk_GTH_RX_FSM_RESET_DONE_4_READONLY", { {"register", 4 } } },
		{ "sTGC_lnk_GTH_cpllfbclklost_4_READONLY", { {"register", 4 } } },
		{ "sTGC_lnk_GTH_cplllock_4_READONLY", { {"register", 4 } } },
		{ "sTGC_lnk_GTH_rxresetdone_4_READONLY", { {"register", 4 } } },
		{ "sTGC_lnk_GTH_txresetdone_4_READONLY", { {"register", 4 } } },
		{ "sTGC_lnk_GTH_QPLLLOCK_READONLY", { {"register", 12 } } },
		{ "sTGC_lnk_GTH_QPLLREFCLKLOST_READONLY", { {"register", 12 } } },
		{ "sTGC_lnk_GTH_QPLLRESET", { {"register", 12 } } },
		{ "sTGC_lnk_GlobalReset", { {"register", 1 } } },
		{ "sTGC_lnk_GTH_rxuserrdy_32", { {"register", 32 } } },
		{ "sTGC_lnk_GTH_rxuserrdy_4", { {"register", 4 } } },
		{ "sTGC_lnk_GTH_txuserrdy_32_READONLY", { {"register", 32 } } },
		{ "sTGC_lnk_GTH_txuserrdy_4", { {"register", 4 } } },
		{ "sTGC_lnk_GTH_cpllreset_32", { {"register", 32 } } },
		{ "sTGC_lnk_GTH_cpllreset_4", { {"register", 4 } } },
		{ "sTGC_lnk_GTH_gtrxreset_32", { {"register", 32 } } },
		{ "sTGC_lnk_GTH_gtrxreset_4", { {"register", 4 } } },
		{ "sTGC_lnk_GTH_gttxreset_32", { {"register", 32 } } },
		{ "sTGC_lnk_GTH_gttxreset_4", { {"register", 4 } } },
		{ "sTGC_lnk_V7_ANLINK_RX_WR_EN", { {"register", 1 } } },
		{ "sTGC_lnk_V7_ANLINK_RX_RD_EN", { {"register", 1 } } },
		{ "sTGC_lnk_V7_ANLINK_TX_WR_EN", { {"register", 1 } } },
		{ "sTGC_lnk_V7_ANLINK_TX_RD_EN", { {"register", 1 } } },
	};

static const std::vector<std::string> TP_REGISTERORDER_sTGC_lnk = {
		{ "sTGC_lnk_GTH_MMC_RX_lock_READONLY" },
		{ "sTGC_lnk_GTH_TX_FSM_RESET_DONE_32_READONLY" },
		{ "sTGC_lnk_GTH_RX_FSM_RESET_DONE_32_READONLY" },
		{ "sTGC_lnk_GTH_cpllfbclklost_32_READONLY" },
		{ "sTGC_lnk_GTH_cplllock_32_READONLY" },
		{ "sTGC_lnk_GTH_rxresetdone_32_READONLY" },
		{ "sTGC_lnk_GTH_txresetdone_32_READONLY" },
		{ "sTGC_lnk_GTH_TX_FSM_RESET_DONE_4_READONLY" },
		{ "sTGC_lnk_GTH_RX_FSM_RESET_DONE_4_READONLY" },
		{ "sTGC_lnk_GTH_cpllfbclklost_4_READONLY" },
		{ "sTGC_lnk_GTH_cplllock_4_READONLY" },
		{ "sTGC_lnk_GTH_rxresetdone_4_READONLY" },
		{ "sTGC_lnk_GTH_txresetdone_4_READONLY" },
		{ "sTGC_lnk_GTH_QPLLLOCK_READONLY" },
		{ "sTGC_lnk_GTH_QPLLREFCLKLOST_READONLY" },
		{ "sTGC_lnk_GTH_QPLLRESET" },
		{ "sTGC_lnk_GlobalReset" },
		{ "sTGC_lnk_GTH_rxuserrdy_32" },
		{ "sTGC_lnk_GTH_rxuserrdy_4" },
		{ "sTGC_lnk_GTH_txuserrdy_32_READONLY" },
		{ "sTGC_lnk_GTH_txuserrdy_4" },
		{ "sTGC_lnk_GTH_cpllreset_32" },
		{ "sTGC_lnk_GTH_cpllreset_4" },
		{ "sTGC_lnk_GTH_gtrxreset_32" },
		{ "sTGC_lnk_GTH_gtrxreset_4" },
		{ "sTGC_lnk_GTH_gttxreset_32" },
		{ "sTGC_lnk_GTH_gttxreset_4" },
		{ "sTGC_lnk_V7_ANLINK_RX_WR_EN" },
		{ "sTGC_lnk_V7_ANLINK_RX_RD_EN" },
		{ "sTGC_lnk_V7_ANLINK_TX_WR_EN" },
		{ "sTGC_lnk_V7_ANLINK_TX_RD_EN" },
	};

// -------------	sTGC_V6	-------------
static const char TP_NAME_sTGC_V6[] ="sTGC_V6";
static const i2c::AddressRegisterMap TP_REGISTERS_sTGC_V6 = {
		{ "sTGC_V6_V6_global_RST", { {"register", 1 } } },
		{ "sTGC_V6_V6_UDP_GTX_RST", { {"register", 1 } } },
		{ "sTGC_V6_V6_ANLINK_RX_WR_EN", { {"register", 1 } } },
		{ "sTGC_V6_V6_ANLINK_RX_RD_EN", { {"register", 1 } } },
		{ "sTGC_V6_V6_ANLINK_TX_WR_EN", { {"register", 1 } } },
		{ "sTGC_V6_V6_ANLINK_TX_RD_EN", { {"register", 1 } } },
	};

static const std::vector<std::string> TP_REGISTERORDER_sTGC_V6 = {
		{ "sTGC_V6_V6_global_RST" },
		{ "sTGC_V6_V6_UDP_GTX_RST" },
		{ "sTGC_V6_V6_ANLINK_RX_WR_EN" },
		{ "sTGC_V6_V6_ANLINK_RX_RD_EN" },
		{ "sTGC_V6_V6_ANLINK_TX_WR_EN" },
		{ "sTGC_V6_V6_ANLINK_TX_RD_EN" },
	};

// -------------	sTGC_alg	-------------
static const char TP_NAME_sTGC_alg[] ="sTGC_alg";
static const i2c::AddressRegisterMap TP_REGISTERS_sTGC_alg = {
		{ "sTGC_alg_radial_offset_0", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_1", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_2", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_3", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_4", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_5", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_6", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_7", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_8", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_9", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_10", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_11", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_12", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_13", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_14", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_15", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_16", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_17", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_18", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_19", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_20", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_21", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_22", { {"register", 12 } } },
		{ "sTGC_alg_radial_offset_23", { {"register", 12 } } },
		{ "sTGC_alg_plane_offset_0", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_1", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_2", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_3", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_4", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_5", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_6", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_7", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_8", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_9", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_10", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_11", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_12", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_13", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_14", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_15", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_16", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_17", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_18", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_19", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_20", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_21", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_22", { {"register", 16 } } },
		{ "sTGC_alg_plane_offset_23", { {"register", 16 } } },
		{ "sTGC_alg_max_cluster_size", { {"register", 4 } } },
		{ "sTGC_alg_min_cluster_size", { {"register", 4 } } },
		{ "sTGC_alg_charge_thresh_cluster_0", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_1", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_2", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_3", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_4", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_5", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_6", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_7", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_8", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_9", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_10", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_11", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_12", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_13", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_14", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_15", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_16", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_17", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_18", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_19", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_20", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_21", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_22", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_cluster_23", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_0", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_1", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_2", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_3", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_4", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_5", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_6", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_7", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_8", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_9", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_10", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_11", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_12", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_13", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_14", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_15", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_16", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_17", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_18", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_19", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_20", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_21", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_22", { {"register", 6 } } },
		{ "sTGC_alg_charge_thresh_centroid_23", { {"register", 6 } } },
		{ "sTGC_alg_strip_dir", { {"register", 8 } } },
		{ "sTGC_alg_R_offset_0", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_1", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_2", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_3", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_4", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_5", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_6", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_7", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_8", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_9", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_10", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_11", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_12", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_13", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_14", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_15", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_16", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_17", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_18", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_19", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_20", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_21", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_22", { {"register", 16 } } },
		{ "sTGC_alg_R_offset_23", { {"register", 16 } } },
	};

static const std::vector<std::string> TP_REGISTERORDER_sTGC_alg = {
		{ "sTGC_alg_radial_offset_0" },
		{ "sTGC_alg_radial_offset_1" },
		{ "sTGC_alg_radial_offset_2" },
		{ "sTGC_alg_radial_offset_3" },
		{ "sTGC_alg_radial_offset_4" },
		{ "sTGC_alg_radial_offset_5" },
		{ "sTGC_alg_radial_offset_6" },
		{ "sTGC_alg_radial_offset_7" },
		{ "sTGC_alg_radial_offset_8" },
		{ "sTGC_alg_radial_offset_9" },
		{ "sTGC_alg_radial_offset_10" },
		{ "sTGC_alg_radial_offset_11" },
		{ "sTGC_alg_radial_offset_12" },
		{ "sTGC_alg_radial_offset_13" },
		{ "sTGC_alg_radial_offset_14" },
		{ "sTGC_alg_radial_offset_15" },
		{ "sTGC_alg_radial_offset_16" },
		{ "sTGC_alg_radial_offset_17" },
		{ "sTGC_alg_radial_offset_18" },
		{ "sTGC_alg_radial_offset_19" },
		{ "sTGC_alg_radial_offset_20" },
		{ "sTGC_alg_radial_offset_21" },
		{ "sTGC_alg_radial_offset_22" },
		{ "sTGC_alg_radial_offset_23" },
		{ "sTGC_alg_plane_offset_0" },
		{ "sTGC_alg_plane_offset_1" },
		{ "sTGC_alg_plane_offset_2" },
		{ "sTGC_alg_plane_offset_3" },
		{ "sTGC_alg_plane_offset_4" },
		{ "sTGC_alg_plane_offset_5" },
		{ "sTGC_alg_plane_offset_6" },
		{ "sTGC_alg_plane_offset_7" },
		{ "sTGC_alg_plane_offset_8" },
		{ "sTGC_alg_plane_offset_9" },
		{ "sTGC_alg_plane_offset_10" },
		{ "sTGC_alg_plane_offset_11" },
		{ "sTGC_alg_plane_offset_12" },
		{ "sTGC_alg_plane_offset_13" },
		{ "sTGC_alg_plane_offset_14" },
		{ "sTGC_alg_plane_offset_15" },
		{ "sTGC_alg_plane_offset_16" },
		{ "sTGC_alg_plane_offset_17" },
		{ "sTGC_alg_plane_offset_18" },
		{ "sTGC_alg_plane_offset_19" },
		{ "sTGC_alg_plane_offset_20" },
		{ "sTGC_alg_plane_offset_21" },
		{ "sTGC_alg_plane_offset_22" },
		{ "sTGC_alg_plane_offset_23" },
		{ "sTGC_alg_max_cluster_size" },
		{ "sTGC_alg_min_cluster_size" },
		{ "sTGC_alg_charge_thresh_cluster_0" },
		{ "sTGC_alg_charge_thresh_cluster_1" },
		{ "sTGC_alg_charge_thresh_cluster_2" },
		{ "sTGC_alg_charge_thresh_cluster_3" },
		{ "sTGC_alg_charge_thresh_cluster_4" },
		{ "sTGC_alg_charge_thresh_cluster_5" },
		{ "sTGC_alg_charge_thresh_cluster_6" },
		{ "sTGC_alg_charge_thresh_cluster_7" },
		{ "sTGC_alg_charge_thresh_cluster_8" },
		{ "sTGC_alg_charge_thresh_cluster_9" },
		{ "sTGC_alg_charge_thresh_cluster_10" },
		{ "sTGC_alg_charge_thresh_cluster_11" },
		{ "sTGC_alg_charge_thresh_cluster_12" },
		{ "sTGC_alg_charge_thresh_cluster_13" },
		{ "sTGC_alg_charge_thresh_cluster_14" },
		{ "sTGC_alg_charge_thresh_cluster_15" },
		{ "sTGC_alg_charge_thresh_cluster_16" },
		{ "sTGC_alg_charge_thresh_cluster_17" },
		{ "sTGC_alg_charge_thresh_cluster_18" },
		{ "sTGC_alg_charge_thresh_cluster_19" },
		{ "sTGC_alg_charge_thresh_cluster_20" },
		{ "sTGC_alg_charge_thresh_cluster_21" },
		{ "sTGC_alg_charge_thresh_cluster_22" },
		{ "sTGC_alg_charge_thresh_cluster_23" },
		{ "sTGC_alg_charge_thresh_centroid_0" },
		{ "sTGC_alg_charge_thresh_centroid_1" },
		{ "sTGC_alg_charge_thresh_centroid_2" },
		{ "sTGC_alg_charge_thresh_centroid_3" },
		{ "sTGC_alg_charge_thresh_centroid_4" },
		{ "sTGC_alg_charge_thresh_centroid_5" },
		{ "sTGC_alg_charge_thresh_centroid_6" },
		{ "sTGC_alg_charge_thresh_centroid_7" },
		{ "sTGC_alg_charge_thresh_centroid_8" },
		{ "sTGC_alg_charge_thresh_centroid_9" },
		{ "sTGC_alg_charge_thresh_centroid_10" },
		{ "sTGC_alg_charge_thresh_centroid_11" },
		{ "sTGC_alg_charge_thresh_centroid_12" },
		{ "sTGC_alg_charge_thresh_centroid_13" },
		{ "sTGC_alg_charge_thresh_centroid_14" },
		{ "sTGC_alg_charge_thresh_centroid_15" },
		{ "sTGC_alg_charge_thresh_centroid_16" },
		{ "sTGC_alg_charge_thresh_centroid_17" },
		{ "sTGC_alg_charge_thresh_centroid_18" },
		{ "sTGC_alg_charge_thresh_centroid_19" },
		{ "sTGC_alg_charge_thresh_centroid_20" },
		{ "sTGC_alg_charge_thresh_centroid_21" },
		{ "sTGC_alg_charge_thresh_centroid_22" },
		{ "sTGC_alg_charge_thresh_centroid_23" },
		{ "sTGC_alg_strip_dir" },
		{ "sTGC_alg_R_offset_0" },
		{ "sTGC_alg_R_offset_1" },
		{ "sTGC_alg_R_offset_2" },
		{ "sTGC_alg_R_offset_3" },
		{ "sTGC_alg_R_offset_4" },
		{ "sTGC_alg_R_offset_5" },
		{ "sTGC_alg_R_offset_6" },
		{ "sTGC_alg_R_offset_7" },
		{ "sTGC_alg_R_offset_8" },
		{ "sTGC_alg_R_offset_9" },
		{ "sTGC_alg_R_offset_10" },
		{ "sTGC_alg_R_offset_11" },
		{ "sTGC_alg_R_offset_12" },
		{ "sTGC_alg_R_offset_13" },
		{ "sTGC_alg_R_offset_14" },
		{ "sTGC_alg_R_offset_15" },
		{ "sTGC_alg_R_offset_16" },
		{ "sTGC_alg_R_offset_17" },
		{ "sTGC_alg_R_offset_18" },
		{ "sTGC_alg_R_offset_19" },
		{ "sTGC_alg_R_offset_20" },
		{ "sTGC_alg_R_offset_21" },
		{ "sTGC_alg_R_offset_22" },
		{ "sTGC_alg_R_offset_23" },
	};

// -------------	sTGC_mrg	-------------
static const char TP_NAME_sTGC_mrg[] ="sTGC_mrg";
static const i2c::AddressRegisterMap TP_REGISTERS_sTGC_mrg = {
		{ "sTGC_mrg_enable_MM_segments", { {"register", 8 } } },
		{ "sTGC_mrg_enable_SL_output", { {"register", 1 } } },
		{ "sTGC_mrg_SL_out_offset", { {"register", 3 } } },
		{ "sTGC_mrg_fiber_ctrl_param_0", { {"register", 16 } } },
		{ "sTGC_mrg_fiber_ctrl_param_1", { {"register", 16 } } },
		{ "sTGC_mrg_fiber_ctrl_param_2", { {"register", 16 } } },
		{ "sTGC_mrg_fiber_ctrl_param_3", { {"register", 16 } } },
	};

static const std::vector<std::string> TP_REGISTERORDER_sTGC_mrg = {
		{ "sTGC_mrg_enable_MM_segments" },
		{ "sTGC_mrg_enable_SL_output" },
		{ "sTGC_mrg_SL_out_offset" },
		{ "sTGC_mrg_fiber_ctrl_param_0" },
		{ "sTGC_mrg_fiber_ctrl_param_1" },
		{ "sTGC_mrg_fiber_ctrl_param_2" },
		{ "sTGC_mrg_fiber_ctrl_param_3" },
	};

/*
 * Map-Pairing Register Files Arrays
 */
#define NUM_REGISTER_FILES 10

static const i2c::AddressRegisterMap registerFilesArr[NUM_REGISTER_FILES] = {
	TP_REGISTERS_NSW,
	TP_REGISTERS_MM_lnk,
	TP_REGISTERS_MM_addc,
	TP_REGISTERS_MM,
	TP_REGISTERS_MM_alg,
	TP_REGISTERS_MM_diag,
	TP_REGISTERS_sTGC_lnk,
	TP_REGISTERS_sTGC_V6,
	TP_REGISTERS_sTGC_alg,
	TP_REGISTERS_sTGC_mrg,
	};

static const std::string registerFilesNamesArr[NUM_REGISTER_FILES] = {
	TP_NAME_NSW,
	TP_NAME_MM_lnk,
	TP_NAME_MM_addc,
	TP_NAME_MM,
	TP_NAME_MM_alg,
	TP_NAME_MM_diag,
	TP_NAME_sTGC_lnk,
	TP_NAME_sTGC_V6,
	TP_NAME_sTGC_alg,
	TP_NAME_sTGC_mrg,
	};

static const std::vector<std::string> registerFilesOrderArr[NUM_REGISTER_FILES] = {
	TP_REGISTERORDER_NSW,
	TP_REGISTERORDER_MM_lnk,
	TP_REGISTERORDER_MM_addc,
	TP_REGISTERORDER_MM,
	TP_REGISTERORDER_MM_alg,
	TP_REGISTERORDER_MM_diag,
	TP_REGISTERORDER_sTGC_lnk,
	TP_REGISTERORDER_sTGC_V6,
	TP_REGISTERORDER_sTGC_alg,
	TP_REGISTERORDER_sTGC_mrg,
	};

#endif // NSWCONFIGURATION_TP_I2CREGISTERMAPPINGS_H_