#ifndef NSWCONFIGURATION_TP_I2CREGISTERMAPPINGS_H_
#define NSWCONFIGURATION_TP_I2CREGISTERMAPPINGS_H_

/*
 * ----------------------------------------------------------------------------------
 * -- Company:  The Weizmann Institute of Science
 * -- Engineer: Noam Inbari (noam.inbari@weizmann.ac.il)
 * --
 * -- Edits and review: Lawrence Lee (lawrence.lee.jr@cern.ch)
 * --
 * ----------------------------------------------------------------------------------
 */

#include <map>
#include <vector>
#include <string>
#include <utility>

#include "NSWConfiguration/Types.h"


// -------------	NSW	-------------
static const char TP_NAME_NSW[] ="NSW";
static const i2c::AddressRegisterMap TP_REGISTERS_NSW = {
		{ "Firmware_version__time_stamp_00", { {"register", 32 } } },
		{ "EndcapSector_ID_01", { {"register", 5 } } },
		{ "XL1ID_02", { {"register", 8 } } },
		{ "Run_number_03", { {"register", 32 } } },
		{ "orbit_count_04", { {"register", 32 } } },
		{ "delta_theta_cut_05", { {"register", 5 } } },
		{ "mezz_PLL_reset_06", { {"register", 1 } } },
		{ "XVC_IP_low_byte_07", { {"register", 8 } } },
		{ "BC_offset_08", { {"register", 12 } } },
		{ "BC_L1A_window_09", { {"register", 3 } } },
		{ "BC_monitoring_window_0a", { {"register", 3 } } },
		{ "send_RODBUSY_on_0b", { {"register", 1 } } },
		{ "send_RODBUSY_off_0c", { {"register", 1 } } },
		{ "enable_LIA_data_output_0d", { {"register", 1 } } },
	};

// -------------	MM_lnk	-------------
static const char TP_NAME_MM_lnk[] ="MM_lnk";
static const i2c::AddressRegisterMap TP_REGISTERS_MM_lnk = {
		{ "gbt_link_alligned_00", { {"register", 32 } } },
		{ "gbt_pll_locked_01", { {"register", 9 } } },
		{ "gbt_pll_reset_02", { {"register", 9 } } },
		{ "gbt_hw_reset_03", { {"register", 1 } } },
		{ "gbt_link_error_04", { {"register", 32 } } },
		{ "gbt_channel_mask_05", { {"register", 32 } } },
	};

// -------------	MM_addc	-------------
static const char TP_NAME_MM_addc[] ="MM_addc";
static const i2c::AddressRegisterMap TP_REGISTERS_MM_addc = {
		{ "addc_packet_parity_error_00", { {"register", 32 } } },
		{ "addc_packet_bc_error_01", { {"register", 32 } } },
		{ "addc_packet_format_error_02", { {"register", 32 } } },
		{ "addc_packet_BC_offset_0_03", { {"register", 8 } } },
		{ "addc_packet_BC_offset_1_04", { {"register", 8 } } },
		{ "addc_packet_BC_offset_2_05", { {"register", 8 } } },
		{ "addc_packet_BC_offset_3_06", { {"register", 8 } } },
		{ "addc_packet_BC_offset_4_07", { {"register", 8 } } },
		{ "addc_packet_BC_offset_5_08", { {"register", 8 } } },
		{ "addc_packet_BC_offset_6_09", { {"register", 8 } } },
		{ "addc_packet_BC_offset_7_0a", { {"register", 8 } } },
		{ "addc_packet_BC_offset_8_0b", { {"register", 8 } } },
		{ "addc_packet_BC_offset_9_0c", { {"register", 8 } } },
		{ "addc_packet_BC_offset_10_0d", { {"register", 8 } } },
		{ "addc_packet_BC_offset_11_0e", { {"register", 8 } } },
		{ "addc_packet_BC_offset_12_0f", { {"register", 8 } } },
		{ "addc_packet_BC_offset_13_10", { {"register", 8 } } },
		{ "addc_packet_BC_offset_14_11", { {"register", 8 } } },
		{ "addc_packet_BC_offset_15_12", { {"register", 8 } } },
		{ "addc_packet_BC_offset_16_13", { {"register", 8 } } },
		{ "addc_packet_BC_offset_17_14", { {"register", 8 } } },
		{ "addc_packet_BC_offset_18_15", { {"register", 8 } } },
		{ "addc_packet_BC_offset_19_16", { {"register", 8 } } },
		{ "addc_packet_BC_offset_20_17", { {"register", 8 } } },
		{ "addc_packet_BC_offset_21_18", { {"register", 8 } } },
		{ "addc_packet_BC_offset_22_19", { {"register", 8 } } },
		{ "addc_packet_BC_offset_23_1a", { {"register", 8 } } },
		{ "addc_packet_BC_offset_24_1b", { {"register", 8 } } },
		{ "addc_packet_BC_offset_25_1c", { {"register", 8 } } },
		{ "addc_packet_BC_offset_26_1d", { {"register", 8 } } },
		{ "addc_packet_BC_offset_27_1e", { {"register", 8 } } },
		{ "addc_packet_BC_offset_28_1f", { {"register", 8 } } },
		{ "addc_packet_BC_offset_29_20", { {"register", 8 } } },
		{ "addc_packet_BC_offset_30_21", { {"register", 8 } } },
		{ "addc_packet_BC_offset_31_22", { {"register", 8 } } },
	};

// -------------	MM	-------------
static const char TP_NAME_MM[] ="MM";
static const i2c::AddressRegisterMap TP_REGISTERS_MM = {
		{ "tp_status_00", { {"register", 32 } } },
		{ "tp_local_bc_disable_01", { {"register", 1 } } },
		{ "tp_local_bc_reset_02", { {"register", 1 } } },
	};

// -------------	MM_alg	-------------
static const char TP_NAME_MM_alg[] ="MM_alg";
static const i2c::AddressRegisterMap TP_REGISTERS_MM_alg = {
		{ "algor_strip0_offset_0_00", { {"register", 16 } } },
		{ "algor_strip0_offset_1_01", { {"register", 16 } } },
		{ "algor_strip0_offset_2_02", { {"register", 16 } } },
		{ "algor_strip0_offset_3_03", { {"register", 16 } } },
		{ "algor_strip0_offset_4_04", { {"register", 16 } } },
		{ "algor_strip0_offset_5_05", { {"register", 16 } } },
		{ "algor_strip0_offset_6_06", { {"register", 16 } } },
		{ "algor_strip0_offset_7_07", { {"register", 16 } } },
		{ "algor_strip0_offset_8_08", { {"register", 16 } } },
		{ "algor_strip0_offset_9_09", { {"register", 16 } } },
		{ "algor_strip0_offset_10_0a", { {"register", 16 } } },
		{ "algor_strip0_offset_11_0b", { {"register", 16 } } },
		{ "algor_strip0_offset_12_0c", { {"register", 16 } } },
		{ "algor_strip0_offset_13_0d", { {"register", 16 } } },
		{ "algor_strip0_offset_14_0e", { {"register", 16 } } },
		{ "algor_strip0_offset_15_0f", { {"register", 16 } } },
		{ "algor_strip0_offset_16_10", { {"register", 16 } } },
		{ "algor_strip0_offset_17_11", { {"register", 16 } } },
		{ "algor_strip0_offset_18_12", { {"register", 16 } } },
		{ "algor_strip0_offset_19_13", { {"register", 16 } } },
		{ "algor_strip0_offset_20_14", { {"register", 16 } } },
		{ "algor_strip0_offset_21_15", { {"register", 16 } } },
		{ "algor_strip0_offset_22_16", { {"register", 16 } } },
		{ "algor_strip0_offset_23_17", { {"register", 16 } } },
		{ "algor_strip0_offset_24_18", { {"register", 16 } } },
		{ "algor_strip0_offset_25_19", { {"register", 16 } } },
		{ "algor_strip0_offset_26_1a", { {"register", 16 } } },
		{ "algor_strip0_offset_27_1b", { {"register", 16 } } },
		{ "algor_strip0_offset_28_1c", { {"register", 16 } } },
		{ "algor_strip0_offset_29_1d", { {"register", 16 } } },
		{ "algor_strip0_offset_30_1e", { {"register", 16 } } },
		{ "algor_strip0_offset_31_1f", { {"register", 16 } } },
		{ "algor_strip0_offset_32_20", { {"register", 16 } } },
		{ "algor_strip0_offset_33_21", { {"register", 16 } } },
		{ "algor_strip0_offset_34_22", { {"register", 16 } } },
		{ "algor_strip0_offset_35_23", { {"register", 16 } } },
		{ "algor_strip0_offset_36_24", { {"register", 16 } } },
		{ "algor_strip0_offset_37_25", { {"register", 16 } } },
		{ "algor_strip0_offset_38_26", { {"register", 16 } } },
		{ "algor_strip0_offset_39_27", { {"register", 16 } } },
		{ "algor_strip0_offset_40_28", { {"register", 16 } } },
		{ "algor_strip0_offset_41_29", { {"register", 16 } } },
		{ "algor_strip0_offset_42_2a", { {"register", 16 } } },
		{ "algor_strip0_offset_43_2b", { {"register", 16 } } },
		{ "algor_strip0_offset_44_2c", { {"register", 16 } } },
		{ "algor_strip0_offset_45_2d", { {"register", 16 } } },
		{ "algor_strip0_offset_46_2e", { {"register", 16 } } },
		{ "algor_strip0_offset_47_2f", { {"register", 16 } } },
		{ "algor_strip0_offset_48_30", { {"register", 16 } } },
		{ "algor_strip0_offset_49_31", { {"register", 16 } } },
		{ "algor_strip0_offset_50_32", { {"register", 16 } } },
		{ "algor_strip0_offset_51_33", { {"register", 16 } } },
		{ "algor_strip0_offset_52_34", { {"register", 16 } } },
		{ "algor_strip0_offset_53_35", { {"register", 16 } } },
		{ "algor_strip0_offset_54_36", { {"register", 16 } } },
		{ "algor_strip0_offset_55_37", { {"register", 16 } } },
		{ "algor_strip0_offset_56_38", { {"register", 16 } } },
		{ "algor_strip0_offset_57_39", { {"register", 16 } } },
		{ "algor_strip0_offset_58_3a", { {"register", 16 } } },
		{ "algor_strip0_offset_59_3b", { {"register", 16 } } },
		{ "algor_strip0_offset_60_3c", { {"register", 16 } } },
		{ "algor_strip0_offset_61_3d", { {"register", 16 } } },
		{ "algor_strip0_offset_62_3e", { {"register", 16 } } },
		{ "algor_strip0_offset_63_3f", { {"register", 16 } } },
		{ "algor_strip0_offset_64_40", { {"register", 16 } } },
		{ "algor_strip0_offset_65_41", { {"register", 16 } } },
		{ "algor_strip0_offset_66_42", { {"register", 16 } } },
		{ "algor_strip0_offset_67_43", { {"register", 16 } } },
		{ "algor_strip0_offset_68_44", { {"register", 16 } } },
		{ "algor_strip0_offset_69_45", { {"register", 16 } } },
		{ "algor_strip0_offset_70_46", { {"register", 16 } } },
		{ "algor_strip0_offset_71_47", { {"register", 16 } } },
		{ "algor_strip0_offset_72_48", { {"register", 16 } } },
		{ "algor_strip0_offset_73_49", { {"register", 16 } } },
		{ "algor_strip0_offset_74_4a", { {"register", 16 } } },
		{ "algor_strip0_offset_75_4b", { {"register", 16 } } },
		{ "algor_strip0_offset_76_4c", { {"register", 16 } } },
		{ "algor_strip0_offset_77_4d", { {"register", 16 } } },
		{ "algor_strip0_offset_78_4e", { {"register", 16 } } },
		{ "algor_strip0_offset_79_4f", { {"register", 16 } } },
		{ "algor_strip0_offset_80_50", { {"register", 16 } } },
		{ "algor_strip0_offset_81_51", { {"register", 16 } } },
		{ "algor_strip0_offset_82_52", { {"register", 16 } } },
		{ "algor_strip0_offset_83_53", { {"register", 16 } } },
		{ "algor_strip0_offset_84_54", { {"register", 16 } } },
		{ "algor_strip0_offset_85_55", { {"register", 16 } } },
		{ "algor_strip0_offset_86_56", { {"register", 16 } } },
		{ "algor_strip0_offset_87_57", { {"register", 16 } } },
		{ "algor_strip0_offset_88_58", { {"register", 16 } } },
		{ "algor_strip0_offset_89_59", { {"register", 16 } } },
		{ "algor_strip0_offset_90_5a", { {"register", 16 } } },
		{ "algor_strip0_offset_91_5b", { {"register", 16 } } },
		{ "algor_strip0_offset_92_5c", { {"register", 16 } } },
		{ "algor_strip0_offset_93_5d", { {"register", 16 } } },
		{ "algor_strip0_offset_94_5e", { {"register", 16 } } },
		{ "algor_strip0_offset_95_5f", { {"register", 16 } } },
		{ "algor_strip0_offset_96_60", { {"register", 16 } } },
		{ "algor_strip0_offset_97_61", { {"register", 16 } } },
		{ "algor_strip0_offset_98_62", { {"register", 16 } } },
		{ "algor_strip0_offset_99_63", { {"register", 16 } } },
		{ "algor_strip0_offset_100_64", { {"register", 16 } } },
		{ "algor_strip0_offset_101_65", { {"register", 16 } } },
		{ "algor_strip0_offset_102_66", { {"register", 16 } } },
		{ "algor_strip0_offset_103_67", { {"register", 16 } } },
		{ "algor_strip0_offset_104_68", { {"register", 16 } } },
		{ "algor_strip0_offset_105_69", { {"register", 16 } } },
		{ "algor_strip0_offset_106_6a", { {"register", 16 } } },
		{ "algor_strip0_offset_107_6b", { {"register", 16 } } },
		{ "algor_strip0_offset_108_6c", { {"register", 16 } } },
		{ "algor_strip0_offset_109_6d", { {"register", 16 } } },
		{ "algor_strip0_offset_110_6e", { {"register", 16 } } },
		{ "algor_strip0_offset_111_6f", { {"register", 16 } } },
		{ "algor_strip0_offset_112_70", { {"register", 16 } } },
		{ "algor_strip0_offset_113_71", { {"register", 16 } } },
		{ "algor_strip0_offset_114_72", { {"register", 16 } } },
		{ "algor_strip0_offset_115_73", { {"register", 16 } } },
		{ "algor_strip0_offset_116_74", { {"register", 16 } } },
		{ "algor_strip0_offset_117_75", { {"register", 16 } } },
		{ "algor_strip0_offset_118_76", { {"register", 16 } } },
		{ "algor_strip0_offset_119_77", { {"register", 16 } } },
		{ "algor_strip0_offset_120_78", { {"register", 16 } } },
		{ "algor_strip0_offset_121_79", { {"register", 16 } } },
		{ "algor_strip0_offset_122_7a", { {"register", 16 } } },
		{ "algor_strip0_offset_123_7b", { {"register", 16 } } },
		{ "algor_strip0_offset_124_7c", { {"register", 16 } } },
		{ "algor_strip0_offset_125_7d", { {"register", 16 } } },
		{ "algor_strip0_offset_126_7e", { {"register", 16 } } },
		{ "algor_strip0_offset_127_7f", { {"register", 16 } } },
		{ "algor_plane_offset_0_80", { {"register", 16 } } },
		{ "algor_plane_offset_1_81", { {"register", 16 } } },
		{ "algor_plane_offset_2_82", { {"register", 16 } } },
		{ "algor_plane_offset_3_83", { {"register", 16 } } },
		{ "algor_plane_offset_4_84", { {"register", 16 } } },
		{ "algor_plane_offset_5_85", { {"register", 16 } } },
		{ "algor_plane_offset_6_86", { {"register", 16 } } },
		{ "algor_plane_offset_7_87", { {"register", 16 } } },
		{ "algor_plane_offset_8_88", { {"register", 16 } } },
		{ "algor_plane_offset_9_89", { {"register", 16 } } },
		{ "algor_plane_offset_10_8a", { {"register", 16 } } },
		{ "algor_plane_offset_11_8b", { {"register", 16 } } },
		{ "algor_plane_offset_12_8c", { {"register", 16 } } },
		{ "algor_plane_offset_13_8d", { {"register", 16 } } },
		{ "algor_plane_offset_14_8e", { {"register", 16 } } },
		{ "algor_plane_offset_15_8f", { {"register", 16 } } },
		{ "algor_plane_offset_16_90", { {"register", 16 } } },
		{ "algor_plane_offset_17_91", { {"register", 16 } } },
		{ "algor_plane_offset_18_92", { {"register", 16 } } },
		{ "algor_plane_offset_19_93", { {"register", 16 } } },
		{ "algor_plane_offset_20_94", { {"register", 16 } } },
		{ "algor_plane_offset_21_95", { {"register", 16 } } },
		{ "algor_plane_offset_22_96", { {"register", 16 } } },
		{ "algor_plane_offset_23_97", { {"register", 16 } } },
		{ "algor_plane_offset_24_98", { {"register", 16 } } },
		{ "algor_plane_offset_25_99", { {"register", 16 } } },
		{ "algor_plane_offset_26_9a", { {"register", 16 } } },
		{ "algor_plane_offset_27_9b", { {"register", 16 } } },
		{ "algor_plane_offset_28_9c", { {"register", 16 } } },
		{ "algor_plane_offset_29_9d", { {"register", 16 } } },
		{ "algor_plane_offset_30_9e", { {"register", 16 } } },
		{ "algor_plane_offset_31_9f", { {"register", 16 } } },
		{ "algor_plane_offset_32_a0", { {"register", 16 } } },
		{ "algor_plane_offset_33_a1", { {"register", 16 } } },
		{ "algor_plane_offset_34_a2", { {"register", 16 } } },
		{ "algor_plane_offset_35_a3", { {"register", 16 } } },
		{ "algor_plane_offset_36_a4", { {"register", 16 } } },
		{ "algor_plane_offset_37_a5", { {"register", 16 } } },
		{ "algor_plane_offset_38_a6", { {"register", 16 } } },
		{ "algor_plane_offset_39_a7", { {"register", 16 } } },
		{ "algor_plane_offset_40_a8", { {"register", 16 } } },
		{ "algor_plane_offset_41_a9", { {"register", 16 } } },
		{ "algor_plane_offset_42_aa", { {"register", 16 } } },
		{ "algor_plane_offset_43_ab", { {"register", 16 } } },
		{ "algor_plane_offset_44_ac", { {"register", 16 } } },
		{ "algor_plane_offset_45_ad", { {"register", 16 } } },
		{ "algor_plane_offset_46_ae", { {"register", 16 } } },
		{ "algor_plane_offset_47_af", { {"register", 16 } } },
		{ "algor_plane_offset_48_b0", { {"register", 16 } } },
		{ "algor_plane_offset_49_b1", { {"register", 16 } } },
		{ "algor_plane_offset_50_b2", { {"register", 16 } } },
		{ "algor_plane_offset_51_b3", { {"register", 16 } } },
		{ "algor_plane_offset_52_b4", { {"register", 16 } } },
		{ "algor_plane_offset_53_b5", { {"register", 16 } } },
		{ "algor_plane_offset_54_b6", { {"register", 16 } } },
		{ "algor_plane_offset_55_b7", { {"register", 16 } } },
		{ "algor_plane_offset_56_b8", { {"register", 16 } } },
		{ "algor_plane_offset_57_b9", { {"register", 16 } } },
		{ "algor_plane_offset_58_ba", { {"register", 16 } } },
		{ "algor_plane_offset_59_bb", { {"register", 16 } } },
		{ "algor_plane_offset_60_bc", { {"register", 16 } } },
		{ "algor_plane_offset_61_bd", { {"register", 16 } } },
		{ "algor_plane_offset_62_be", { {"register", 16 } } },
		{ "algor_plane_offset_63_bf", { {"register", 16 } } },
		{ "algor_plane_offset_64_c0", { {"register", 16 } } },
		{ "algor_plane_offset_65_c1", { {"register", 16 } } },
		{ "algor_plane_offset_66_c2", { {"register", 16 } } },
		{ "algor_plane_offset_67_c3", { {"register", 16 } } },
		{ "algor_plane_offset_68_c4", { {"register", 16 } } },
		{ "algor_plane_offset_69_c5", { {"register", 16 } } },
		{ "algor_plane_offset_70_c6", { {"register", 16 } } },
		{ "algor_plane_offset_71_c7", { {"register", 16 } } },
		{ "algor_plane_offset_72_c8", { {"register", 16 } } },
		{ "algor_plane_offset_73_c9", { {"register", 16 } } },
		{ "algor_plane_offset_74_ca", { {"register", 16 } } },
		{ "algor_plane_offset_75_cb", { {"register", 16 } } },
		{ "algor_plane_offset_76_cc", { {"register", 16 } } },
		{ "algor_plane_offset_77_cd", { {"register", 16 } } },
		{ "algor_plane_offset_78_ce", { {"register", 16 } } },
		{ "algor_plane_offset_79_cf", { {"register", 16 } } },
		{ "algor_plane_offset_80_d0", { {"register", 16 } } },
		{ "algor_plane_offset_81_d1", { {"register", 16 } } },
		{ "algor_plane_offset_82_d2", { {"register", 16 } } },
		{ "algor_plane_offset_83_d3", { {"register", 16 } } },
		{ "algor_plane_offset_84_d4", { {"register", 16 } } },
		{ "algor_plane_offset_85_d5", { {"register", 16 } } },
		{ "algor_plane_offset_86_d6", { {"register", 16 } } },
		{ "algor_plane_offset_87_d7", { {"register", 16 } } },
		{ "algor_plane_offset_88_d8", { {"register", 16 } } },
		{ "algor_plane_offset_89_d9", { {"register", 16 } } },
		{ "algor_plane_offset_90_da", { {"register", 16 } } },
		{ "algor_plane_offset_91_db", { {"register", 16 } } },
		{ "algor_plane_offset_92_dc", { {"register", 16 } } },
		{ "algor_plane_offset_93_dd", { {"register", 16 } } },
		{ "algor_plane_offset_94_de", { {"register", 16 } } },
		{ "algor_plane_offset_95_df", { {"register", 16 } } },
		{ "algor_plane_offset_96_e0", { {"register", 16 } } },
		{ "algor_plane_offset_97_e1", { {"register", 16 } } },
		{ "algor_plane_offset_98_e2", { {"register", 16 } } },
		{ "algor_plane_offset_99_e3", { {"register", 16 } } },
		{ "algor_plane_offset_100_e4", { {"register", 16 } } },
		{ "algor_plane_offset_101_e5", { {"register", 16 } } },
		{ "algor_plane_offset_102_e6", { {"register", 16 } } },
		{ "algor_plane_offset_103_e7", { {"register", 16 } } },
		{ "algor_plane_offset_104_e8", { {"register", 16 } } },
		{ "algor_plane_offset_105_e9", { {"register", 16 } } },
		{ "algor_plane_offset_106_ea", { {"register", 16 } } },
		{ "algor_plane_offset_107_eb", { {"register", 16 } } },
		{ "algor_plane_offset_108_ec", { {"register", 16 } } },
		{ "algor_plane_offset_109_ed", { {"register", 16 } } },
		{ "algor_plane_offset_110_ee", { {"register", 16 } } },
		{ "algor_plane_offset_111_ef", { {"register", 16 } } },
		{ "algor_plane_offset_112_f0", { {"register", 16 } } },
		{ "algor_plane_offset_113_f1", { {"register", 16 } } },
		{ "algor_plane_offset_114_f2", { {"register", 16 } } },
		{ "algor_plane_offset_115_f3", { {"register", 16 } } },
		{ "algor_plane_offset_116_f4", { {"register", 16 } } },
		{ "algor_plane_offset_117_f5", { {"register", 16 } } },
		{ "algor_plane_offset_118_f6", { {"register", 16 } } },
		{ "algor_plane_offset_119_f7", { {"register", 16 } } },
		{ "algor_plane_offset_120_f8", { {"register", 16 } } },
		{ "algor_plane_offset_121_f9", { {"register", 16 } } },
		{ "algor_plane_offset_122_fa", { {"register", 16 } } },
		{ "algor_plane_offset_123_fb", { {"register", 16 } } },
		{ "algor_plane_offset_124_fc", { {"register", 16 } } },
		{ "algor_plane_offset_125_fd", { {"register", 16 } } },
		{ "algor_plane_offset_126_fe", { {"register", 16 } } },
		{ "algor_plane_offset_127_ff", { {"register", 16 } } },
		{ "algor_plane_offset_recip_0_100", { {"register", 16 } } },
		{ "algor_plane_offset_recip_1_101", { {"register", 16 } } },
		{ "algor_plane_offset_recip_2_102", { {"register", 16 } } },
		{ "algor_plane_offset_recip_3_103", { {"register", 16 } } },
		{ "algor_plane_offset_recip_4_104", { {"register", 16 } } },
		{ "algor_plane_offset_recip_5_105", { {"register", 16 } } },
		{ "algor_plane_offset_recip_6_106", { {"register", 16 } } },
		{ "algor_plane_offset_recip_7_107", { {"register", 16 } } },
		{ "algor_plane_offset_recip_8_108", { {"register", 16 } } },
		{ "algor_plane_offset_recip_9_109", { {"register", 16 } } },
		{ "algor_plane_offset_recip_10_10a", { {"register", 16 } } },
		{ "algor_plane_offset_recip_11_10b", { {"register", 16 } } },
		{ "algor_plane_offset_recip_12_10c", { {"register", 16 } } },
		{ "algor_plane_offset_recip_13_10d", { {"register", 16 } } },
		{ "algor_plane_offset_recip_14_10e", { {"register", 16 } } },
		{ "algor_plane_offset_recip_15_10f", { {"register", 16 } } },
		{ "algor_plane_offset_recip_16_110", { {"register", 16 } } },
		{ "algor_plane_offset_recip_17_111", { {"register", 16 } } },
		{ "algor_plane_offset_recip_18_112", { {"register", 16 } } },
		{ "algor_plane_offset_recip_19_113", { {"register", 16 } } },
		{ "algor_plane_offset_recip_20_114", { {"register", 16 } } },
		{ "algor_plane_offset_recip_21_115", { {"register", 16 } } },
		{ "algor_plane_offset_recip_22_116", { {"register", 16 } } },
		{ "algor_plane_offset_recip_23_117", { {"register", 16 } } },
		{ "algor_plane_offset_recip_24_118", { {"register", 16 } } },
		{ "algor_plane_offset_recip_25_119", { {"register", 16 } } },
		{ "algor_plane_offset_recip_26_11a", { {"register", 16 } } },
		{ "algor_plane_offset_recip_27_11b", { {"register", 16 } } },
		{ "algor_plane_offset_recip_28_11c", { {"register", 16 } } },
		{ "algor_plane_offset_recip_29_11d", { {"register", 16 } } },
		{ "algor_plane_offset_recip_30_11e", { {"register", 16 } } },
		{ "algor_plane_offset_recip_31_11f", { {"register", 16 } } },
		{ "algor_plane_offset_recip_32_120", { {"register", 16 } } },
		{ "algor_plane_offset_recip_33_121", { {"register", 16 } } },
		{ "algor_plane_offset_recip_34_122", { {"register", 16 } } },
		{ "algor_plane_offset_recip_35_123", { {"register", 16 } } },
		{ "algor_plane_offset_recip_36_124", { {"register", 16 } } },
		{ "algor_plane_offset_recip_37_125", { {"register", 16 } } },
		{ "algor_plane_offset_recip_38_126", { {"register", 16 } } },
		{ "algor_plane_offset_recip_39_127", { {"register", 16 } } },
		{ "algor_plane_offset_recip_40_128", { {"register", 16 } } },
		{ "algor_plane_offset_recip_41_129", { {"register", 16 } } },
		{ "algor_plane_offset_recip_42_12a", { {"register", 16 } } },
		{ "algor_plane_offset_recip_43_12b", { {"register", 16 } } },
		{ "algor_plane_offset_recip_44_12c", { {"register", 16 } } },
		{ "algor_plane_offset_recip_45_12d", { {"register", 16 } } },
		{ "algor_plane_offset_recip_46_12e", { {"register", 16 } } },
		{ "algor_plane_offset_recip_47_12f", { {"register", 16 } } },
		{ "algor_plane_offset_recip_48_130", { {"register", 16 } } },
		{ "algor_plane_offset_recip_49_131", { {"register", 16 } } },
		{ "algor_plane_offset_recip_50_132", { {"register", 16 } } },
		{ "algor_plane_offset_recip_51_133", { {"register", 16 } } },
		{ "algor_plane_offset_recip_52_134", { {"register", 16 } } },
		{ "algor_plane_offset_recip_53_135", { {"register", 16 } } },
		{ "algor_plane_offset_recip_54_136", { {"register", 16 } } },
		{ "algor_plane_offset_recip_55_137", { {"register", 16 } } },
		{ "algor_plane_offset_recip_56_138", { {"register", 16 } } },
		{ "algor_plane_offset_recip_57_139", { {"register", 16 } } },
		{ "algor_plane_offset_recip_58_13a", { {"register", 16 } } },
		{ "algor_plane_offset_recip_59_13b", { {"register", 16 } } },
		{ "algor_plane_offset_recip_60_13c", { {"register", 16 } } },
		{ "algor_plane_offset_recip_61_13d", { {"register", 16 } } },
		{ "algor_plane_offset_recip_62_13e", { {"register", 16 } } },
		{ "algor_plane_offset_recip_63_13f", { {"register", 16 } } },
		{ "algor_plane_offset_recip_64_140", { {"register", 16 } } },
		{ "algor_plane_offset_recip_65_141", { {"register", 16 } } },
		{ "algor_plane_offset_recip_66_142", { {"register", 16 } } },
		{ "algor_plane_offset_recip_67_143", { {"register", 16 } } },
		{ "algor_plane_offset_recip_68_144", { {"register", 16 } } },
		{ "algor_plane_offset_recip_69_145", { {"register", 16 } } },
		{ "algor_plane_offset_recip_70_146", { {"register", 16 } } },
		{ "algor_plane_offset_recip_71_147", { {"register", 16 } } },
		{ "algor_plane_offset_recip_72_148", { {"register", 16 } } },
		{ "algor_plane_offset_recip_73_149", { {"register", 16 } } },
		{ "algor_plane_offset_recip_74_14a", { {"register", 16 } } },
		{ "algor_plane_offset_recip_75_14b", { {"register", 16 } } },
		{ "algor_plane_offset_recip_76_14c", { {"register", 16 } } },
		{ "algor_plane_offset_recip_77_14d", { {"register", 16 } } },
		{ "algor_plane_offset_recip_78_14e", { {"register", 16 } } },
		{ "algor_plane_offset_recip_79_14f", { {"register", 16 } } },
		{ "algor_plane_offset_recip_80_150", { {"register", 16 } } },
		{ "algor_plane_offset_recip_81_151", { {"register", 16 } } },
		{ "algor_plane_offset_recip_82_152", { {"register", 16 } } },
		{ "algor_plane_offset_recip_83_153", { {"register", 16 } } },
		{ "algor_plane_offset_recip_84_154", { {"register", 16 } } },
		{ "algor_plane_offset_recip_85_155", { {"register", 16 } } },
		{ "algor_plane_offset_recip_86_156", { {"register", 16 } } },
		{ "algor_plane_offset_recip_87_157", { {"register", 16 } } },
		{ "algor_plane_offset_recip_88_158", { {"register", 16 } } },
		{ "algor_plane_offset_recip_89_159", { {"register", 16 } } },
		{ "algor_plane_offset_recip_90_15a", { {"register", 16 } } },
		{ "algor_plane_offset_recip_91_15b", { {"register", 16 } } },
		{ "algor_plane_offset_recip_92_15c", { {"register", 16 } } },
		{ "algor_plane_offset_recip_93_15d", { {"register", 16 } } },
		{ "algor_plane_offset_recip_94_15e", { {"register", 16 } } },
		{ "algor_plane_offset_recip_95_15f", { {"register", 16 } } },
		{ "algor_plane_offset_recip_96_160", { {"register", 16 } } },
		{ "algor_plane_offset_recip_97_161", { {"register", 16 } } },
		{ "algor_plane_offset_recip_98_162", { {"register", 16 } } },
		{ "algor_plane_offset_recip_99_163", { {"register", 16 } } },
		{ "algor_plane_offset_recip_100_164", { {"register", 16 } } },
		{ "algor_plane_offset_recip_101_165", { {"register", 16 } } },
		{ "algor_plane_offset_recip_102_166", { {"register", 16 } } },
		{ "algor_plane_offset_recip_103_167", { {"register", 16 } } },
		{ "algor_plane_offset_recip_104_168", { {"register", 16 } } },
		{ "algor_plane_offset_recip_105_169", { {"register", 16 } } },
		{ "algor_plane_offset_recip_106_16a", { {"register", 16 } } },
		{ "algor_plane_offset_recip_107_16b", { {"register", 16 } } },
		{ "algor_plane_offset_recip_108_16c", { {"register", 16 } } },
		{ "algor_plane_offset_recip_109_16d", { {"register", 16 } } },
		{ "algor_plane_offset_recip_110_16e", { {"register", 16 } } },
		{ "algor_plane_offset_recip_111_16f", { {"register", 16 } } },
		{ "algor_plane_offset_recip_112_170", { {"register", 16 } } },
		{ "algor_plane_offset_recip_113_171", { {"register", 16 } } },
		{ "algor_plane_offset_recip_114_172", { {"register", 16 } } },
		{ "algor_plane_offset_recip_115_173", { {"register", 16 } } },
		{ "algor_plane_offset_recip_116_174", { {"register", 16 } } },
		{ "algor_plane_offset_recip_117_175", { {"register", 16 } } },
		{ "algor_plane_offset_recip_118_176", { {"register", 16 } } },
		{ "algor_plane_offset_recip_119_177", { {"register", 16 } } },
		{ "algor_plane_offset_recip_120_178", { {"register", 16 } } },
		{ "algor_plane_offset_recip_121_179", { {"register", 16 } } },
		{ "algor_plane_offset_recip_122_17a", { {"register", 16 } } },
		{ "algor_plane_offset_recip_123_17b", { {"register", 16 } } },
		{ "algor_plane_offset_recip_124_17c", { {"register", 16 } } },
		{ "algor_plane_offset_recip_125_17d", { {"register", 16 } } },
		{ "algor_plane_offset_recip_126_17e", { {"register", 16 } } },
		{ "algor_plane_offset_recip_127_17f", { {"register", 16 } } },
		{ "algor_mmfe8_invert_180", { {"register", 32 } } },
		{ "algor_roi_map_181", { {"register", 16 } } },
		{ "algor_roi_map_182_rdEn", { {"register", 1 } } },
		{ "algor_roi_map_182_wrEn", { {"register", 1 } } },
		{ "algor_roi_map_addr_184", { {"register", 16 } } },
		{ "algor_mxlocal_parameters_185", { {"register", 16 } } },
		{ "algor_mxlocal_parameters_186_rdEn", { {"register", 1 } } },
		{ "algor_mxlocal_parameters_186_wrEn", { {"register", 1 } } },
		{ "algor_mxlocal_parameters_addr_188", { {"register", 16 } } },
		{ "algor_dtheta_parameters_189", { {"register", 16 } } },
		{ "algor_dtheta_parameters_18a_rdEn", { {"register", 1 } } },
		{ "algor_dtheta_parameters_18a_wrEn", { {"register", 1 } } },
		{ "algor_dtheta_parameters_addr_18c", { {"register", 16 } } },
		{ "algor_region_mask_18d", { {"register", 16 } } },
	};

// -------------	MM_diag	-------------
static const char TP_NAME_MM_diag[] ="MM_diag";
static const i2c::AddressRegisterMap TP_REGISTERS_MM_diag = {
		{ "diag_fifo_ef_00", { {"register", 32 } } },
		{ "diag_fifo_of_01", { {"register", 32 } } },
		{ "diag_gbt_loopback_data_02", { {"register", 32 } } },
		{ "diag_gbt_loopback_data_03_rdEn", { {"register", 1 } } },
		{ "diag_gbt_loopback_data_03_wrEn", { {"register", 1 } } },
		{ "diag_gbt_loopback_data_05", { {"register", 32 } } },
	};

// -------------	sTGC_lnk	-------------
static const char TP_NAME_sTGC_lnk[] ="sTGC_lnk";
static const i2c::AddressRegisterMap TP_REGISTERS_sTGC_lnk = {
		{ "GTH_MMC_RX_lock_00", { {"register", 3 } } },
		{ "GTH_TX_FSM_RESET_DONE_01", { {"register", 36 } } },
		{ "GTH_RX_FSM_RESET_DONE_02", { {"register", 36 } } },
		{ "GTH_cpllfbclklost_03", { {"register", 36 } } },
		{ "GTH_cplllock_04", { {"register", 36 } } },
		{ "GTH_rxresetdone_05", { {"register", 36 } } },
		{ "GTH_txresetdone_06", { {"register", 36 } } },
		{ "GTH_QPLLLOCK_07", { {"register", 12 } } },
		{ "GTH_QPLLREFCLKLOST_08", { {"register", 12 } } },
		{ "GTH_QPLLRESET_09", { {"register", 12 } } },
		{ "GlobalReset_0a", { {"register", 1 } } },
		{ "GTH_rxuserrdy_0b", { {"register", 36 } } },
		{ "GTH_txuserrdy_0c", { {"register", 36 } } },
		{ "GTH_cpllreset_0d", { {"register", 36 } } },
		{ "GTH_gtrxreset_0e", { {"register", 36 } } },
		{ "GTH_gttxreset_0f", { {"register", 36 } } },
		{ "V7_ANLINK_RX_WR_EN_10", { {"register", 1 } } },
		{ "V7_ANLINK_RX_RD_EN_11", { {"register", 1 } } },
		{ "V7_ANLINK_TX_WR_EN_12", { {"register", 1 } } },
		{ "V7_ANLINK_TX_RD_EN_13", { {"register", 1 } } },
	};

// -------------	sTGC_V6	-------------
static const char TP_NAME_sTGC_V6[] ="sTGC_V6";
static const i2c::AddressRegisterMap TP_REGISTERS_sTGC_V6 = {
		{ "V6_global_RST_00", { {"register", 1 } } },
		{ "V6_UDP_GTX_RST_01", { {"register", 1 } } },
		{ "V6_ANLINK_RX_WR_EN_02", { {"register", 1 } } },
		{ "V6_ANLINK_RX_RD_EN_03", { {"register", 1 } } },
		{ "V6_ANLINK_TX_WR_EN_04", { {"register", 1 } } },
		{ "V6_ANLINK_TX_RD_EN_05", { {"register", 1 } } },
	};

// -------------	sTGC_alg	-------------
static const char TP_NAME_sTGC_alg[] ="sTGC_alg";
static const i2c::AddressRegisterMap TP_REGISTERS_sTGC_alg = {
		{ "radial_offset_0_00", { {"register", 12 } } },
		{ "radial_offset_1_01", { {"register", 12 } } },
		{ "radial_offset_2_02", { {"register", 12 } } },
		{ "radial_offset_3_03", { {"register", 12 } } },
		{ "radial_offset_4_04", { {"register", 12 } } },
		{ "radial_offset_5_05", { {"register", 12 } } },
		{ "radial_offset_6_06", { {"register", 12 } } },
		{ "radial_offset_7_07", { {"register", 12 } } },
		{ "radial_offset_8_08", { {"register", 12 } } },
		{ "radial_offset_9_09", { {"register", 12 } } },
		{ "radial_offset_10_0a", { {"register", 12 } } },
		{ "radial_offset_11_0b", { {"register", 12 } } },
		{ "radial_offset_12_0c", { {"register", 12 } } },
		{ "radial_offset_13_0d", { {"register", 12 } } },
		{ "radial_offset_14_0e", { {"register", 12 } } },
		{ "radial_offset_15_0f", { {"register", 12 } } },
		{ "radial_offset_16_10", { {"register", 12 } } },
		{ "radial_offset_17_11", { {"register", 12 } } },
		{ "radial_offset_18_12", { {"register", 12 } } },
		{ "radial_offset_19_13", { {"register", 12 } } },
		{ "radial_offset_20_14", { {"register", 12 } } },
		{ "radial_offset_21_15", { {"register", 12 } } },
		{ "radial_offset_22_16", { {"register", 12 } } },
		{ "radial_offset_23_17", { {"register", 12 } } },
		{ "plane_offset_0_18", { {"register", 16 } } },
		{ "plane_offset_1_19", { {"register", 16 } } },
		{ "plane_offset_2_1a", { {"register", 16 } } },
		{ "plane_offset_3_1b", { {"register", 16 } } },
		{ "plane_offset_4_1c", { {"register", 16 } } },
		{ "plane_offset_5_1d", { {"register", 16 } } },
		{ "plane_offset_6_1e", { {"register", 16 } } },
		{ "plane_offset_7_1f", { {"register", 16 } } },
		{ "plane_offset_8_20", { {"register", 16 } } },
		{ "plane_offset_9_21", { {"register", 16 } } },
		{ "plane_offset_10_22", { {"register", 16 } } },
		{ "plane_offset_11_23", { {"register", 16 } } },
		{ "plane_offset_12_24", { {"register", 16 } } },
		{ "plane_offset_13_25", { {"register", 16 } } },
		{ "plane_offset_14_26", { {"register", 16 } } },
		{ "plane_offset_15_27", { {"register", 16 } } },
		{ "plane_offset_16_28", { {"register", 16 } } },
		{ "plane_offset_17_29", { {"register", 16 } } },
		{ "plane_offset_18_2a", { {"register", 16 } } },
		{ "plane_offset_19_2b", { {"register", 16 } } },
		{ "plane_offset_20_2c", { {"register", 16 } } },
		{ "plane_offset_21_2d", { {"register", 16 } } },
		{ "plane_offset_22_2e", { {"register", 16 } } },
		{ "plane_offset_23_2f", { {"register", 16 } } },
		{ "max_cluster_size_30", { {"register", 4 } } },
		{ "min_cluster_size_31", { {"register", 4 } } },
		{ "charge_thresh_cluster_0_32", { {"register", 6 } } },
		{ "charge_thresh_cluster_1_33", { {"register", 6 } } },
		{ "charge_thresh_cluster_2_34", { {"register", 6 } } },
		{ "charge_thresh_cluster_3_35", { {"register", 6 } } },
		{ "charge_thresh_cluster_4_36", { {"register", 6 } } },
		{ "charge_thresh_cluster_5_37", { {"register", 6 } } },
		{ "charge_thresh_cluster_6_38", { {"register", 6 } } },
		{ "charge_thresh_cluster_7_39", { {"register", 6 } } },
		{ "charge_thresh_cluster_8_3a", { {"register", 6 } } },
		{ "charge_thresh_cluster_9_3b", { {"register", 6 } } },
		{ "charge_thresh_cluster_10_3c", { {"register", 6 } } },
		{ "charge_thresh_cluster_11_3d", { {"register", 6 } } },
		{ "charge_thresh_cluster_12_3e", { {"register", 6 } } },
		{ "charge_thresh_cluster_13_3f", { {"register", 6 } } },
		{ "charge_thresh_cluster_14_40", { {"register", 6 } } },
		{ "charge_thresh_cluster_15_41", { {"register", 6 } } },
		{ "charge_thresh_cluster_16_42", { {"register", 6 } } },
		{ "charge_thresh_cluster_17_43", { {"register", 6 } } },
		{ "charge_thresh_cluster_18_44", { {"register", 6 } } },
		{ "charge_thresh_cluster_19_45", { {"register", 6 } } },
		{ "charge_thresh_cluster_20_46", { {"register", 6 } } },
		{ "charge_thresh_cluster_21_47", { {"register", 6 } } },
		{ "charge_thresh_cluster_22_48", { {"register", 6 } } },
		{ "charge_thresh_cluster_23_49", { {"register", 6 } } },
		{ "charge_thresh_centroid_0_4a", { {"register", 6 } } },
		{ "charge_thresh_centroid_1_4b", { {"register", 6 } } },
		{ "charge_thresh_centroid_2_4c", { {"register", 6 } } },
		{ "charge_thresh_centroid_3_4d", { {"register", 6 } } },
		{ "charge_thresh_centroid_4_4e", { {"register", 6 } } },
		{ "charge_thresh_centroid_5_4f", { {"register", 6 } } },
		{ "charge_thresh_centroid_6_50", { {"register", 6 } } },
		{ "charge_thresh_centroid_7_51", { {"register", 6 } } },
		{ "charge_thresh_centroid_8_52", { {"register", 6 } } },
		{ "charge_thresh_centroid_9_53", { {"register", 6 } } },
		{ "charge_thresh_centroid_10_54", { {"register", 6 } } },
		{ "charge_thresh_centroid_11_55", { {"register", 6 } } },
		{ "charge_thresh_centroid_12_56", { {"register", 6 } } },
		{ "charge_thresh_centroid_13_57", { {"register", 6 } } },
		{ "charge_thresh_centroid_14_58", { {"register", 6 } } },
		{ "charge_thresh_centroid_15_59", { {"register", 6 } } },
		{ "charge_thresh_centroid_16_5a", { {"register", 6 } } },
		{ "charge_thresh_centroid_17_5b", { {"register", 6 } } },
		{ "charge_thresh_centroid_18_5c", { {"register", 6 } } },
		{ "charge_thresh_centroid_19_5d", { {"register", 6 } } },
		{ "charge_thresh_centroid_20_5e", { {"register", 6 } } },
		{ "charge_thresh_centroid_21_5f", { {"register", 6 } } },
		{ "charge_thresh_centroid_22_60", { {"register", 6 } } },
		{ "charge_thresh_centroid_23_61", { {"register", 6 } } },
		{ "strip_dir_0_62", { {"register", 1 } } },
		{ "strip_dir_1_63", { {"register", 1 } } },
		{ "strip_dir_2_64", { {"register", 1 } } },
		{ "strip_dir_3_65", { {"register", 1 } } },
		{ "strip_dir_4_66", { {"register", 1 } } },
		{ "strip_dir_5_67", { {"register", 1 } } },
		{ "strip_dir_6_68", { {"register", 1 } } },
		{ "strip_dir_7_69", { {"register", 1 } } },
		{ "R_offset_0_6a", { {"register", 16 } } },
		{ "R_offset_1_6b", { {"register", 16 } } },
		{ "R_offset_2_6c", { {"register", 16 } } },
		{ "R_offset_3_6d", { {"register", 16 } } },
		{ "R_offset_4_6e", { {"register", 16 } } },
		{ "R_offset_5_6f", { {"register", 16 } } },
		{ "R_offset_6_70", { {"register", 16 } } },
		{ "R_offset_7_71", { {"register", 16 } } },
		{ "R_offset_8_72", { {"register", 16 } } },
		{ "R_offset_9_73", { {"register", 16 } } },
		{ "R_offset_10_74", { {"register", 16 } } },
		{ "R_offset_11_75", { {"register", 16 } } },
		{ "R_offset_12_76", { {"register", 16 } } },
		{ "R_offset_13_77", { {"register", 16 } } },
		{ "R_offset_14_78", { {"register", 16 } } },
		{ "R_offset_15_79", { {"register", 16 } } },
		{ "R_offset_16_7a", { {"register", 16 } } },
		{ "R_offset_17_7b", { {"register", 16 } } },
		{ "R_offset_18_7c", { {"register", 16 } } },
		{ "R_offset_19_7d", { {"register", 16 } } },
		{ "R_offset_20_7e", { {"register", 16 } } },
		{ "R_offset_21_7f", { {"register", 16 } } },
		{ "R_offset_22_80", { {"register", 16 } } },
		{ "R_offset_23_81", { {"register", 16 } } },
	};

// -------------	SL_out	-------------
static const char TP_NAME_SL_out[] ="SL_out";
static const i2c::AddressRegisterMap TP_REGISTERS_SL_out = {
		{ "enable_MM_segments_00", { {"register", 1 } } },
		{ "enable_SL_output_01", { {"register", 1 } } },
		{ "SL_out_offset_02", { {"register", 3 } } },
	};

/*
 * Map-Pairing Register Files Arrays
 */
#define NUM_REGISTER_FILES 10

i2c::AddressRegisterMap registerFilesArr[NUM_REGISTER_FILES] = {
	TP_REGISTERS_NSW,
	TP_REGISTERS_MM_lnk,
	TP_REGISTERS_MM_addc,
	TP_REGISTERS_MM,
	TP_REGISTERS_MM_alg,
	TP_REGISTERS_MM_diag,
	TP_REGISTERS_sTGC_lnk,
	TP_REGISTERS_sTGC_V6,
	TP_REGISTERS_sTGC_alg,
	TP_REGISTERS_SL_out,
	};

std::string registerFilesNamesArr[NUM_REGISTER_FILES] = {
	TP_NAME_NSW,
	TP_NAME_MM_lnk,
	TP_NAME_MM_addc,
	TP_NAME_MM,
	TP_NAME_MM_alg,
	TP_NAME_MM_diag,
	TP_NAME_sTGC_lnk,
	TP_NAME_sTGC_V6,
	TP_NAME_sTGC_alg,
	TP_NAME_SL_out,
	};

#endif //NSWCONFIGURATION_TP_I2CREGISTERMAPPINGS_H_